- Source/DataProvider/BulkCopyReader.cs
fixed BulkCopyReader to work with Sap Hana provider.
> fixed BulkCopyReader

- Source/DataProvider/Oracle/OracleSqlOptimizer.cs
Would like to override this class, so I need it to be public.
> Make OracleSqlOptimizer class public

- Source/DataProvider/SQLite/SQLiteSqlBuilder.cs
- Source/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/DataProvider/OracleTest.cs
> Again, setting a class access modifier to public

- Source/Linq/Builder/UpdateBuilder.cs
- Tests/Linq/Update/UpdateTest.cs
#319 
I didn't specified against what databases test should run, because I don't have configured environment with all databases right now
> Test and fix for #319

- Source/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Update/UpdateTest.cs
> Issue 321 test and fix

- Source/Configuration/DataProviderElement.cs
- Source/Configuration/IConnectionStringSettings.cs
- Source/Configuration/IDataProviderSettings.cs
- Source/Configuration/ILinqToDBSettings.cs
- Source/Configuration/LinqToDBSection.cs
- Source/Configuration/NamedValue.cs
- Source/Data/DataConnection.cs
- Source/DataProvider/Access/AccessFactory.cs
- Source/DataProvider/DB2/DB2Factory.cs
- Source/DataProvider/DB2/DB2Tools.cs
- Source/DataProvider/Firebird/FirebirdFactory.cs
- Source/DataProvider/IDataProviderFactory.cs
- Source/DataProvider/Informix/InformixFactory.cs
- Source/DataProvider/MySql/MySqlFactory.cs
- Source/DataProvider/Oracle/OracleFactory.cs
- Source/DataProvider/Oracle/OracleTools.cs
- Source/DataProvider/PostgreSQL/PostgreSQLFactory.cs
- Source/DataProvider/PostgreSQL/PostgreSQLTools.cs
- Source/DataProvider/SQLite/SQLiteFactory.cs
- Source/DataProvider/SapHana/SapHanaFactory.cs
- Source/DataProvider/SqlCe/SqlCeFactory.cs
- Source/DataProvider/SqlServer/SqlServerFactory.cs
- Source/DataProvider/SqlServer/SqlServerTools.cs
- Source/DataProvider/Sybase/SybaseFactory.cs
- Source/LinqToDB.csproj
- Tests/Linq/DataProvider/AccessTests.cs
- Tests/Linq/DataProvider/SQLiteTests.cs
- Tests/Linq/DataProvider/SqlCeTests.cs
- Tests/Linq/Mapping/MappingSchemaTests.cs
- appveyor.yml
In general this is configuration abstraction against app.config
Needed for .Net Core support (#304)
> Configuration

- Source/DataProvider/Oracle/OracleSchemaProvider.cs
I have comments on tables in DB. But Oracle T4 Template does not fill Description properties on TableInfo's. Therefore there no XML comments on the generated code.
#456
> T4 Oracle Template does not generate XML code comments for tables.

- Source/Expressions/ConvertFromDataReaderExpression.cs
- Tests/Linq/UserTests/ConverterInsertTests.cs
converter for enum->string now possible
> bugfix for #468

- Source/Common/Tools.cs
- Source/DataProvider/SQLite/SQLiteTools.cs
a file URI only starts with "file://" the next slash is part of the path!
> Fix Linq2DB with System.Data.Sqlite on Mono

- Tests/FSharp/MappingSchema.fs
- Tests/FSharp/Models.fs
- Tests/FSharp/Tests.FSharp.fsproj
- Tests/FSharp/WhereTest.fs
- Tests/Linq/Linq/FSharpTests.cs
- Tests/Linq/TestBase.cs
As promised here is a passing test on how to use option types.
> Adding tests for F# option types

- Source/DataProvider/SQLite/SQLiteSqlBuilder.cs
This refers to the https://github.com/linq2db/linq2db/issues/525 issue.
> Fix sqlite build table name

- Source/Mapping/EntityDescriptor.cs
- Source/Mapping/EntityMappingBuilder.cs
- Source/Mapping/PropertyMappingBuilder.cs
- Tests/Linq/Mapping/FluentMappingTests.cs
- Fix Spaces to Tabs
- Fix Association should not Change IsColumn Attribute
- Support Inheritance via Fluent mapping (In Fluent Mapping we have the Problem, that Inherited classes do not have the attributes of the parent class!)
> Fluent mapping Fixes and Addons

- Source/Mapping/EntityDescriptor.cs
- appveyor.core.yml
- appveyor.yml
One test failed after merging #521
> trying to fix test fail after #521

- Source/Mapping/MappingSchema.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue548Tests.cs
Tests and fix for #548
Race condition issues around `MappingSchema.MetadataReaders`
> Tests and fix for #548

- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue273Tests.cs
test for issue 273 (issue still needs to be fixed!)
> Test for issue #273

- Source/Linq/Builder/GroupByBuilder.cs
- Tests/Linq/Linq/IssueTests.cs
- Tests/Model/ComplexPerson.cs
> #528 tests

- Source/SqlQuery/SelectQuery.cs
- Tests/Linq/Linq/IssueTests.cs
Column.Equals - recursive column compassion
> Tests for #508

- Source/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/ConcatUnionTests.cs
> Working on #415

- Source/Linq/Builder/ConcatUnionBuilder.cs
- Tests/Linq/Linq/ConcatUnionTests.cs
Added fix and test for issue #601
> Fix for issue #601 (Unions)

- Source/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/Linq/Builder/ExpressionBuilder.cs
- Source/Linq/Builder/TakeSkipBuilder.cs
- Source/Linq/Query.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue533Tests.cs
- Tests/Model/FullName.cs
- Tests/Model/IPerson.cs
> Fix for #533

- Source/DataProvider/Access/AccessSqlBuilder.cs
- Source/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue175Tests.cs
> fix for #175

- Source/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/Mapping/MappingSchema.cs
- Tests/Linq/TestBase.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue192Tests.cs
> Fix for #192

- Source/DataProvider/Access/AccessSchemaProvider.cs
see also http://stackoverflow.com/questions/21388962/columns-flags-field-values-for-columns-collection-of-ole-db-schema-collections for flags description
> fix #409 -> boolen types are no identitys

- Source/DataProvider/Oracle/OracleDataProvider.cs
- Tests/Linq/DataProvider/OracleTests.cs
One more test for issue.
Refactoring.
p.s. я не понял, нужно ли создавать pull request, если допиливается issue из ветки которая уже мерджилась в основную репу. Если коммит автоматом вам виден, то удалю.
> Issue 612: more test, refactoring

- Source/Compatibility/System/Collections/Concurrent/ConcurrentDictionary.cs
- Source/Mapping/EntityMappingBuilder.cs
- Source/Mapping/MappingSchema.cs
- Tests/Linq/Mapping/FluentMappingTests.cs
Resetting EntityDescriptor cache if EntityMappingBuilder is created
> Fix for #446

- Source/Linq/Query.cs
- Tests/Linq/OrmBattle/OrmBattleTests.cs
possible fix for connection leak
> connection leak on LoadWith

- Tests/Linq/Linq/GroupByTests.cs
Test for #365
Btw, WCF version of tests fails due to enums. Not sure if it is expected behavior or bug.
> Test for #365

- Source/SqlQuery/SelectQuery.cs
if we do have really big query calling QuetyVisitor.Find() takes too much time.
And IRL we do need only to compare the most low level expressions for two columns
> this fixes Column.Equals performance

- Source/Data/DataConnection.Linq.cs
- Source/DataProvider/BasicMerge.cs
- Source/DataProvider/BulkCopyReader.cs
- Source/DataProvider/DB2/DB2BulkCopy.cs
- Source/DataProvider/MultipleRowsHelper.cs
- Source/DataProvider/Oracle/OracleBulkCopy.cs
- Source/DataProvider/Oracle/OracleXmlTable.cs
- Source/DataProvider/SapHana/SapHanaBulkCopy.cs
- Source/DataProvider/SqlServer/SqlServerBulkCopy.cs
- Source/Mapping/ColumnDescriptor.cs
- Source/Mapping/EntityDescriptor.cs
- Source/Mapping/MappingSchema.cs
- Source/Mapping/MappingSchemaInfo.cs
- Source/ServiceModel/RemoteDataContextBase.cs
- Source/SqlQuery/SelectQuery.cs
- Tests/Linq/DataProvider/SqlServerTests.cs
#615 Moving EntityDescriptors cache to MappingSchemaInfo to avoid performance gap on using many MappingSchemas
> #615 perfomance fix

- NuGet/Readme.txt
- Source/Common/Configuration.cs
- Source/Properties/LinqToDBConstants.cs
- Source/project.json
- appveyor.yml
Versions and release notes for 1.8.0
> Prepare to release 1.8.0

- Source/SqlQuery/SqlDataType.cs
Latest changes break Sql functions using dicitionary fields (postgresql hstore).
> Fix for missing dictionary datatype

- Data/Create Scripts/Access.sql
- Data/Create Scripts/DB2.sql
- Data/Create Scripts/Firebird.sql
- Data/Create Scripts/Informix.sql
- Data/Create Scripts/MySql.sql
- Data/Create Scripts/Oracle.sql
- Data/Create Scripts/PostgreSQL.sql
- Data/Create Scripts/SQLite.sql
- Data/Create Scripts/SapHana.sql
- Data/Create Scripts/SqlCe.sql
- Data/Create Scripts/SqlServer.sql
- Data/Create Scripts/SqlServer2000.sql
- Data/Create Scripts/Sybase.sql
- Source/Data/CommandInfo.cs
- Source/Data/DataConnection.cs
- Source/DataProvider/DB2/DB2DataProvider.cs
- Source/DataProvider/DataProviderBase.cs
- Source/DataProvider/IDataProvider.cs
- Source/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
- Tests/Linq/Create/CreateData.cs
- Tests/Linq/Linq/SelectTests.cs
- Tests/Linq/Linq/SqlExtensionTests.cs
- Tests/Linq/Linq/SubQueryTests.cs
- Tests/Linq/TestBase.cs
- Tests/Linq/UserTests/Issue269Tests.cs
- Tests/Model/LinqDataTypes.cs
Possibility to configure `CommandBehavior` for different `DataProviders`
> Fix for #665

- Source/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/DataProvider/SqlCeTests.cs
- Tests/Linq/DataProvider/SqlServerTests.cs
> Fix for #700

- .github/ISSUE_TEMPLATE.md
- NuGet/Readme.txt
- README.md
- Source/Data/DataConnection.cs
- Source/Linq/Builder/SelectManyBuilder.cs
- Source/Properties/LinqToDBConstants.cs
- Source/ServiceModel/RemoteDataContextBase.cs
- Tests/Linq/Data/ProcedureTests.cs
- Tests/Linq/Exceptions/CommonTests.cs
- Tests/Linq/Linq/CommonTests.cs
- Tests/Linq/Linq/CountTests.cs
- Tests/Linq/Linq/DataContextTests.cs
- Tests/Linq/Linq/ExtensionTests.cs
- Tests/Linq/Linq/JoinTests.cs
- Tests/Linq/Linq/JoinToLimitedTests.cs
- Tests/Linq/Linq/ParserTests.cs
- Tests/Linq/Linq/SelectTests.cs
- Tests/Linq/Linq/StringFunctionTests.cs
- Tests/Linq/Linq/TableFunctionTests.cs
- Tests/Linq/Update/CreateTableTests.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/UserTests/MultiPartIdentifierTests.cs
- appveyor.yml
> prepare to release 1.8.1

- NuGet/Readme.txt
- Source/Common/Configuration.cs
- Source/Properties/LinqToDBConstants.cs
- Source/project.json
- appveyor.yml
> Release 1.8.2

- Source/DataProvider/DataProviderBase.cs
- Source/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
#714 - checking column for null
#715 - i'v switched off setting `CommandBehavior.KeyInfo` to avoid performance gap
> Fixes for #714 #715

- Source/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/Linq/ConvertTests.cs
Removing convert optimization, used to lead to wrong convert expressions
> Fix for #722

- Source/Common/Configuration.cs
- Source/Common/Tools.cs
- Source/Data/DataConnection.Async.cs
- Source/Data/DataConnection.cs
- Source/DataProvider/SqlServer/SqlServerRetryPolicy.cs
- Source/DataProvider/SqlServer/SqlServerTransientErrorDetector.cs
- Source/IRetryPolicy.cs
- Source/LinqToDB.csproj
- Source/LinqToDB.csproj.DotSettings
- Source/RetryLimitExceededException.cs
- Source/RetryPolicyBase.cs
- linq2db.4.5.sln.DotSettings
Base contract for retry policy strategy and db access wrapping
> Retry policy infrastructure

- Source/Common/Configuration.cs
- Source/Data/DataConnection.Async.cs
- Source/Data/DataConnection.cs
- Source/Data/RetryingDbCommand.cs
- Source/Data/RetryingDbConnection.cs
- Source/DataProvider/DataProviderBase.cs
- Source/DataProvider/IDataProvider.cs
- Source/DataProvider/SqlServer/SqlServerDataProvider.cs
- Source/DataProvider/SqlServer/SqlServerRetryPolicy.cs
- Source/IRetryPolicy.cs
- Source/LinqToDB.csproj
- Source/RetryPolicyBase.cs
- Tests/Linq/Data/RetryPolicyTest.cs
I'v reseted master to the latest "green" build & moved all changes to brunch with PR.
@andrewvk can you please avoid of direct pushes to master branch
> Feature retry policy

- Source/DataProvider/MySql/MySqlSqlBuilder.cs
- Source/Linq/Query.cs
- Source/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/Update/UpdateTests.cs
Fixes call of InsertOrUpdate without updateable fields. See #100, #732 
Implements insert if not exists operation
> fix for #100 and #732

- Source/DataProvider/Access/AccessSqlBuilder.cs
- Source/DataProvider/DB2/DB2SqlBuilderBase.cs
- Source/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Source/DataProvider/Informix/InformixSqlBuilder.cs
- Source/DataProvider/MySql/MySqlSqlBuilder.cs
- Source/DataProvider/Oracle/OracleSqlBuilder.cs
- Source/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Source/DataProvider/SQLite/SQLiteSqlBuilder.cs
- Source/DataProvider/SapHana/SapHanaOdbcSqlBuilder.cs
- Source/DataProvider/SapHana/SapHanaSqlBuilder.cs
- Source/DataProvider/SqlCe/SqlCeSqlBuilder.cs
- Source/DataProvider/SqlServer/SqlServer2000SqlBuilder.cs
- Source/DataProvider/SqlServer/SqlServer2005SqlBuilder.cs
- Source/DataProvider/SqlServer/SqlServerSqlBuilder.cs
- Source/DataProvider/Sybase/SybaseSqlBuilder.cs
- Source/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/DataProvider/OracleTests.cs
> Fix for #731

- Source/Extensions/ReflectionExtensions.cs
- Source/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/Linq/Builder/ExpressionContext.cs
- Source/Linq/Builder/SequenceContextBase.cs
- Source/Linq/Builder/TableBuilder.cs
- Source/Mapping/AssociationAttribute.cs
- Source/Mapping/AssociationDescriptor.cs
- Source/Mapping/EntityDescriptor.cs
- Tests/Linq/Linq/AssociationTests.cs
- Tests/Model/ParentChild.cs
> Generic Associations

- Source/Data/DataConnection.Linq.cs
- Source/Data/DataConnection.cs
Xml documentation for DataConnection class public surface
> [Documentation] DataConnection

- Source/Linq/Builder/AggregationBuilder.cs
- Source/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/Linq/Builder/GroupByBuilder.cs
- Source/Sql/Sql.ExpressionAttribute.cs
- Source/Sql/Sql.ExtensionAttribute.cs
- Source/SqlProvider/BasicSqlBuilder.cs
- Source/SqlQuery/SqlTable.cs
- Tests/Linq/Linq/FunctionTests.cs
Added possibility to use table as an expression. 
Added possibility to examine SelectQuery during Extension building. It may be useful for searching TableSource.
> Extension updates

- Source/Expressions/InternalExtensions.cs
- Source/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/Linq/Builder/TableBuilder.cs
- Tests/Linq/Linq/AssociationTests.cs
Possibility to use associations via extension methods
> extension associatiobs

- Source/DataProvider/SqlServer/SqlServer2000SchemaProvider.cs
- Source/DataProvider/SqlServer/SqlServerSchemaProvider.cs
That will also help `linq2db.t4models` to generate column attributes for computed columns:
`[Column(SkipOnInsert = true, SkipOnUpdate = true)]`
> Set SkipOnInsert and SkipOnUpdate for Computed columns for SqlServer

- Source/Linq/Builder/ContainsBuilder.cs
- Tests/Linq/Linq/ComplexTests.cs
> Fix for #329

- Source/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
Per Npgsql documentation set Guid type to uuid PostgreSQL type
http://www.npgsql.org/doc/types/basic.html
> Fix PostgreSQL issue creating table with Guid field

- Tests/Linq/Linq/SelectTests.cs
- Tests/Model/LinqDataTypes.cs
disable broken test for sql2014
> restore datetime mapping type for non-sqlserver providers

- Source/SqlProvider/BasicSqlOptimizer.cs
- Source/SqlQuery/QueryVisitor.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue825Tests.cs
> Regression test for #825

- Source/SqlProvider/BasicSqlBuilder.cs
> CanCombineParameters fix

- Source/Data/CommandInfo.cs
- Source/Data/DataConnectionExtensions.cs
Added additional async extensions.
Added documentation for MergeAsync methods.
Unified CancellationToken parameter name to cancellationToken.
> Added additional async extensions.

- Source/Expressions/IGenericInfoProvider.cs
- Source/Extensions/ReflectionExtensions.cs
- Source/Mapping/AssociationDescriptor.cs
- Source/Mapping/ColumnAttribute.cs
- Source/Mapping/ColumnDescriptor.cs
- Source/Mapping/EntityDescriptor.cs
- Source/Mapping/EntityMappingBuilder.cs
- Source/Mapping/FluentMappingBuilder.cs
- Source/Mapping/InheritanceMapping.cs
- Source/Mapping/MapValue.cs
- Source/Mapping/MappingSchema.cs
- Source/Mapping/PropertyMappingBuilder.cs
- mapping descriptors
- fluent mapper
- mapping schema
> Xml Documentation Part 5

- Source/SqlProvider/BasicSqlOptimizer.cs
- Source/SqlProvider/JoinOptimizer.cs
- Tests/Linq/Linq/JoinOptimizeTests.cs
Changed replacing fields mechanism to Walk method. Activated optimization for subqueries.
> Join Optimization improvements

- Source/Data/DataConnection.QueryRunner.cs
- Tests/Linq/Samples/ConcurrencyCheckTests.cs
> Fixed caching issue.

- Source/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/Linq/Builder/TableBuilder.cs
- Source/Mapping/AssociationDescriptor.cs
- Tests/Linq/Linq/AssociationTests.cs
- Tests/Model/ParentChild.cs
> Fixed predicate conversion for associations

- Source/Linq/Builder/AllJoinsBuilder.cs
- Source/Linq/Builder/BuildInfo.cs
- Source/Linq/Builder/ExpressionBuilder.cs
- Source/Linq/Builder/SelectManyBuilder.cs
- Source/Linq/Builder/TableBuilder.cs
- Source/LinqExtensions.cs
- Source/LinqToDB.Silverlight.4.csproj
- Source/LinqToDB.Silverlight.5.csproj
- Source/LinqToDB.WindowsStore.csproj
- Source/LinqToDB.csproj
- Source/SqlJoinType.cs
- Source/SqlProvider/BasicSqlBuilder.cs
- Source/SqlQuery/SelectQuery.cs
- Tests/Linq/Linq/JoinTests.cs
- Tests/Linq/TestBase.cs
It's implementation of feature #685
Add ed support for RIGHT and FULL joins. 
New extension functions for joins:
- Join (common function that changes join type via parameter)
- InnerJoin
- LeftJoin
- RightJoin
- FullJoin
> Implemented support for RIGHT and FULL joins.

- Source/DataProvider/Informix/InformixSchemaProvider.cs
I can not find a way to identify the default schema, so all not default schema.
> InformixSchemaProvider GetTables add SchemaName

- Source/DataProvider/PostgreSQL/PostgreSQLSqlOptimizer.cs
- Source/Sql/Sql.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue882Tests.cs
> Added conversion for PostgreSQL's DatePart realization.

- Source/Data/CommandInfo.cs
> Corrected lazy query execution.

- Source/DataProvider/DB2/DB2LUWSchemaProvider.cs
Potential exception as described here https://github.com/linq2db/linq2db/issues/874#issuecomment-336814069
> Fixed potential exception during DB2 schema filtering.

- Source/DataProvider/Oracle/OracleMappingSchema.cs
http://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT1841
> OracleMappingSchema  ConvertDateTimeToSql

- Source/project.json
> Removed library strong name for .NET Core 1.1

- Source/DataProvider/Oracle/OracleBulkCopy.cs
- Source/DataProvider/Oracle/OracleTools.cs
- Tests/Linq/DataProvider/OracleTests.cs
Change type of UseAlternativeBulkCopy from bool to enum => Update Oracle Unit test
> Additional Oracle Bulkcopy Insert Method to improve performance

- Tests/Linq/Linq/FunctionTests.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue773Tests.cs
> Issue 773 - add more tests and fix existing test

- Source/Linq/Query.cs
It may help in clearing all Query Caches.
See #894 .
> Added Query.ClearCaches method

- Source/Data/CommandInfo.cs
- Source/Data/RecordReaderBuilder.cs
- Source/LinqToDB.csproj
- Tests/Linq/Linq/InheritanceTests.cs
- Tests/Linq/Linq/QueryInheritanceTests.cs
- Tests/Linq/Tests.csproj
Fixes #895
It is extraction of needed functionality from TableBuilder.
> Introduced RecordReaderBuilder for reading objects hierarchy.

- Source/LinqToDB/ServiceModel/LinqService.cs
Reproducible only when run tests on whole TypesTests test fixture (4.5, Sqlite.MS).
> Fixed non stable conversion error.

- Source/LinqToDB/SqlProvider/JoinOptimizer.cs
- Tests/Linq/Linq/JoinOptimizeTests.cs
> Fixed bug with comparing tables

- Source/LinqToDB/Linq/QueryRunner.cs
- Tests/Linq/UserTests/Issue973Tests.cs
Currently there is no way to add parameters dynamically. This PR allows such transformations.
Fixes issue #973
> Added support of dynamic parameters.

- Source/LinqToDB/DataProvider/Oracle/OracleSqlOptimizer.cs
- Tests/Linq/Linq/DateTimeFunctionsTests.cs
> Corrected convertation for Date type in Oracle.

- Source/LinqToDB/Linq/Builder/TableBuilder.cs
- Source/LinqToDB/Mapping/AssociationAttribute.cs
- Source/LinqToDB/Mapping/AssociationDescriptor.cs
- Source/LinqToDB/Mapping/EntityDescriptor.cs
- Source/LinqToDB/Mapping/EntityMappingBuilder.cs
- Tests/Linq/Linq/AssociationTests.cs
- Tests/Linq/Mapping/FluentMappingTests.cs
Added additional Predicate property for AssociationAttribute.
Added additional fluent mapping methods for defining Association based on predicate.
Fixes issue #961
> Added additional Predicate property for AssociationAttribute.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Tests/Linq/Linq/AssociationTests.cs
This is a fix for another case of issue #170, when SelectMany used in query
> test and fix for #170 with SelectMany

- NuGet/Readme.txt
- Source/LinqToDB/Data/MergeDefinition.cs
- Source/LinqToDB/DataProvider/BasicMergeBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlQuery/SelectQuery.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Update/MergeTests.Operations.Delete.cs
- Tests/Linq/Update/MergeTests.Operations.DeleteBySource.cs
- Tests/Linq/Update/MergeTests.Operations.Insert.cs
- Tests/Linq/Update/MergeTests.Operations.Parameters.cs
- Tests/Linq/Update/MergeTests.Operations.Update.cs
- Tests/Linq/Update/MergeTests.Operations.UpdateBySource.cs
- Tests/Linq/Update/MergeTests.Operations.UpdateWithDelete.cs
- Tests/Linq/Update/MergeTests.TargetSourceOn.cs
do not merge yet. I need to add more tests to it
> Fix #986 + typed source projections support

- Source/LinqToDB/Expressions/Extensions.cs
- Tests/Linq/UserTests/Issue1046Tests.cs
> Corrected InheritanceMapping transformation for issue #1046.

- Source/LinqToDB/DataProvider/BasicMergeBuilder.cs
- Source/LinqToDB/LinqExtensions.cs
- Source/LinqToDB/Sql/Sql.Analytic.cs
Please review before merge.
Especially name of callback.
> Added callback for intercepting queries exactly before execution.

- Build/AppVeyor.NUnit.Tests.ps1
- Tests/Linq/Create/CreateData.cs
- Tests/Linq/UserTests/Issue1107Tests.cs
> [WIP] Fail AppVeyor build on test failure

- Tests/Base/TestUtils.cs
- Tests/FSharp/Models.fs
- Tests/FSharp/SelectTest.fs
- Tests/Linq/DataProvider/OracleTests.cs
- Tests/Linq/Linq/ComplexTests2.cs
- Tests/Linq/Linq/EnumMappingTests.cs
- Tests/Linq/Linq/FSharpTests.cs
- Tests/Linq/Linq/JoinTests.cs
- Tests/Linq/Update/DeleteTests.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/Update/MergeTests.Operations.Insert.cs
- Tests/Linq/Update/MergeTests.Operations.Parameters.cs
- Tests/Linq/UserTests/Issue421.cs
> Fix failing tests [part 2]

- Source/LinqToDB/DataProvider/DB2/DB2DataProvider.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Linq/CteTests.cs
> Added required RECURSIVE keyword for Recursive CTE's in Firebird, MySql, PostgreSQL.

- Source/LinqToDB/Linq/Builder/TableBuilder.AssociatedTableContext.cs
- Tests/Linq/UserTests/Issue1196Tests.cs
- Tests/Linq/UserTests/Issue975Tests.cs
Fixes issues #1195, #1196 and #975.
> Fix for issue #1196. Wrong ExpressionContext initialization.

- Source/LinqToDB/Linq/Expressions.cs
- Tests/Linq/Linq/SelectTests.cs
> Fix for issue #1213. Added support of HasValue for Nullable types. 

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Base/BaseDataContextSourceAttribute.cs
- Tests/Base/TestBase.cs
- Tests/Base/Tools/SettingsReader.cs
- Tests/Linq/Linq/SelectTests.cs
@igor-tkachev, please verify idea.
It may help in situations with #1202, and OData providers. Usually they also add check for null in projection.
> Implemented Null Propagation optimization.

- Source/LinqToDB/Data/CommandInfo.cs
- Tests/Linq/DataProvider/SqlServerTests.cs
> Added parameter rebinding for async execution. 

- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Tests/Linq/UserTests/Issue1225Tests.cs
@igor-tkachev, i have added partial fix for this issue. 
Problem with associations. If remove `AsQueryable` from test: everything works fine.
> Tests for #1225

- Source/LinqToDB/DataProvider/Oracle/OracleSqlBuilder.cs
- Source/LinqToDB/DataProvider/Oracle/OracleTools.cs
- Tests/Linq/DataProvider/OracleTests.cs
> Fix oracle identifiers quotation detection

- NuGet/Access/CopyMe.Access.tt.txt
- NuGet/DB2/CopyMe.DB2.tt.txt
- NuGet/Firebird/CopyMe.Firebird.tt.txt
- NuGet/Informix/CopyMe.Informix.tt.txt
- NuGet/MySql/CopyMe.MySql.tt.txt
- NuGet/Oracle/CopyMe.Oracle.tt.txt
- NuGet/PostgreSQL/CopyMe.PostgreSQL.tt.txt
- NuGet/SQLite/CopyMe.SQLite.tt.txt
- NuGet/SapHana/CopyMe.SapHana.tt.txt
- NuGet/SqlCe/CopyMe.SqlCe.tt.txt
- NuGet/SqlServer/CopyMe.SqlServer.tt.txt
- NuGet/Sybase.DataAction/CopyMe.Sybase.DataAction.tt.txt
- NuGet/Sybase/CopyMe.Sybase.tt.txt
- NuGet/t4models/CopyMe.tt.txt
> update t4 instructions

- NuGet/linq2db.nuspec
- Source/LinqToDB/LinqToDB.csproj
> Add SourceLink support

- NuGet/Pack.bat
- NuGet/PackAV.bat
- NuGet/Readme.txt
- NuGet/linq2db.t4models.nuspec
- NuGet/t4models/CopyMe.tt.txt
- NuGet/t4models/linq2db.t4models.props
- linq2db.sln
Fix #1251
I preserved init.ps1 for now. Do we really need it for anything?
> update linq2db.t4models package publishing

- Tests/Linq/UserTests/Issue1284Tests.cs
> Tests for #1284 - CTE generation issues

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/LinqToDB.csproj
- Tests/Linq/Linq/WhereTests.cs
- Tests/Linq/UserTests/Issue1261Tests.cs
Also fixed other related bug with Nullable fields.
> Fixes incorrect predicate generation. Issue #1261

- Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs
- Tests/Linq/Data/DataConnectionTests.cs
> Added additional Server version check for SQL Server.

- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Tests/Linq/Samples/JsonConvertTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
Added test sample test for Json usage in linq2db.
> Added missed support of CanBeNull in Sql.ExtesnionAttribute.

- NuGet/linq2db.Oracle.Managed.nuspec
- Tests/Linq/Tests.csproj
> update Oracle.ManagedDataAccess.Core nuget version

- Source/LinqToDB/Expressions/ConvertFromDataReaderExpression.cs
- Source/LinqToDB/Linq/Builder/ConcatUnionBuilder.cs
- Tests/Linq/Linq/ConcatUnionTests.cs
- Tests/Linq/Linq/DynamicColumnsTests.cs
> Fix for Issue #1319. Concat/Union with Dynamic columns.

- Source/LinqToDB/Common/Utils.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/Linq/CteTests.cs
Fixed recursive CTE generation when there are many CTEs in query mixed with non recursive CTEs.
Fixed bug in MakeUniqueNames function.
> Fixed recursive CTE generation.

- Source/LinqToDB/Linq/Builder/ConcatUnionBuilder.cs
- Tests/Linq/Linq/CteTests.cs
There is a problem with deep nesting for recursive CTE.
Proposed patch tried to solve problem. 
Needs @igor-tkachev reviewing.
> Fix for complex recursive CTE queries.

- Source/LinqToDB/Data/DataConnection.QueryRunner.cs
- Source/LinqToDB/Data/DataReader.cs
- Source/LinqToDB/Data/DataReaderAsync.cs
- Tests/Linq/Data/TraceTests.cs
Issue #1355.
Added tracing to the DataReader wrapper's Dispose method.
Looks like the project didn't have any tests related to the tracing, so I've added a fixture.
> DataReader reporting TraceInfoStep.Completed step

- NuGet/linq2db.nuspec
- Source/LinqToDB/LinqToDB.csproj
- Tests/Base/Tests.Base.csproj
- Tests/IBM.Core/Tests.IBM.Core.csproj
- Tests/Linq/DataProvider/FirebirdTests.cs
- Tests/Linq/DataProvider/MySqlTests.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
- Tests/Linq/DataProvider/SybaseTests.cs
- Tests/Linq/Linq/AssociationTests.cs
- Tests/Linq/Linq/ConcatUnionTests.cs
- Tests/Linq/Linq/CteTests.cs
- Tests/Linq/Linq/DynamicColumnsTests.cs
- Tests/Linq/Linq/EntityCreatedTests.cs
- Tests/Linq/Linq/JoinTests.cs
- Tests/Linq/Linq/OrderByDistinctTests.cs
- Tests/Linq/Linq/WhereTests.cs
- Tests/Linq/Samples/JsonConvertTests.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/Update/BulkCopyTests.cs
- Tests/Linq/Update/CreateTempTableTests.cs
- Tests/Linq/UserTests/Issue1174Tests.cs
- Tests/Linq/UserTests/Issue1196Tests.cs
- Tests/Linq/UserTests/Issue1222Tests.cs
- Tests/Linq/UserTests/Issue1225Tests.cs
- Tests/Linq/UserTests/Issue1268Tests.cs
- Tests/Linq/UserTests/Issue1303Tests.cs
- Tests/Linq/UserTests/Issue975Tests.cs
- Tests/Model/Tests.Model.csproj
- Tests/Tests.Playground/TestTemplate.cs
- Tests/Tests.Playground/Tests.Playground.csproj
- update nunit and remove [Combinatorial] workaround from tests
- updated `System.Data.SqlClient` dependency from 4.4.2 to 4.5.1. Fixes #1342
> Update some nuget dependencies

- Source/LinqToDB/SqlQuery/SqlStatement.cs
- Tests/Linq/UserTests/Issue1363Tests.cs
> Fixed issue #1363, missed correct IsParameterDependent for Statement.

- Doc/articles/sql/Window-Functions-(Analytic-Functions).md
previously it was linking directly to a line number, but that line didn't make much sense to link to anymore, might want to fix that
> [ci skip] fix link to Analytic file

- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/Data/DataConnection.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteTools.cs
- Tests/Linq/Data/DataConnectionTests.cs
> Add DataConnection.OnConnectionOpened event

- Source/LinqToDB/Linq/Builder/AggregationBuilder.cs
- Source/LinqToDB/Linq/Builder/AllAnyBuilder.cs
- Source/LinqToDB/Linq/Builder/CountBuilder.cs
- Source/LinqToDB/Linq/Builder/SubQueryContext.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/UserTests/Issue873Tests.cs
Fixed long standing issue #873.
Problem was in bad bug-fix for #67 and issue from BLToolkit http://www.rsdn.ru/forum/prj.rfd/4844518.aspx
Removed unnecessary code from `SubQueryContext` and corrected other contexts.
> Fix for issue #873. Count() in SubQueryContext.

- Source/LinqToDB/ExpressionMethodAttribute.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Mapping/EntityDescriptor.cs
- Source/LinqToDB/Mapping/EntityMappingBuilder.cs
- Source/LinqToDB/Mapping/PropertyMappingBuilder.cs
- Tests/Linq/Mapping/FluentMappingAliasTests.cs
- Tests/Linq/Mapping/FluentMappingExpressionMethodTests.cs
> Fixes issue #1365. Added additional methods for simplifying mapping.

- Build/linq2db.Default.props
- NuGet/Access/linq2db.Access.props
- NuGet/DB2/linq2db.DB2.props
- NuGet/Firebird/linq2db.Firebird.props
- NuGet/Informix/linq2db.Informix.props
- NuGet/MySql/linq2db.MySql.props
- NuGet/Oracle/linq2db.Oracle.props
- NuGet/PostgreSQL/linq2db.PostgreSQL.props
- NuGet/SQLite/linq2db.SQLite.props
- NuGet/SapHana/linq2db.SapHana.props
- NuGet/SqlCe/linq2db.SqlCe.props
- NuGet/Sybase.DataAction/linq2db.Sybase.DataAction.props
- NuGet/Sybase/linq2db.Sybase.props
- NuGet/linq2db.t4.props
- NuGet/t4models/linq2db.t4models.props
> Add missing msbuild namespace to props files

- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlQuery/SqlField.cs
- Source/LinqToDB/SqlQuery/SqlTable.cs
- Tests/Linq/UserTests/Issue1403Tests.cs
> Apply columns ordering only to CREATE TABLE statement as it was intended

- Source/LinqToDB/Linq/Builder/ConcatUnionBuilder.cs
- Tests/Linq/UserTests/Issue1412Tests.cs
I hope this is last commit in this area.
@jogibear9988, please test fix on your sources before next patch release.
> Fix for #1412. Used first sequence for building expression.

- Source/LinqToDB/Linq/Builder/ConcatUnionBuilder.cs
- Source/LinqToDB/Linq/Builder/IBuildContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.CteTableContext.cs
- Tests/Linq/Linq/CteTests.cs
> Fix for issue #1435. Improved UnionContext functionality. Fixed CTE Context

- Source/LinqToDB/Data/DataConnection.QueryRunner.cs
Fixes issue reported as part of #1185
> Fix CommandBehavior selection for async reader queries

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
- Tests/Base/TestBase.cs
- Tests/Linq/UserTests/Issue1438Tests.cs
> [PostgreSQL] Don't try to call provider-specific methods if they are not enabled

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.RawSqlContext.cs
- Tests/Base/QueryUtils.cs
- Tests/Linq/Linq/FromSqlTests.cs
Just improved parameters parsing.
> Redesigned parameter parsing for FromSql method.

- Source/LinqToDB/Mapping/EntityDescriptor.cs
- Tests/Linq/UserTests/Issue999Tests.cs
Added unit test that reproduces #999.
> Fixed problem with EntityDescriptor initialization.

- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/Linq/ConcatUnionTests.cs
Fixes issue #1492
Minor fix for CTE naming.
> Fixed problem with SelectContext in Union case when selecting just parameter value.

- Source/LinqToDB/DataProvider/Access/AccessSchemaProvider.cs
> Fix access bit fields reported as identity by schema provider

- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Source/LinqToDB.Templates/README.md
- Tests/T4.Linq/SqlServer.tt
> Add GenerateProcedureResultAsList T4 option

- NuGet/MySqlConnector/CopyMe.MySqlConnector.tt.txt
- NuGet/MySqlConnector/LinqToDB.MySqlConnector.Tools.ttinclude
- NuGet/MySqlConnector/linq2db.MySqlConnector.props
- NuGet/Pack.bat
- NuGet/PackAV.bat
- NuGet/linq2db.MySqlConnector.nuspec
- Tests/Linq/Update/MergeTests.Types.cs
- linq2db.sln
Remaining tasks for MySqlConnector provider:
> linq2db.MysqlConnector nuget package

- Source/LinqToDB.Templates/DataAnnotations.ttinclude
- Source/LinqToDB.Templates/LinqToDB.Firebird.ttinclude
- Source/LinqToDB.Templates/LinqToDB.PostgreSQL.ttinclude
- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Source/LinqToDB.Templates/NotifyPropertyChanged.ttinclude
- Source/LinqToDB.Templates/T4Model.ttinclude
- Source/LinqToDB.Templates/Validation.ttinclude
Backport from #1393 to fix #1516
> [T4] Proper string literals generation

- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/DataContext.cs
- Source/LinqToDB/DataContextTransaction.cs
- Tests/Linq/Data/TransactionTests.cs
- add BeginTransactionAsync to DataConnection and DataContext. Fix #1497
> Add BeginTransactionAsync method

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.AssociatedTableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Base/Tools/ComparerBuilder.cs
- Tests/Linq/Linq/QueryableAssociationTests.cs
> Fix for issue #1523. Improved custom Associations generation.

- Source/LinqToDB/Data/CommandInfo.cs
- Source/LinqToDB/Data/RecordReaderBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Mapping/EntityDescriptor.cs
- Tests/Linq/Linq/SelectTests.cs
> Support complex properties mapping in raw queries

- Source/LinqToDB/Linq/Builder/ExpressionContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.cs
- Tests/Linq/UserTests/Issue1556Tests.cs
> NullReferenceException on InnerJoin

- Source/LinqToDB/Linq/Builder/TableBuilder.RawSqlContext.cs
- Tests/Linq/Linq/FromSqlTests.cs
> Added support of NewArrayExpression for FromSql method.

- Source/LinqToDB.Templates/T4Model.ttinclude
> Issue 1550

- Source/LinqToDB.Templates/T4Model.ttinclude
> Issue 1551

- Tests/Linq/DataProvider/SqlCeTests.cs
need use data annotation [Column(DataType = DataType.Image), Nullable]
> Test for issue #393

- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/JoinOptimizer.cs
- Tests/Linq/Linq/QueryableAssociationTests.cs
> Fix for issue #1560. Improved Join Optimization.

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
Added preliminary `NpgsqlRange<>` type support.
Added missing extension point for Expressions.
> Various fixes for EF Core support.

- Tests/Linq/Linq/SubQueryTests.cs
> Test for issue #1601. Unoptimal SQL when suing let in linq query.

- Tests/Linq/Mapping/FluentMappingTests.cs
> tests for issue #291

- Tests/Linq/UserTests/Issue1298Tests.cs
> tests to reproduce issue #1298

- Tests/Linq/Linq/TableFunctionTests.cs
> tests for issue#386

- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/Data/DataConnection.cs
- Tests/Linq/Data/DataConnectionTests.cs
> Add Event  OnBeforeConnectionOpen & OnBeforeConnectionOpenAsync

- Tests/Linq/Linq/DateTimeFunctionsTests.cs
> Test to reproduce issue#1615

- Source/LinqToDB/DataContext.cs
- Tests/Linq/Linq/DataContextTests.cs
> fix#1513  Add constr for DataContext(providerName, connectionString)

- Doc/articles/FAQ.md
- Doc/articles/sql/CTE.md
- Doc/articles/sql/Join-Operators.md
- README.md
- Source/LinqToDB/Sql/Readme.md
Placeholder for Updating/adding Readme.MD files.
> Readme and Doc updates

- Source/LinqToDB/Linq/Builder/TableBuilder.CteTableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/Linq/CteTests.cs
> Fix #1653. Wrong embedded CTE processing.

- Tests/Linq/Linq/SelectTests.cs
> Tests for reproduce #1202

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Tests/Linq/Linq/SelectTests.cs
Also improved conditions in projection expression.
Fix #1664
> Added ExpressionMethod support for Convert.

- Tests/Linq/DataProvider/SqlServerTests.cs
> issue_1613  Test

- Tests/Linq/Linq/DateTimeFunctionsTests.cs
> test reproduced issue 1675

- Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs
- Source/LinqToDB/Linq/Builder/ScalarSelectBuilder.cs
- Tests/Linq/Linq/DateTimeFunctionsTests.cs
- Tests/Linq/Linq/TakeSkipTests.cs
> Fix for issue #1675. Added missing parent index calculation.

- Source/LinqToDB/Data/DataConnection.cs
- Tests/Linq/Data/DataConnectionTests.cs
> Сhanged the behavior of CommandTimeout properties

- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/LeftJoinTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
> Prevent subquery optimization for Left Join.

- Source/LinqToDB/SqlQuery/QueryVisitor.cs
- Source/LinqToDB/SqlQuery/SqlDeleteStatement.cs
- Source/LinqToDB/SqlQuery/SqlInsertOrUpdateStatement.cs
- Source/LinqToDB/SqlQuery/SqlInsertStatement.cs
- Source/LinqToDB/SqlQuery/SqlSelectStatement.cs
- Source/LinqToDB/SqlQuery/SqlUpdateStatement.cs
- Source/LinqToDB/SqlQuery/SqlWithClause.cs
- Tests/Linq/Linq/CteTests.cs
> Added missing Clone and Convert parts for SqlWithClause.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionTestGenerator.cs
- Tests/Linq/Linq/SelectTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
> Fixed problem with ConditionalExpression projection.

- Doc/README.md
- Doc/articles/general/Managing-data-connection.md
- Doc/articles/general/databases.md
- Doc/articles/general/supportedfw.md
- Doc/articles/releasenotes/2.0.0.md
I'm trying to go over all the existing md files in the doc folder for us to have a clean(er) baseline.
> [WIP] Documentation improvements

- Source/LinqToDB/Linq/Builder/ConcatUnionBuilder.cs
- Tests/Linq/UserTests/Issue1736Tests.cs
> Fix for issue #1736

- Source/LinqToDB/Linq/Builder/ConcatUnionBuilder.cs
- Tests/Linq/UserTests/IndexOutOfRangeInUnions.cs
> Added additional Conditions for Union projection generation.

- Source/LinqToDB/Data/DataConnection.QueryRunner.cs
- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/ServiceModel/RemoteDataContextBase.QueryRunner.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlProvider/ISqlOptimizer.cs
- Source/LinqToDB/SqlProvider/SqlOptimizerExtensions.cs
- Source/LinqToDB/SqlQuery/QueryVisitor.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlSelectClause.cs
- Source/LinqToDB/SqlQuery/SqlStatement.cs
- Tests/Linq/Linq/SelectTests.cs
- Tests/Linq/Linq/TakeSkipTests.cs
Fix #1734 
It fixes issue, but looks like we have to improve SQL optimizer.
> Fix for #1734. Improving CASE handling in SqlBuilder.

- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/Linq/ExpressionsTests.cs
generate proper comparison of nullable operands if at least one of them is SqlExpression
> fix nullable comparisons with expressions

- Source/LinqToDB/SqlQuery/QueryVisitor.cs
> Fixed Convert function for correct handling replacements.

- Source/LinqToDB/LinqToDB.csproj
- Tests/Linq/Linq/GroupByTests.cs
- appveyor.yml
> Release 2.7.4

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Expressions.cs
- Tests/Linq/Linq/ExpressionsTests.cs
This PR allows to map any binary expression to extension function.
Fix #1723
> Added ability to map binary expressions to SQL.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/Linq/SelectTests.cs
> Fix another reverse null check case

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Expressions.cs
- Tests/Base/TestBase.cs
- Tests/Linq/Linq/SelectScalarTests.cs
- Tests/Linq/Linq/WhereTests.cs
Fix #1755
Fix #1776
Fix #1777 
also fixed #1788
> Fix multiple issues with Nullable<T>.HasValue translation to null check

- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/AssociationTests.cs
> Fix weak joins optimization

- Source/LinqToDB.Templates/README.md
- Source/LinqToDB/SchemaProvider/GetSchemaOptions.cs
- Source/LinqToDB/SchemaProvider/LoadTableData.cs
- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
- Source/LinqToDB/SchemaProvider/TableInfo.cs
- Tests/T4.Linq/SqlServer.generated.cs
- Tests/T4.Linq/SqlServer.tt
Fix #1667
Fix #1640
Adds new callback to schema load options to filter out tables and views before they pollute GetSchema results and generated T4 code
> Implement GetSchema table load filtering

- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/Linq/Builder/SelectManyBuilder.cs
- Source/LinqToDB/SqlQuery/SqlSelectClause.cs
- Tests/Linq/Linq/AnalyticTests.cs
- Tests/Linq/Linq/SelectManyTests.cs
> Force subquery context for SelectManyBuilder left-side select query

- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlTableSource.cs
- Tests/Linq/Linq/JoinTests.cs
Fixes #1816 
Actually it is another form of #1614
> Fix another case of incorrect weak join optimization

- Source/LinqToDB/SqlQuery/CteClause.cs
- Tests/Linq/UserTests/Issue1584Tests.cs
- Tests/Linq/UserTests/Issue1817Tests.cs
> Fix for #1584 and #1817 - Cte.

- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Linq/Builder/BuildInfo.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Source/LinqToDB/Linq/Builder/MethodChainBuilder.cs
- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Source/LinqToDB/Sql/Sql.Strings.cs
- Tests/Linq/Linq/CteTests.cs
- Tests/Linq/UserTests/Issue1564Tests.cs
Reviewed again how custom aggregates should work.
> Fix for #1564. Improved custom aggregates functionality.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Tests/Linq/Linq/SelectTests.cs
- Tests/Linq/UserTests/Issue1838Tests.cs
> Fix for #1838. Missing conversion for conditional.

- Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs
- Source/LinqToDB/LinqToDB.csproj
- Source/LinqToDB/Metadata/MetadataReader.cs
- Source/LinqToDB/Metadata/SystemDataSqlServerAttributeReader.cs
- Tests/Linq/DataProvider/SqlServerTypesTests.cs
- Tests/Linq/Tests.csproj
Improves spatial types support for sql server for netcoreapp2.0
> enable SystemDataSqlServerAttributeReader for .net core 2

- Source/LinqToDB/SqlQuery/QueryVisitor.cs
> Added support for transforming SqlPredicate.FuncLike into another predicate.

- .editorconfig
- .gitattributes
- Build/Azure/README.md
- Build/Azure/net46/sqlserver.2017.json
- Build/Azure/netcoreapp20/sqlserver.2017.json
- Build/Azure/scripts/mac.sqlserver.2017.sh
- Build/Azure/scripts/mysql.sh
- Build/Azure/scripts/pgsql.sh
- Build/Azure/scripts/sqlserver.2017.cmd
- Build/Azure/scripts/sqlserver.2017.sh
- NuGet/linq2db.nuspec
- Source/LinqToDB/LinqToDB.csproj
- Tests/Base/TestBase.cs
- Tests/DataProviders.json
- Tests/Linq/App.config
- Tests/Linq/Linq/DateTimeOffsetTests.cs
- azure-pipelines.yml
- linq2db.sln
Without Northwind/FTS tests now
> [Azure DevOps] SQL Server 2017 support

- Source/LinqToDB/DataContext.cs
- Tests/Linq/Linq/DataContextTests.cs
> Fix for #1891. Fixed problem with closing connection via DataContext.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.AssociatedTableContext.cs
- Tests/Linq/UserTests/Issue1885Tests.cs
> Fix for #1885. Redirected expression building to inner context.

- Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs
- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/UserTests/Issue1869Tests.cs
- linq2db.playground.sln
> Fix for #1869. Fixed incorrect SearchCondition handling. Fixed CanBeNull for SqlExtension.

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/SqlQuery/SqlField.cs
- Tests/Linq/Linq/DynamicColumnsTests.cs
- Tests/Linq/UserTests/Issue1900Tests.cs
> Fix for #1900. Added IsDynamic property to filter dynamically created fields.

- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Tests/T4.Linq/SqlServer.generated.cs
- Tests/T4.Linq/SqlServer.tt
> [T4] properly replace column attribute during generation

- Data/Create Scripts/SqlServer.sql
- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Source/LinqToDB.Templates/README.md
- Tests/Linq/DataProvider/SqlServerTests.cs
- Tests/T4.Linq/SqlServer.generated.cs
- Tests/T4.Linq/SqlServer.tt
- Tests/T4.Linq/SqlServer.ttinclude
Adds support for return value parameter generation for procedures by T4.
Fixes #1897
> [t4] procedure return value support

- Source/LinqToDB/ExpressionMethodAttribute.cs
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Mapping/PropertyMappingBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Mapping/FluentMappingTests.cs
> Fix for #1892. Added proper Aliases generation for ExpressionMethodAttribute.

- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/HasUniqueKeysBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.CteTableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Sql/Sql.Analytic.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlProvider/JoinOptimizer.cs
- Tests/Linq/Linq/CteTests.cs
- Tests/Linq/Linq/OptimizerTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
Solves problems found during analysis issue #1875
> Fixed found problems with CTE and HasUniqueKeysBuilder.

- Build/Azure/README.md
- NuGet/linq2db.Access.nuspec
- NuGet/linq2db.nuspec
- Source/LinqToDB/Data/DataConnection.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeBulkCopy.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeDataProvider.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeFactory.cs
- Source/LinqToDB/LinqToDB.csproj
- Tests/Base/TestBase.cs
- Tests/Linq/Create/CreateData.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/TestsInitialization.cs
- Tests/Linq/UserTests/Issue0010Tests.cs
- Tests/Linq/UserTests/Issue1164Tests.cs
- Tests/Tests.Android/Tests.Android.csproj
- Tests/Tests.Android/app.config
- Tests/Tests.Android/packages.config
> Netcore providers support part2

- Build/linq2db.Default.props
- Data/Create Scripts/Oracle.sql
- Data/Create Scripts/SqlServer2000.sql
- Source/LinqToDB/DataExtensions.cs
- Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs
- Source/LinqToDB/DataType.cs
- Source/LinqToDB/Expressions/ExpressionGenerator.cs
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Expressions/SqlQueryDependentAttribute.cs
- Source/LinqToDB/Expressions/TypeMapper.cs
- Source/LinqToDB/Expressions/TypeWrapper.cs
- Source/LinqToDB/Expressions/TypeWrapperExtensions.cs
- Source/LinqToDB/Expressions/WrapperAttribute.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/SetOperationBuilder.cs
- Source/LinqToDB/Linq/Query.cs
- Tests/Linq/DataProvider/OracleTests.cs
- Tests/Linq/Linq/TestQueryCache.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/TestsInitialization.cs
- Tests/Linq/TypeMapping/MappingTests.cs
- Tests/Linq/TypeMapping/OracleWrappingTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
- appveyor.yml
> Release 2.9.2

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
Fixes https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/20
> Fixes problem with EF Extension. Buggy reflection check.

- Source/LinqToDB/DataProvider/Oracle/OracleSchemaProvider.cs
- Tests/T4.Linq/Oracle.generated.cs
> [T4/Schema] Fix Oracle Long/Long Raw type hints

- Data/Create Scripts/SqlServer.sql
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSchemaProvider.cs
- Tests/Linq/DataProvider/SqlServerTests.cs
- Tests/T4.Linq/SqlServer.2017.generated.cs
- Tests/T4.Linq/SqlServer.2017.tt
- Tests/T4.Linq/Tests.T4.Linq.csproj
Fix #1921
Looks like we need to release new linqpad integration after this release
> [MSSQL] Fix table function schema load in SQL2017+

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/UserTests/Issue1946Tests.cs
> Fix for #1946. Wrong logic when processing Enum conversion.

- appveyor.yml
> Release 2.9.3 (with proper nuget version)

- Source/LinqToDB/Linq/Builder/AllJoinsLinqBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectManyBuilder.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/QueryVisitor.cs
- Source/LinqToDB/SqlQuery/SqlSelectClause.cs
- Tests/Linq/UserTests/Issue1964Tests.cs
Fixes #1964
Partially back-ported needed functionality from 3.0.
> Fix for #1964. Corrected Join condition nesting. 

- Source/LinqToDB/Linq/Builder/InsertBuilder.cs
- Tests/Linq/Update/InsertTests.cs
> Fix for #1962. Ensure that all Insert expressions are in SELECT clause.

- Source/LinqToDB/DataExtensions.cs
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/UserTests/Issue1969Tests.cs
> Fix for #1969. Handling additional cases when processing ExpressionMethod.

- Source/LinqToDB/Linq/Builder/TableBuilder.AssociatedTableContext.cs
- Tests/Linq/UserTests/Issue1974Tests.cs
> Fix for #1974. Fixed nullable associations materialization.

- .travis.yml
- Build/linq2db.Default.props
- Source/LinqToDB/Data/RetryPolicy/RetryingDbConnection.cs
- Source/LinqToDB/DataExtensions.cs
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Linq/Builder/AllJoinsLinqBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/InsertBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectManyBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.AssociatedTableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/QueryVisitor.cs
- Source/LinqToDB/SqlQuery/SqlSelectClause.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/UserTests/Issue1084Tests.cs
- Tests/Linq/UserTests/Issue1964Tests.cs
- Tests/Linq/UserTests/Issue1965Tests.cs
- Tests/Linq/UserTests/Issue1968Tests.cs
- Tests/Linq/UserTests/Issue1969Tests.cs
- Tests/Linq/UserTests/Issue1974Tests.cs
- appveyor.yml
> Release 2.9.4

- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/SqlQuery/CteClause.cs
- Source/LinqToDB/SqlQuery/QueryVisitor.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/UserTests/Issue2008Tests.cs
Fix for #2008. Corrected nesting fix in SelectQueryOptimizer. Migrated part of ConvertImmutable from 3.0.
> Fix for #2008. Corrected nesting fix in SelectQueryOptimizer

- Source/LinqToDB/LinqExtensions.cs
- Tests/Linq/UserTests/Issue2000Tests.cs
> Fix for #2000. Added additional constant handling for interfaces.

- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Tests/Linq/UserTests/Issue1983Tests.cs
Test for #1983 
@sdanyliv also check generated SQL - it is too verbose
> Issue 1983

- Source/LinqToDB/DataProvider/Access/AccessSqlBuilder.cs
- Source/LinqToDB/DataProvider/DataTools.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseSqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/SqlQuery/ConditionBase`2.cs
- Source/LinqToDB/SqlQuery/QueryVisitor.cs
- Source/LinqToDB/SqlQuery/SqlParameter.cs
- Source/LinqToDB/SqlQuery/SqlPredicate.cs
- Tests/Linq/Common/DataToolsTests.cs
- Tests/Linq/Linq/StringFunctionTests.cs
- Tests/Tests.Playground/Issue1925Tests.cs
> #1925 and #776 Repro Test and fix

- Source/LinqToDB/DataProvider/SqlServer/SqlServer2000SqlOptimizer.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServer2005SqlOptimizer.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServer2012SqlOptimizer.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServer2017SqlOptimizer.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerDataProvider.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlOptimizer.cs
- Tests/Linq/UserTests/Issue1982Tests.cs
> Use TIME type when converting from DateTime to Time for MSSQL2008+

- Tests/Linq/Tests.csproj
> Downgrade System.Threading.Tasks.Extensions version for net46 target

- NuGet/Access/CopyMe.Access.tt.txt
- NuGet/DB2/CopyMe.DB2.tt.txt
- NuGet/Firebird/CopyMe.Firebird.tt.txt
- NuGet/Informix/CopyMe.Informix.tt.txt
- NuGet/MySql/CopyMe.MySql.tt.txt
- NuGet/MySqlConnector/CopyMe.MySqlConnector.tt.txt
- NuGet/Oracle/CopyMe.Oracle.tt.txt
- NuGet/PostgreSQL/CopyMe.PostgreSQL.tt.txt
- NuGet/SQLite/CopyMe.SQLite.tt.txt
- NuGet/SapHana/CopyMe.SapHana.tt.txt
- NuGet/SqlCe/CopyMe.SqlCe.tt.txt
- NuGet/SqlServer/CopyMe.SqlServer.tt.txt
- NuGet/Sybase.DataAction/CopyMe.Sybase.DataAction.tt.txt
- NuGet/Sybase/CopyMe.Sybase.tt.txt
- Source/LinqToDB.Templates/README.md
Fix #2002 
well, kinda fix - we cannot fix it, only provide some limited guideance to users
> Add notes about error when wrong t4 tool selected

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Tests/Linq/Linq/SelectTests.cs
> Fix for #2031. Added missing functionality for processing subqueries.

- Source/LinqToDB/Reflection/TypeAccessorT.cs
- Tests/Linq/UserTests/Issue2052Tests.cs
> Fix for #2052. Added filter for Reference properties.

- Data/Create Scripts/PostgreSQL.sql
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSchemaProvider.cs
- Tests/Linq/SchemaProvider/PostgreSQLSchemaProviderTests.cs
> Add materialized views schema read for PostgreSQL

- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Linq/CteTests.cs
> Fix for #2061. Corrected CTE header generation.

- Source/LinqToDB/Linq/Builder/TableBuilder.CteTableContext.cs
- Source/LinqToDB/SqlQuery/CteClause.cs
> Fixes NRE when building CTE. CTE refactoring.

- Source/LinqToDB/Linq/ExpressionQuery.cs
- Tests/Linq/Linq/SelectTests.cs
> Fix for #2073. Removed SqlText caching for ToString() method.

- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Tests/Linq/Linq/CteTests.cs
Fixes #2072 
Not reproduced but added additional case handling based on StackTrace.
> Added additional check for Declaring type. Possible fix for #2072.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Tests/Linq/Microsoft/MicrosoftODataTests.cs
- Tests/Linq/Tests.csproj
- Tests/Tests.Playground/Tests.Playground.csproj
> Fix for #2070. Added additional Unwrapping of Convert expression to handle OData specific queries.

- Source/LinqToDB/DataProvider/Oracle/OracleSqlOptimizer.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeSqlOptimizer.cs
- Tests/Linq/Linq/AllAnyTests.cs
- Tests/Linq/Linq/TakeSkipTests.cs
Fixes #2063 
Corrected query transformation for handling Oracle's pagination rules. 
Also fixed found limitation in SqlCe.
> Fix for #2063. Corrected query transformation for handling Oracle's pagination rules.

- Tests/Linq/Linq/ComplexTests.cs
> Test for issue 413

- Tests/Base/TestBase.cs
- Tests/Linq/Linq/GroupByTests.cs
> Tests for issue 672.

- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlDataType.cs
- Tests/Linq/UserTests/Issue1960Tests.cs
Discovered during looking into #1960
> Use int? in SqlDataType for optional sizes

- Source/LinqToDB/DataProvider/SqlServer/SqlServerDataProvider.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Source/LinqToDB/Linq/Builder/OrderByBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Microsoft/MicrosoftODataTests.cs
> Fix for #2092. Improved SelectContext to handle grouping and unexpected conversions.

- Source/LinqToDB/DataContextTransaction.cs
> DataContextTransaction: pass cancellation tokens to BeginTransactionAsync

- Source/LinqToDB/Expressions/DefaultValueExpression.cs
- Source/LinqToDB/Linq/Builder/DefaultIfEmptyBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/Data/DataExtensionsTests.cs
- Tests/Linq/Linq/SelectManyTests.cs
> Fix for #2097. Safe handling of non-table members. Fixed other found issues.

- Data/Create Scripts/SqlServer.sql
- Source/LinqToDB/DataProvider/SqlServer/SqlServerMappingSchema.cs
- Tests/Linq/Data/ProcedureTests.cs
> Fixed ColumnNameComparer for sql server 

- Source/LinqToDB/Data/DataConnectionExtensions.cs
- Tests/Linq/Data/ProcedureTests.cs
- Tests/Linq/Data/QueryMultipleResultTests.cs
- Tests/Linq/DataProvider/SqlServerTests.cs
> Added some overloads accepting sql parameters as object

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.RawSqlContext.cs
- Source/LinqToDB/Linq/Builder/UpdateBuilder.cs
- Source/LinqToDB/LinqExtensions.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlQuery/SqlSetExpression.cs
- Tests/Linq/Update/UpdateTests.cs
> Added possibility to define custom Set expression for Updates.

- Source/LinqToDB/Linq/Internals.cs
- Source/LinqToDB/LinqExtensions.cs
- Tests/Linq/Linq/InternalsTests.cs
> Exposed way to access to DataContext from query.

- Source/LinqToDB/Linq/Builder/SetOperationBuilder.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/EnumerableInQuery.cs
Found during analysis of feature request #2145
> Fixed found issue with Union materialization.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/InsertBuilder.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Source/LinqToDB/SqlQuery/SqlParameter.cs
- Tests/Linq/Linq/SelectTests.cs
Not sure yet why, but SelectExpression1 and 2 tests return incorrect results.
> Fix parameters handling regression

- Source/LinqToDB/DataProvider/Firebird/FirebirdSqlOptimizer.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/QueryVisitor.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlStatement.cs
- replaced remaining calls to old Convert visitor
- removed old Convert
- renamed new one to Convert
> Remove old convert visitor

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.AssociatedTableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/Mapping/AssociationDescriptor.cs
- Tests/Base/QueryUtils.cs
- Tests/Linq/UserTests/Issue2161Tests.cs
Also Minor changes in alias generation.
Fixes #2161
> Fix for #2161. Added cache for LoadWith expressions. 

- Data/Create Scripts/Oracle.sql
- Source/LinqToDB/DataProvider/Oracle/OracleSchemaProvider.cs
Fix #2132
No tests, as I didn't found a way to create invalid records for non-package procedures, and we don't support packages right now (tracked by other issue already)
> [Oracle] fix procedure parameters load

- Source/LinqToDB/Linq/Builder/AsSubQueryBuilder.cs
- Source/LinqToDB/LinqExtensions.cs
- Tests/Linq/Linq/OptimizerTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
> Fix for #2105. Added additional AsSubQuery method from flattening IGrouping<,>

- Source/LinqToDB/Data/DataConnectionExtensions.LegacyMerge.cs
- Tests/Linq/Update/OldMergeTests.cs
> Another attempt to obsolete old MERGE API

- README.md
- fix/reorganize badges
- move dnf logo to upper corner
- add links to related projects
- added templates from #2181
> readme.md refactoring

- Build/Azure/README.md
- Build/linq2db.Tests.Providers.props
- NuGet/linq2db.MySqlConnector.nuspec
- NuGet/linq2db.Oracle.Managed.nuspec
- NuGet/linq2db.SQLite.nuspec
- Tests/Base/Tests.Base.csproj
- Tests/Tests.T4/Tests.T4.csproj
Providers:
- [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core) 1.0.112.1 -> 1.0.112.2
- [Oracle.ManagedDataAccess](https://www.nuget.org/packages/Oracle.ManagedDataAccess) 19.6.0 -> 19.7.0
- [MySqlConnector](https://www.nuget.org/packages/MySqlConnector) 0.63.2 -> 0.64.1
Other:
- [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk) 16.5.0 -> 16.6.1
- [Microsoft.AspNet.OData](https://www.nuget.org/packages/Microsoft.AspNet.OData) 7.3.0 -> 7.4.0
- [Humanizer.Core](https://www.nuget.org/packages/Humanizer.Core) 2.7.9 -> 2.8.2
> bump dependencies

- Source/LinqToDB/Expressions/TypeMapper.cs
> Exception-less resolve of optional provider mappings

- Source/LinqToDB/SqlQuery/SqlTable.cs
- Tests/Linq/Update/InsertWithOutputTests.cs
> Remove schema and database name from INSERTED table

- Source/LinqToDB/DataProvider/SQLite/SQLiteDataProvider.cs
- Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs
- Source/LinqToDB/Sql/Sql.FunctionAttribute.cs
- Source/LinqToDB/Sql/Sql.PropertyAttribute.cs
Added XMLDocs to `ExpressionAttribute`, `FunctionAttribute`, and `PropertyAttribute`
Added XMLDocs to `SQLiteDataProvider` Constructors
> Added XMLDocs

- Source/LinqToDB/DataProvider/Oracle/OracleSchemaProvider.cs
- Tests/Linq/DataProvider/OracleTests.cs
- Tests/Tests.T4/Databases/Oracle.generated.cs
> [Oracle] Read column length for character types from proper column 

- Source/LinqToDB/LinqExtensions.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/Update/UpdateTests.cs
> Fixes #2207. Added missing ToString overloads for DML operations.

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
> Fix for Issue #2196

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ParameterContainer.cs
- Source/LinqToDB/Linq/ExpressionQuery.cs
- Source/LinqToDB/Linq/Query.cs
- Tests/Linq/Linq/ParameterTests.cs
> Fix for #2174. Added nested queries parameters support.

- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Expressions/MemberHelper.cs
- Source/LinqToDB/Linq/AccessorMember.cs
- Source/LinqToDB/Linq/Builder/AssociationHelper.cs
- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Source/LinqToDB/Linq/Builder/ParameterContainer.cs
- Source/LinqToDB/Linq/Builder/SetOperationBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/Linq/QueryableMemberAccessor.cs
- Source/LinqToDB/Linq/TableT.cs
- Source/LinqToDB/LinqExtensions.cs
- Source/LinqToDB/Mapping/AssociationDescriptor.cs
- Source/LinqToDB/Reflection/Methods.cs
- Source/LinqToDB/SqlQuery/SelectQuery.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
- Tests/Linq/Linq/QueryableAssociationTests.cs
Based on `issue/2238` branch. can be mess in reviewing.
> Fixed found issues with EagerLoading and QueryFilters.

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/Reflection/Methods.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
Fixes #2249
Also https://github.com/linq2db/linq2db/issues/1764#issuecomment-636974287
Thanks @detoxhby for detailed reproducing steps.
> Eager Loading regression fixes

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/Linq/AssociationTests.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
- Tests/Linq/OrmBattle/Helper/ExpressionUtils.cs
> Improved Eager Loading dependency detection.

- Source/LinqToDB/Sql/Sql.Analytic.cs
- Tests/Linq/Linq/AnalyticTests.cs
> Fixed token name collision. Added LongCount analytic functions.

- Source/LinqToDB/Linq/Builder/AsSubQueryBuilder.cs
- Source/LinqToDB/Linq/Builder/DisableGroupingGuardBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Source/LinqToDB/LinqExtensions.cs
- Source/LinqToDB/Reflection/Methods.cs
- Tests/Linq/Linq/GroupByTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
@detoxhby, please review also. 
Original conversation: https://github.com/linq2db/linq2db/issues/1764#issuecomment-638169815
> Added possibility to Disable Grouping Guard in query.

- Source/LinqToDB/ILoadWithQueryable.cs
- Source/LinqToDB/Linq/Builder/LoadWithBuilder.cs
- Source/LinqToDB/LinqExtensions.LoadWith.cs
- Source/LinqToDB/Reflection/Methods.cs
- Tests/Linq/Linq/LoadWithTests.cs
> Added old style LoadWithAsTable API for simplifying backward compatibility.

- Tests/Linq/Linq/CteTests.cs
> #2029 test

- Source/LinqToDB/Linq/QueryRunner.cs
> Remove unneeded Mapper.QueryRunner field

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/LoadWithBuilder.cs
- Tests/Linq/Linq/AbstractionTests.cs
Added ability to use LoadWith with interfaces which do not expose association attribute.
Fixes #2278
> Fix for #2278. Added ability to use LoadWith with interfaces.

- Source/LinqToDB/IEntityServices.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
> update OnEntityCreated documentation

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/UserTests/Issue2296Tests.cs
> Fix for issue #2296

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
> Fix for #2309. Removed unwanted projection from query.

- Build/Azure/README.md
- Build/linq2db.Tests.Providers.props
- NuGet/linq2db.MySqlConnector.nuspec
- Source/LinqToDB/DataProvider/MySql/MySqlSchemaProvider.cs
- Tests/Linq/DataProvider/MySqlTests.cs
- Tests/Tests.T4/Databases/MariaDB.generated.cs
- Tests/Tests.T4/Databases/MySql.generated.cs
- Tests/Tests.T4/Databases/MySqlConnector.generated.cs
> improve types reveng for mysql

- Source/LinqToDB/Linq/Query.cs
- Tests/Linq/Linq/GroupByTests.cs
> Introduce query flags into query cache

- Build/Azure/README.md
- Build/linq2db.Tests.Providers.props
- Data/Create Scripts/MySql.sql
- NuGet/linq2db.MySqlConnector.nuspec
- Tests/Linq/DataProvider/MySqlTests.cs
new version fixed geomcollection support, so we can enable it in tests
> Update mysqlconnector and reenable disabled test-case

- Source/LinqToDB/Linq/Builder/TakeSkipBuilder.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/TakeSkipTests.cs
> Fix support for multiple Skip/Test calls

- README.md
> replace BulkCopy transaction-related text with link to our documentation

- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/Linq/WhereTests.cs
> redo EXISTS fix

- Source/LinqToDB/ILoadWithQueryable.cs
- Source/LinqToDB/LinqExtensions.LoadWith.cs
- Tests/Base/TestBase.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
> override ToString for ILoadWithQueryable to return base query sql

- Source/LinqToDB/Data/RetryPolicy/RetryingDbCommand.cs
- Source/LinqToDB/DataProvider/DynamicDataProviderBase.cs
- Tests/Linq/Data/MiniProfilerTests.cs
- Tests/Linq/DataProvider/OracleTests.cs
> Fix connection/command unwrapping when RetryPolicy enabled

- Source/LinqToDB/Async/AsyncDbConnection.cs
- Source/LinqToDB/Common/Configuration.cs
- Source/LinqToDB/Data/CommandInfo.cs
- Source/LinqToDB/Data/DataConnectionExtensions.cs
- Source/LinqToDB/DataProvider/Access/AccessODBCSchemaProvider.cs
- Source/LinqToDB/DataProvider/Access/AccessOleDbSchemaProvider.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdSchemaProvider.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSchemaProvider.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaSchemaProvider.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSchemaProvider.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseSchemaProvider.cs
- Source/LinqToDB/SchemaProvider/GetSchemaOptions.cs
- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
- Tests/Linq/Linq/ParameterTests.cs
- Tests/Linq/SchemaProvider/SchemaProviderTests.cs
- Tests/Tests.Playground/TestTemplate.cs
- linq2db.playground.sln
> CommandBehavior.SchemaOnly causes problems while generating SQL Server SP

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Tests/Linq/Linq/LoadWithTests.cs
> Fix for #2351. Added missing transformation exception for LoadWithAsTable

- Source/LinqToDB/Common/Configuration.cs
- Source/LinqToDB/DataProvider/DB2/DB2BulkCopy.cs
- Source/LinqToDB/DataProvider/Informix/InformixBulkCopy.cs
- Source/LinqToDB/DataProvider/MySql/MySqlBulkCopy.cs
- Source/LinqToDB/DataProvider/Oracle/OracleBulkCopy.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaBulkCopy.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerBulkCopy.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseBulkCopy.cs
> Add support for using DataConnection.CommandTimeout on BulkCopy

- Source/LinqToDB/Common/Utils.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/OrderByTests.cs
> Fix for #2378. Corrected OrderBy merging for optimized subqueries.

- Tests/Linq/DataProvider/PostgreSQLTests.cs
See #2395 
This separates the tests failing due to DST from `TestRangeBulkCopy` and `TestRangeBulkCopyAsync` and into a separate test called `TestRangeBulkCopyDST`.  The new test is marked with `[ActiveIssue]`
> Separate broken npgsql tstzrange tests for postgre

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/Linq/WhereTests.cs
> Bad expression parameter optimization

- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/GroupByTests.cs
> Fix for #2405. Improved OrderBy merging.

- Source/LinqToDB/Linq/Builder/MergeBuilder.InsertWhenNotMatched.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.On.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.UpdateWhenMatched.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.UpdateWhenMatchedThenDelete.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.cs
- Source/LinqToDB/LinqExtensions.Merge.cs
- Tests/Linq/Update/MergeTests.Issues.cs
> Fix interfaces support in Merge API

- Data/Create Scripts/PostgreSQL.sql
- Source/LinqToDB/DataProvider/Oracle/OracleMappingSchema.cs
- Source/LinqToDB/DataProvider/Oracle/OracleSchemaProvider.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaSchemaProvider.cs
- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
- Tests/Linq/SchemaProvider/SchemaProviderTests.cs
- server-side schema filtering for oracle
> Additional schema-related fixes

- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Tests/Linq/UserTests/Issue2418Tests.cs
> Fix for #2418. Corrected chain sequence sorting.

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/UserTests/SkipOnEntityFetchTests.cs
> Fix for #2456. More smart projection generation.

- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Tests/Linq/Linq/InheritanceTests.cs
> Improve handling of method overrides with ExpressionMethodAttribute

- Source/LinqToDB/Linq/Builder/SetOperationBuilder.cs
- Tests/Linq/UserTests/Issue2461Tests.cs
Also fixed bad exception generation.
> Added test for #2461.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Expressions.cs
- Tests/Linq/UserTests/Issue2468Tests.cs
> Fix for #2468. Improved members mapping.

- Source/LinqToDB/Data/TransactionScopeHelper.cs
- Source/LinqToDB/Linq/ExpressionQuery.cs
- Tests/Linq/Linq/LoadWithTests.cs
> Fix for #2471. Added TransactionScope check when loading preambles.

- Source/LinqToDB/SqlQuery/SqlDataType.cs
- Tests/Linq/AST/SqlDataTypeTests.cs
> Fix SqlDataType.SystemType property value

- Source/LinqToDB/DataExtensions.cs
> Fix for #2479. Correct Parameter usage

- Source/LinqToDB/Linq/Builder/AggregationBuilder.cs
- Source/LinqToDB/Linq/Builder/AllAnyBuilder.cs
- Source/LinqToDB/Linq/Builder/ArrayBuilder.cs
- Source/LinqToDB/Linq/Builder/AssociationContext.cs
- Source/LinqToDB/Linq/Builder/AssociationHelper.cs
- Source/LinqToDB/Linq/Builder/ContainsBuilder.cs
- Source/LinqToDB/Linq/Builder/CountBuilder.cs
- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/EnumerableContext.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Source/LinqToDB/Linq/Builder/IBuildContext.cs
- Source/LinqToDB/Linq/Builder/JoinBuilder.cs
- Source/LinqToDB/Linq/Builder/MethodChainBuilder.cs
- Source/LinqToDB/Linq/Builder/PassThroughContext.cs
- Source/LinqToDB/Linq/Builder/ScalarSelectBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/Linq/Builder/SelectManyBuilder.cs
- Source/LinqToDB/Linq/Builder/SequenceContextBase.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Reflection/Methods.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Tests/Base/TestBase.cs
- Tests/Linq/UserTests/Issue2478Tests.cs
- Tests/Tests.Playground/Issue2478Tests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
> Fix for #2478. Added explicit aggregation column completion.

- Source/LinqToDB/Linq/Builder/JoinBuilder.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/DataProvider/SQLiteParameterTests.cs
- Tests/Linq/Linq/ComplexTests2.cs
- Tests/Linq/Linq/EnumerableInQuery.cs
- Tests/Linq/Linq/ExpandTests.cs
- Tests/Linq/Linq/ExpressionsTests.cs
- Tests/Linq/Linq/QueryFilterTests.cs
- Tests/Linq/Linq/QueryableAssociationTests.cs
- Tests/Linq/Linq/SetOperatorTests.cs
- Tests/Linq/Mapping/FluentMappingExpressionMethodTests.cs
- Tests/Linq/Samples/JsonConvertTests.cs
- Tests/Linq/TypeMapping/MappingTests.cs
- Tests/Linq/Update/DeleteWithOutputTests.cs
- Tests/Linq/Update/DynamicColumnsTests.cs
- Tests/Linq/Update/InsertWithOutputTests.cs
- Tests/Linq/Update/UpdateFromTests.cs
- Tests/Linq/UserTests/Issue1584Tests.cs
- Tests/Linq/UserTests/Issue1925Tests.cs
- Tests/Linq/UserTests/Issue2470Tests.cs
- Tests/Linq/UserTests/Issue999Tests.cs
- Tests/Tests.Playground/Issue2470Tests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
> Fix for #2470. Reverted introduced regression.

- Data/Create Scripts/SqlServer.sql
- Data/Create Scripts/SqlServer2000.sql
- Source/LinqToDB.Templates/DataModel.ttinclude
- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Source/LinqToDB/DataProvider/SqlServer/SqlServer2000SchemaProvider.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSchemaProvider.cs
- Source/LinqToDB/SchemaProvider/ParameterSchema.cs
- Source/LinqToDB/SchemaProvider/ProcedureInfo.cs
- Source/LinqToDB/SchemaProvider/ProcedureParameterInfo.cs
- Source/LinqToDB/SchemaProvider/ProcedureSchema.cs
- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
- Tests/Linq/DataProvider/SqlServerTests.cs
- Tests/Tests.T4/Databases/SqlServer.2017.ProceduresFromSchema.generated.cs
- Tests/Tests.T4/Databases/SqlServer.2017.generated.cs
- Tests/Tests.T4/Databases/SqlServer.MS.generated.cs
- Tests/Tests.T4/Databases/SqlServer.generated.cs
- Tests/Tests.T4/Databases/SqlServerAzure.generated.cs
> [MSSQL] Implement MS_Description support for procedures, functions and parameters

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Tests/Linq/Linq/LoadWithTests.cs
> Fix for #2532. Added missing ParameterContainer parametrization.

- Source/LinqToDB/DataProvider/Access/AccessSchemaProviderBase.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSchemaProvider.cs
> Remove bogus exception

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/Linq/SelectTests.cs
> Fix for #2530. Corrected projection generation.

- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Tests/Linq/UserTests/Issue2546Tests.cs
> Fix for #2546. Do not convert properties if they should be parameters.

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/DataProvider/FirebirdTests.cs
- Tests/Linq/UserTests/Issue2562Tests.cs
> Fix for #2562. Removed superfluous code for dynamic columns.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/UserTests/Issue2566Tests.cs
> Fix for #2566. Improved custom constant handling.

- Source/LinqToDB/AsyncExtensions.cs
> Fix .ToDictionaryAsync() call

- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
- Tests/Base/TestProvName.cs
- Tests/Linq/Linq/CteTests.cs
- Tests/Linq/Update/MergeTests.cs
Fix #2573
@MaceWindu, I have no possibility to run tests on MySQL 8. I hope you can try that,
If this PR works we can include it in next bugfix release. Nothing special here, but if it works - it is is better than waiting epic issue fix.
> Fix for #2573. Corrected MySQL CTE building for UPDATE.

- Source/LinqToDB/Common/Configuration.cs
- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Tests/Base/TestBase.cs
- Tests/Linq/UserTests/Issue447Tests.cs
> remove UseBinaryAggregateExpression setting

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Tests/Linq/UserTests/Issue2596Tests.cs
> Fix for #2596. Fixed infinite loop in LoadWith query.

- Source/LinqToDB/Sql/Sql.DateTime.cs
- Source/LinqToDB/Sql/Sql.DateTimeOffset.cs
- Tests/Linq/Linq/DateTimeFunctionsTests.cs
> Add DateDiff function for Access

- Source/LinqToDB/Sql/Sql.cs
- Tests/Linq/Linq/StringFunctionTests.cs
> Fix some of the Sql functions + add tests for non-db part

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Tests/Linq/UserTests/Issue2602Tests.cs
> Fix for #2602. Fixed parameter caching regression.

- Tests/Base/CustomizationSupportInterceptor.cs
- Tests/Base/TestBase.Identity.cs
- Tests/Base/TestBase.cs
- Tests/Linq/Create/CreateData.cs
- Tests/Linq/Update/MergeTests.Operations.Parameters.cs
Hope it's not too late, I added a few more intercepetions:
- CreateData
- Identity Reset helpers
- GetParameterToken
Sorry for the formatting changes, it's vs working it's magic...
> Db2 test changes

- Source/LinqToDB/Sql/Sql.Analytic.cs
- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Tests/Linq/Linq/AnalyticTests.cs
> Fix for #2618. Corrected expression ordering.

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Tests/Linq/UserTests/Issue2642Tests.cs
> Fix for #2642. Added missing null reference check.

- Source/LinqToDB.Templates/NotifyDataErrorInfo.ttinclude
- Source/LinqToDB.Templates/NotifyPropertyChanged.ttinclude
- Source/LinqToDB.Templates/Validation.ttinclude
- Tests/Tests.T4/Models/ModelTest.generated.cs
- Tests/Tests.T4/WPF/ViewModel.generated.cs
- remove remnants of silverlight support
- fix conditional properties validation codegen
- fix `IsValid` logic to use AND instead of OR
> [T4] Various fixes

- Build/Azure/README.md
- Build/linq2db.Providers.props
- Build/linq2db.Tests.Providers.props
- NuGet/linq2db.MySqlConnector.nuspec
- Tests/Base/Tests.Base.csproj
- [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk): 16.8.0 -> 16.8.3
- [MySqlConnector](https://www.nuget.org/packages/MySqlConnector): 1.1.0 -> 1.2.0
> Bump dependecies

- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/UserTests/Issue2665Tests.cs
> Fix for #2665. Added missing columns for group by queries.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Source/LinqToDB/Linq/Builder/GroupByElementBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.cs
- Tests/Linq/UserTests/Issue2662Tests.cs
> Fix for #2662. Added logic for generating correct sequence for grouping element.

- Source/LinqToDB/Linq/Builder/AggregationBuilder.cs
- Source/LinqToDB/Linq/Builder/DefaultIfEmptyBuilder.cs
- Tests/Linq/UserTests/Issue2588Tests.cs
> Fix for #2588. Removed unnecessary null result check.

- Build/Azure/pipelines/templates/test-jobs.yml
- Source/LinqToDB/DataProvider/Access/AccessSqlOptimizer.cs
- Source/LinqToDB/DataProvider/DB2/DB2SqlOptimizer.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSqlOptimizer.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlOptimizer.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteSqlOptimizer.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/Linq/WhereTests.cs
Fail:
- SQL Server
- Firebird
- Informix
- Oracle
- SAP HANA
- SQL CE
- Sybase
Pass:
- SQLite
- Access
- DB2
- MySQL/MariaDB
- PostgreSQL
> Invalid SQL generated for multiple comparion conditions

- Data/Create Scripts/Oracle.sql
- Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Tests/Linq/Linq/AK107Tests.cs
> SequenceNameAttribute.Schema support for Oracle

- Source/LinqToDB/Data/DataConnection.cs
- Tests/Linq/Data/RetryPolicyTest.cs
- Tests/Linq/UserTests/Issue421.cs
- Tests/Model/TestDataConnection.cs
> Apply retry policy to all DataConnection constructors and to external connection

- NuGet/PostgreSQL/LinqToDB.PostgreSQL.Tools.ttinclude
- NuGet/linq2db.PostgreSQL.nuspec
- NuGet/linq2db.t4models.nuspec
> Fix extra assemblies load for postgresql T4 templates

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/DataProvider/OracleTests.cs
Fix #2725
Extracted regression fix from #2718 to unblock bugfix release
> Fix for #2725 (No coercion operator is defined...)

- Tests/Linq/Data/DataConnectionTests.cs
> TransactionScope tests

- CONTRIBUTING.md
Small change to Contributing.md
> Fix parameter spelling in contribution file

- Source/LinqToDB/Data/DataConnection.QueryRunner.cs
- Source/LinqToDB/Linq/IQueryContext.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Source/LinqToDB/ServiceModel/LinqService.cs
- Source/LinqToDB/ServiceModel/LinqServiceQuery.cs
- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/ServiceModel/RemoteDataContextBase.QueryRunner.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlProvider/OptimizationContext.cs
- Source/LinqToDB/SqlProvider/SqlOptimizerExtensions.cs
- Source/LinqToDB/SqlQuery/AliasesContext.cs
- Source/LinqToDB/SqlQuery/IReadOnlyParameterValues.cs
- Source/LinqToDB/SqlQuery/SqlParameter.cs
- Source/LinqToDB/SqlQuery/SqlParameterValues.cs
- Source/LinqToDB/SqlQuery/SqlStatement.cs
- Tests/Linq/Linq/QueryInheritanceTests.cs
- Tests/Model/TestDataConnection.cs
> Fix for #2379. Fixed parameters mutation.

- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/SqlQuery/SqlStatement.cs
- Tests/Linq/Linq/VisualBasicTests.cs
- Tests/Linq/Linq/WhereTests.cs
- Tests/VisualBasic/Tests.vb
> Fix for #2746. Suppressed removing method based conversions.

- Source/LinqToDB/DataProvider/SqlServer/SqlServerSchemaProvider.cs
Additional fix missing from #2758
> Fix column casing for sql server schema queries

- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
> Fix for #2776. Added additional check for possible transformation.

- Tests/Linq/Linq/PaginationExtensions.cs
- Tests/Linq/Linq/PaginationTests.cs
Set of useful extensions for pagination. Candidates for `linq2db.Tools` after polishing.
> Added pagination extensions sample.

- Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs
- Source/LinqToDB/Linq/Builder/AggregationBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/Sql/Sql.Analytic.cs
- Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs
- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/ConvertVisitor.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlExpression.cs
- Source/LinqToDB/SqlQuery/SqlFlags.cs
- Tests/Linq/UserTests/Issue2797Tests.cs
> Fix for #2797. Added missed IsPredicate and IsWindowFunction for SqlExpression.

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/FSharp/InsertTest.fs
- Tests/FSharp/Issue2678.fs
- Tests/FSharp/Tests.FSharp.fsproj
- Tests/Linq/Linq/FSharpTests.cs
> Fix incorrect F# record type detection

- Build/Azure/scripts/mac.docker.sh
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Tests/Base/CustomizationSupportInterceptor.cs
- Tests/Base/TestBase.Identity.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
> Add GetReserveSequenceValuesSql implementation for postgres

- Source/LinqToDB/DataProvider/DB2/DB2LUWSchemaProvider.cs
- Source/LinqToDB/DataProvider/DB2/DB2zOSSchemaProvider.cs
- Tests/Linq/DataProvider/DB2Tests.cs
> [DB2] Trim table id components for column schema load

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/QueryHelper.Evaluate.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlSearchCondition.cs
- Tests/Base/TestBase.cs
- Tests/Linq/Linq/AssociationTests.cs
- Tests/Linq/UserTests/Issue2800Tests.cs
- Tests/Tests.Playground/Issue2800Tests.cs
>  Fix for #2800. Added additional check for null comparison.

- Source/LinqToDB/Expressions/MemberHelper.cs
- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Source/LinqToDB/Linq/Expressions.cs
- Source/LinqToDB/Sql/Sql.cs
- Tests/Linq/UserTests/Issue2691Tests.cs
> Array.Length mapping support, byte[].Length translation to SQL

- Source/LinqToDB/Common/Configuration.cs
and add missing default value details for some other flags
> fix incorrect GuardGrouping default value comment

- Source/LinqToDB/Sql/Sql.Collate.cs
- Tests/Base/TestUtils.cs
- Tests/Linq/Linq/SqlExtensionsTests.cs
> Add Sql.Collate extension/method to apply collation to string.

- Build/linq2db.Tests.props
- Directory.Packages.props
- Tests/FSharp/Tests.FSharp.fsproj
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue2560Tests.cs
Sample NodaTime conversion for #2560.
> Issue #2560 tests. Added NodaTime.LocalDateTime mapping test.

- Source/LinqToDB/SqlQuery/SqlColumn.cs
- Tests/Linq/UserTests/Issue2856Tests.cs
>  Fix for #2856. Added unwrapping for column equality.

- Build/Azure/pipelines/templates/test-jobs.yml
- Source/LinqToDB/DataProvider/Oracle/Oracle12SqlBuilder.cs
- Tests/Linq/UserTests/Issue2785Tests.cs
> Generate aliases for TOP-level selects with limits for Oracle 12+

- Source/LinqToDB/DataContext.cs
> Virtualize DataContext.Dispose

- Data/Create Scripts/PostgreSQL.sql
- Source/LinqToDB.Templates/DataModel.ttinclude
- Tests/Tests.T4/Databases/PostgreSQL.11.generated.cs
- Tests/Tests.T4/Databases/PostgreSQL.generated.cs
> [t4] add source table name to foreign key identifier

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLExtensions.cs
- Source/LinqToDB/Linq/Expressions.cs
- Tests/Linq/DataProvider/PostgreSQLExtensionsTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
> Added ANY functions for arrays.

- Directory.Packages.props
- NuGet/linq2db.nuspec
Fix #2868
Upstream issue : https://github.com/Azure/azure-functions-host/issues/6893
> Downgrade System.ComponentModel.Annotations for netcoreapp 3.1 TFM

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLExtensions.cs
- Tests/Linq/DataProvider/PostgreSQLExtensionsTests.cs
Proposed rename of methods, introduced by #2871
> [PostgreSQL] ANY methods rename

- Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlOptimizer.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/SelectQuery.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlSetOperator.cs
- Tests/Linq/Linq/OrderByTests.cs
> Fix support for union of sorted queries

- Source/LinqToDB/Sql/Sql.FunctionAttribute.cs
- Source/LinqToDB/Sql/Sql.cs
- Tests/Linq/Linq/FunctionTests.cs
> Fix for #2886. Added IsPure = false for NewGuid function and correcetd function creation.

- Source/LinqToDB/Common/Utils.cs
- Source/LinqToDB/Linq/Builder/InsertBuilder.cs
- Source/LinqToDB/Linq/Builder/UpdateBuilder.cs
- Source/LinqToDB/SqlQuery/SqlInsertClause.cs
- Tests/Linq/Update/InsertIntoTests.cs
- Tests/Linq/Update/UpdateTests.cs
> Fix for #2700. Improved Insert query generation.

- Build/Azure/README.md
- Directory.Packages.props
- NuGet/linq2db.AspNet.nuspec
- NuGet/linq2db.MySqlConnector.nuspec
- NuGet/linq2db.Oracle.Managed.nuspec
- NuGet/linq2db.SQLite.MS.nuspec
- Source/LinqToDB/Async/SafeAwaiter.cs
- Source/LinqToDB/Common/EnumerableHelper.cs
- Source/LinqToDB/DataProvider/BasicBulkCopy.cs
- Source/LinqToDB/DataProvider/BulkCopyReader.cs
- Source/LinqToDB/DataProvider/MySql/MySqlBulkCopy.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLBulkCopy.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaBulkCopy.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerBulkCopy.cs
- Source/LinqToDB/Properties/AssemblyInfo.cs
- Tests/Base/Properties/AssemblyInfo.cs
- Tests/Base/Tools/SettingsReader.cs
- Tests/FSharp/Tests.FSharp.fsproj
- Tests/Linq/Update/CreateTableTypesTests.cs
- Tests/Linq/UserTests/Issue2000Tests.cs
- Tests/Linq/UserTests/Issue2418Tests.cs
- Update dependencies:
- ~[Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk): 16.8.3 -> 16.9.1~ borken, waiting for 16.9.2
- [NUnit3TestAdapter](https://www.nuget.org/packages/NUnit3TestAdapter): 3.17.0 -> 4.0.0-beta.1
- [FastExpressionCompiler](https://www.nuget.org/packages/FastExpressionCompiler): 3.0.0-preview-07 -> 3.0.0
- [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection): 3.1.12 -> 3.1.13
- [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions): 3.1.12 -> 3.1.13
- [Microsoft.Data.Sqlite](https://www.nuget.org/packages/Microsoft.Data.Sqlite): 5.0.3 -> 5.0.4
- [MySqlConnector](https://www.nuget.org/packages/MySqlConnector): 1.3.0 …
> Dependecies update

- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlExpression.cs
- Source/LinqToDB/SqlQuery/SqlFunction.cs
- Tests/Linq/UserTests/Issue2961Tests.cs
> Fix for #2961. Count function should contain information about grouping set.

- Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs
- Source/LinqToDB/Sql/Sql.FunctionAttribute.cs
- Source/LinqToDB/Sql/Sql.TableExpressionAttribute.cs
- Source/LinqToDB/Sql/Sql.TableFunctionAttribute.cs
- Tests/Linq/Linq/ExpressionTests.cs
> Fix for #2963. Corrected arguments collecting.

- Build/Azure/README.md
- Directory.Packages.props
- NuGet/linq2db.MySqlConnector.nuspec
[MySqlConnector](https://www.nuget.org/packages/MySqlConnector) 1.3.4 -> 1.3.5
> MySqlConnector update

- Source/LinqToDB/Mapping/AssociationDescriptor.cs
- Tests/Linq/Linq/AssociationTests.cs
> Fix for #2981

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/UserTests/Issue2994Tests.cs
> Fix for issue #2994

- Data/Create Scripts/SqlServer.sql
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/UserTests/Issue3001Tests.cs
- Tests/Tests.Playground/TestTemplate.cs
> Fix for #3001. Skipping Alias method when handling associations.

- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Tests/Linq/DataProvider/PostgreSQLExtensionsTests.cs
> Fix generic array parameters in extensions

- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Tests/Linq/UserTests/Issue3014Tests.cs
> Fix for #3014. Simplified expression generation.

- Source/LinqToDB/Common/Converter.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/Linq/StringFunctionTests.cs
> Fix IConvertible values support in string search predicates optimization

- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/EvaluationContext.cs
- Source/LinqToDB/SqlQuery/SqlObjectExpression.cs
- Tests/Linq/Linq/SetTests.cs
> Fix IN expression optimization crash

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLMappingSchema.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
> Fix unsigned integers support for pgsql

- Source/LinqToDB/Sql/Sql.cs
- Tests/Linq/Linq/ConvertTests.cs
Fix #2936
Support:
- SQL Server 2012+
- Oracle 12.2+
gonna check if other providers have something similar
> Add Sql.TryConvert extension

- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Tests/Linq/UserTests/Issue2939Tests.cs
> Issue 2939

- Source/LinqToDB/SqlProvider/JoinOptimizer.cs
Address second concern from #2943
> Investigate potentially unused code

- Source/LinqToDB/Data/DataConnectionExtensions.cs
- Source/LinqToDB/DataProvider/DB2/DB2BulkCopy.cs
- Source/LinqToDB/DataProvider/Informix/InformixBulkCopy.cs
- Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
- Source/LinqToDB/DataProvider/MySql/MySqlBulkCopy.cs
- Source/LinqToDB/DataProvider/Oracle/OracleBulkCopy.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLBulkCopy.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaBulkCopy.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerBulkCopy.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseBulkCopy.cs
- Source/LinqToDB/TableExtensions.cs
- Tests/Linq/Update/BulkCopyTests.cs
> Support BulkCopy with DataContext

- Source/LinqToDB/Linq/Builder/OrderByBuilder.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
Extracted from #3022 to include into next release
> OrderBy + Distinct fixes

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLMappingSchema.cs
- Source/LinqToDB/Mapping/MappingSchema.cs
Fixes https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/153
> Fixed incorrect unsigned mapping for PostgreSQL. Improved converters matching.

- Source/LinqToDB/SqlQuery/SqlColumn.cs
- Source/LinqToDB/SqlQuery/SqlSelectClause.cs
- Tests/Linq/UserTests/Issue3061Tests.cs
> Fix for #3061. Improved equal column detection.

- CONTRIBUTING.md
Points to a valid pipeline .yml file in CONTRIBUTING.md
> Fix link to pipelines .yml file in CONTRIBUTING.md

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/UserTests/Issue3049Tests.cs
> Fix for #3049. Removed unwanted conversion.

- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Tests/Linq/UserTests/Issue3043Tests.cs
> Fix for #3043. Removed bad exposing caching.

- Source/LinqToDB/Common/TypeHelper.cs
- Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectBuilder.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
> Fix for #3038. Fixed First/Single Convert issues.

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/Compat/IsExternalInit.cs
- Tests/Linq/Linq/MappingTests.cs
- Tests/Linq/UserTests/Issue1084Tests.cs
- Tests/Linq/UserTests/Issue3049Tests.cs
- Tests/Linq/UserTests/Issue3056Tests.cs
- Tests/Linq/UserTests/Issue3061Tests.cs
- Tests/Model/TestDataConnection.cs
- Tests/Tests.Playground/Linq/Compat/IsExternalInit.cs
> Record-like classes support

- Build/Azure/pipelines/templates/test-matrix.yml
- Build/Azure/scripts/mac.mysql.sh
- Build/Azure/scripts/mysql.sh
- Source/LinqToDB/DataProvider/MySql/MySqlDataProvider.cs
> ONLY_FULL_GROUP_BY support for MySQL

- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Tests/Linq/UserTests/Issue3089Tests.cs
> Fix for #3089. Added NULL values type correction.

- Build/BannedSymbols.txt
- Build/linq2db.Default.props
- Directory.Packages.props
- Source/LinqToDB/Data/RetryPolicy/RetryPolicyBase.cs
- linq2db.sln
> add banned symbols support, ban threadstatic attribute

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/Linq/ConstructorTests.cs
> Fix for #3111. Added handling non-public default constructors.

- .editorconfig
- Source/LinqToDB/DataProvider/Access/AccessOleDbSchemaProvider.cs
- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
- Tests/Linq/Data/DataConnectionTests.cs
- Tests/Linq/Data/TransactionTests.cs
- Tests/Linq/Linq/FunctionTests.cs
- Tests/Linq/UserTests/Issue1925Tests.cs
- Tests/Tests.T4/Databases/Access.generated.cs
- Tests/Tests.T4/Databases/AccessODBC.generated.cs
Fix #3149
Also fixed new analyzer errors appeared after net 6 sdk install
> Disable identity columns detection for Access OleDb provider

- Source/LinqToDB/EntityCreatedEventArgs.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/Linq/EntityCreatedTests.cs
This information is needed for EF Core integration.
> Added missed information about table for EntityService.

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlOptimizer.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/UserTests/Issue3186Tests.cs
> Fix for #3186. Improved PostgreSQL Update FROM queries generation.

- Source/LinqToDB/DataProvider/SqlCe/SqlCeSqlOptimizer.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlExpression.cs
- Tests/Linq/Linq/WhereTests.cs
> Fix for #3182. Added handling SelectQuery boolean predicate.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Source/LinqToDB/Linq/CompiledTableT.cs
- Source/LinqToDB/Linq/Query.cs
- Tests/Linq/Linq/SelectTests.cs
> Added preprocessing for conditional expressions.

- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/SqlProvider/JoinOptimizer.cs
- Tests/Linq/Linq/FullTextTests.SqlServer.cs
> Fix for #3198. Added additional cache key. 

- Source/LinqToDB/Common/MemberInfoEqualityComparer.cs
- Source/LinqToDB/Linq/Builder/AssociationHelper.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/UserTests/Issue3230Tests.cs
> Fix for #3230. Changed way how we compare MemberInfo.

- Build/Azure/README.md
- Build/Azure/pipelines/default.yml
- Directory.Packages.props
- NuGet/linq2db.AspNet.nuspec
- NuGet/linq2db.Firebird.nuspec
- NuGet/linq2db.MySqlConnector.nuspec
- NuGet/linq2db.PostgreSQL.nuspec
- NuGet/linq2db.SQLite.MS.nuspec
- NuGet/linq2db.SqlServer.MS.nuspec
- Source/LinqToDB/DataProvider/Firebird/FirebirdSchemaProvider.cs
- Source/LinqToDB/DataProvider/PostgreSQL/NpgsqlProviderAdapter.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
- Tests/FSharp/Tests.FSharp.fsproj
- [FirebirdSql.Data.FirebirdClient](https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient): 8.5.2 -> 8.5.3
- [FSharp.Core](https://www.nuget.org/packages/FSharp.Core): 5.0.2 -> 6.0.0
- [Microsoft.AspNet.OData](https://www.nuget.org/packages/Microsoft.AspNet.OData): 7.5.8 -> 7.5.11
- [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient): 3.0.0 -> 3.0.1
- [Microsoft.Data.Sqlite](https://www.nuget.org/packages/Microsoft.Data.Sqlite): 5.0.9 -> 5.0.10
- [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection): 3.1.18 -> 3.1.19
- [MySqlConnector](https://www.nuget.org/packages/MySqlConnector): 1.3.11 -> 1.3.12
- [NodaTime](https://www.nuget.org/packages/NodaTime): 3.0.5 -> 3.0.7
- …
> Dependencies update

- Source/LinqToDB/DataProvider/DataProviderBase.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaDataProvider.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaOdbcDataProvider.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerDataProvider.cs
- Source/LinqToDB/Linq/Builder/AggregationBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionContext.cs
- Source/LinqToDB/Linq/Builder/MethodChainBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/Linq/Builder/SelectManyBuilder.cs
- Source/LinqToDB/Linq/Builder/SequenceHelper.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/StringFunctionsTests.cs
- Tests/Linq/UserTests/Issue3259Tests.cs
> Fix for #3259. Improved aggregates handling.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Tests/Linq/UserTests/Issue3257Tests.cs
> Issue 3257

- Source/LinqToDB/DataType.cs
- Source/LinqToDB/Linq/Builder/EnumerableContext.cs
- Source/LinqToDB/Linq/Builder/ParametersContext.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Source/LinqToDB/Reflection/Methods.cs
- Tests/Linq/UserTests/Issue3304Tests.cs
> Fix custom column mapping expression generation

- Tests/Base/CustomizationSupportInterceptor.cs
- Tests/Base/TestBase.cs
Added test customization interception support for IsCaseSensitiveDB, IsCaseSensitiveComparison, IsCollatedTableConfigured for third party providers.
> Added methods to test customization interception

- Source/LinqToDB/Common/Internal/TypeExtensions.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteSqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs
- Source/LinqToDB/Expressions/TransformInfo.cs
- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionTestGenerator.cs
- Source/LinqToDB/Linq/Builder/LoadWithBuilder.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlQuery/SqlPredicate.cs
- Source/LinqToDB/SqlQuery/SqlUpdateStatement.cs
> Fix issues, reported by PVS Studio

- Tests/Linq/UserTests/Issue2895Tests.cs
- Tests/Linq/UserTests/Issue3160Tests.cs
- Tests/Linq/UserTests/Issue3161Tests.cs
See:
- #2895 
- #3160 
- #3161
> Add passing and skipped failing tests for issues 2895, 3160, 3161

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/UserTests/Issue3402Tests.cs
> Fix for #3402. Corrected Boolean column expression generation.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Tests/Linq/Linq/ExpressionsTests.cs
> Fix regression, introduced by 3.5.2

- NuGet/README.AspNet.md
- NuGet/README.T4.md
- NuGet/README.Tools.md
- NuGet/README.linq2db.md
- NuGet/linq2db.Access.nuspec
- NuGet/linq2db.AspNet.nuspec
- NuGet/linq2db.DB2.Core.nuspec
- NuGet/linq2db.DB2.nuspec
- NuGet/linq2db.Firebird.nuspec
- NuGet/linq2db.Informix.Core.nuspec
- NuGet/linq2db.Informix.nuspec
- NuGet/linq2db.MySql.nuspec
- NuGet/linq2db.MySqlConnector.nuspec
- NuGet/linq2db.Oracle.Managed.nuspec
- NuGet/linq2db.Oracle.Unmanaged.nuspec
- NuGet/linq2db.PostgreSQL.nuspec
- NuGet/linq2db.SQLite.MS.nuspec
- NuGet/linq2db.SQLite.nuspec
- NuGet/linq2db.SapHana.nuspec
- NuGet/linq2db.SqlCe.nuspec
- NuGet/linq2db.SqlServer.MS.nuspec
- NuGet/linq2db.SqlServer.nuspec
- NuGet/linq2db.Sybase.DataAction.nuspec
- NuGet/linq2db.Sybase.nuspec
- NuGet/linq2db.Tools.nuspec
- NuGet/linq2db.nuspec
- NuGet/linq2db.t4models.nuspec
- linq2db.sln
> Add readme to nugets

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs
- Source/LinqToDB/Linq/Builder/LoadWithBuilder.cs
- Tests/Linq/UserTests/Issue2895Tests.cs
- Tests/Linq/UserTests/Issue3161Tests.cs
Fix #2895
Fix #3161
- restored old fix and adjusted detection logic
- also fixed (?) lambda convert code
> Fix eager load detection (#2895)

- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/Data/DataConnection.cs
- Tests/Linq/Data/TraceTests.cs
- add isolation level to logs
- add async suffix for async transaction operations
> Improve transactions logging

- Source/LinqToDB/DataProvider/BasicBulkCopy.cs
- Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
- Source/LinqToDB/DataProvider/PostgreSQL/NpgsqlProviderAdapter.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLBulkCopy.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Source/LinqToDB/DataType.cs
- Source/LinqToDB/Extensions/MappingExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Mapping/ColumnDescriptor.cs
- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/ServiceModel/SerializationConverter.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/ValueToSqlConverter.cs
- Tests/Base/TestBase.cs
- Tests/Linq/UserTests/Issue3453Tests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
> Fix for #3453. Added support for Enum types in PostgreSQL.

- Source/LinqToDB/Data/DataConnection.Linq.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Reflection/Methods.cs
- Tests/Linq/Linq/ExpressionsTests.cs
> Fix support for DataConnection.GetTable in expressions

- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlSelectClause.cs
- Tests/Linq/UserTests/Issue3061Tests.cs
> is_empty column handling fix

- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Extensions/MappingExtensions.cs
- Source/LinqToDB/Linq/Builder/AggregationBuilder.cs
- Source/LinqToDB/Linq/Builder/AssociationHelper.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.cs
- Tests/Linq/Linq/QueryableAssociationTests.cs
> prevent `ServerSideOnly` members optimization by `OptimizeExpression`

- Source/LinqToDB/Sql/Sql.cs
- Tests/Linq/Linq/NullIfTests.cs
Supported by:
* [Sql Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/nullif-transact-sql?view=sql-server-ver15)
* [Oracle](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions102.htm)
* [Firebird](https://firebirdsql.org/refdocs/langrefupd21-intfunc-nullif.html)
* [DB2](https://www.ibm.com/docs/en/db2/11.5?topic=functions-nullif)
* [Informix](https://www.ibm.com/docs/en/informix-servers/14.10?topic=functions-nvl-function)
* [PostgreSQL](https://www.postgresql.org/docs/current/functions-conditional.html)
* [MySQL](https://www.w3schools.com/SQL/func_mysql_nullif.asp)
* [Sybase](https://infocenter-archive.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1270/html/iqref/Nullif_wsqlfunc.htm)
* …
> Add NullIf() function

- Source/LinqToDB.CLI/Template.tt
Fixes https://github.com/linq2db/linq2db/issues/3564
> Issue-3564: Fixed nullables and namespaces in the Template.tt

- NuGet/linq2db.AspNet.nuspec
- Source/LinqToDB.Tools/LinqToDB.Tools.csproj
> Fix linq2db.aspnet nuspec

- Source/LinqToDB/DataProvider/SQLite/SQLiteDataProvider.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteMappingSchema.cs
- Tests/Linq/Extensions/SQLiteTests.cs
Fix https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/141
Fix https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/200
Fix #1878
> Fix SQLite Guid mapping.

- Source/LinqToDB/DataContext.cs
> Fix DataContext ctor bug

- Data/Create Scripts/MySql.sql
- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
- Tests/Linq/DataProvider/MySqlTests.cs
- Tests/Linq/Linq/CteTests.cs
- Tests/Linq/Linq/SubQueryTests.cs
- Tests/Linq/Update/UpdateTests.cs
Fix #3611
Probably limit was introduced long time ago when varchar was limited to 255
> lift mysql varchar length limit from 255 to 65535

- Source/LinqToDB.CLI/CommandLine/Options/ObjectNameFilterCliOption.cs
> fix object name filter CLI option validation

- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Configuration.cs
- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Options.cs
- Source/LinqToDB.CLI/CommandLine/Options/NamingCliOption.cs
- Source/LinqToDB.Tools/Naming/NormalizationOptions.cs
> [CLI] Merge naming options with defaults

- Source/LinqToDB.AspNet/ServiceConfigurationExtensions.cs
- Tests/Linq/Data/DataConnectionTests.cs
> Add support for context constructors that receive options plus other DI services

- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Tests/Linq/Linq/ValueConversionTests.cs
Fixes conditional part of https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/226
> Added ColumnDescriptor retrieval for Conditional operator.

- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Tests/Base/QueryUtils.cs
- Tests/Linq/UserTests/Issue3636Tests.cs
> Fix for 3636. Fix caching parameters issue in GroupBy lazy loading code.

- Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Update/DeleteWithOutputTests.cs
- Tests/Linq/Update/InsertWithOutputTests.cs
- Tests/Linq/Update/MergeTests.WithOutput.cs
- Tests/Linq/Update/UpdateWithOutputTests.cs
> Fix output table options

- Source/LinqToDB/DataProvider/SqlServer/SqlServerMappingSchema.cs
- Source/LinqToDB/DataProvider/SqlServer/SystemDataSqlServerAttributeReader.cs
> Fix sql server custom types metadata provider

- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Tests/Linq/UserTests/Issue3649Tests.cs
> Fix for #3649. Rewritten PostgreSQL UPDATE FROM query generation.

- Source/LinqToDB/DataProvider/Access/AccessSqlBuilderBase.cs
- Source/LinqToDB/DataProvider/DB2/DB2SqlBuilderBase.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Source/LinqToDB/DataProvider/Informix/InformixSqlBuilder.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
- Source/LinqToDB/DataProvider/Oracle/OracleSqlBuilderBase.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteSqlBuilder.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaOdbcSqlBuilder.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaSqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeSqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServer2005SqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
Another refactoring from #3627
Currently not used (needed for ClickHouse)
> Add nullability information to BuildDataType methods

- Source/LinqToDB/Expressions/ConvertFromDataReaderExpression.cs
- Tests/Base/TestBase.cs
- Tests/Linq/Linq/ValueConversionTests.cs
> Fix mapping using `IValueConverter` with `HandlesNulls = true`

- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Tests/Linq/Linq/GroupByTests.cs
> Revert changes from #3639

- Source/LinqToDB.Tools/Scaffold/DataModel/DataModelLoader.cs
- Source/LinqToDB.Tools/Schema/LegacySchemaProvider.cs
- Source/LinqToDB/DataProvider/Access/AccessODBCSchemaProvider.cs
Fix #3709
Add explicit DECIMAL type mapping, ensure we will not have such faults in future
> Add explicit Access ODBC decimal type mapping

- Source/LinqToDB/Common/Internal/TypeExtensions.cs
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
> Prevent closures optimization

- Source/LinqToDB/Linq/Builder/UpdateBuilder.cs
- Tests/Linq/Update/DeleteWithOutputTests.cs
- Tests/Linq/Update/InsertWithOutputTests.cs
- Tests/Linq/Update/UpdateWithOutputTests.cs
> Fix UPDATE OUTPUT SQL generation

- Source/LinqToDB/SqlQuery/ISqlPredicate.cs
- Source/LinqToDB/SqlQuery/SqlCondition.cs
- Source/LinqToDB/SqlQuery/SqlPredicate.cs
- Source/LinqToDB/SqlQuery/SqlSearchCondition.cs
- Tests/Linq/Linq/ConcatUnionTests.cs
> Implement predicates equality

- Source/LinqToDB/Linq/Builder/MergeBuilder.Merge.cs
- Tests/Linq/Update/MergeTests.Issues.cs
> Fix merge into table with filter

- Build/Azure/net60/clickhouse.json
- Build/Azure/netcoreapp31/clickhouse.json
- Build/Azure/pipelines/templates/test-matrix.yml
- Build/Azure/scripts/hana2.sh
- Build/Azure/scripts/mariadb.sh
- Data/Setup Scripts/mariadb.cmd
- Data/Setup Scripts/readme.md
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Tests/Base/TestBase.cs
- Tests/Linq/Create/CreateData.cs
- Tests/Linq/Data/MiniProfilerTests.cs
- Tests/Linq/DataProvider/Types/ClickHouseTypeTests.cs
- Tests/Linq/DataProvider/Types/TypeTestsBase.cs
- Tests/Linq/Linq/DataTypesTests.cs
- Tests/Linq/Linq/EnumerableSourceTests.cs
- Tests/Linq/Update/BatchTests.cs
- Tests/Linq/Update/BulkCopyTests.cs
- Tests/Linq/Update/DeleteTests.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/UserTests/Issue1107Tests.cs
- Tests/Linq/UserTests/Issue2433Tests.cs
- Tests/Linq/UserTests/Issue3056Tests.cs
- Tests/Linq/UserTests/Issue3636Tests.cs
- Tests/Linq/UserTests/Issue464Tests.cs
- Tests/UserDataProviders.json.template
- linq2db.sln
Fix #3636
Updated test to test issue properly and re-introduced reverted recently fix
> Group by eager load parameters fix

- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Configuration.cs
- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Options.cs
- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.cs
- Source/LinqToDB.CLI/CommandLine/Options/ImportCliOption.cs
- Source/LinqToDB.Tools/Scaffold/Options/ScaffoldOptions.cs
- Source/LinqToDB.Tools/Scaffold/Options/SchemaOptions.cs
- Source/LinqToDB.Tools/Schema/LegacySchemaProvider.cs
> Add by-name filtering options for stored procedures, scalar and aggregate functions

- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Configuration.cs
- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Options.cs
- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.cs
- Source/LinqToDB.Tools/Scaffold/Options/ScaffoldOptions.cs
- Source/LinqToDB.Tools/Scaffold/Options/SchemaOptions.cs
- Source/LinqToDB.Tools/Schema/LegacySchemaProvider.cs
> [Scaffold] Add default schemas option

- Tests/Linq/DataProvider/OracleTests.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
> add tests for Oracle boolean workarounds

- Tests/Base/CustomizationSupport/CustomizationSupport.cs
- Tests/Linq/TestsInitialization.cs
Just another custom provider test helper, it's a hook on test setup.
> Added custom test initialization logic.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs
- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
- Tests/Linq/UserTests/Issue3161Tests.cs
- Tests/Linq/UserTests/Issue3462Tests.cs
> Fix for #3462. Added another prediction for FirstSingleContext.

- Source/LinqToDB/Compatibility/System/Data/Linq/Binary.cs
> Binary class equality operators fix

- Source/LinqToDB/Interceptors/InterceptorExtensions.cs
Old approach throws cast exception, discovered when tried to add unsupported interceptor type to remote context.
> Add better exception for unsupported interceptor type

- Source/LinqToDB/DataProvider/Sybase/SybaseDataProvider.cs
- Tests/Linq/DataProvider/SybaseTests.cs
> Sybase parameter length issue

- Source/LinqToDB/Common/Internal/IdentifierBuilder.cs
- Source/LinqToDB/Compatibility/System/Data/Linq/Binary.cs
> Address pooling CR

- Source/LinqToDB/LinqExtensions.LoadWith.cs
- Tests/Linq/Linq/LoadWithTests.cs
> Fix NRT annotations on eager load APIs

- Source/LinqToDB/Common/OptionsContainer.cs
- Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
- Source/LinqToDB/DataProvider/MySql/MySqlHints.generated.cs
- Source/LinqToDB/DataProvider/MySql/MySqlHints.tt
- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
- Source/LinqToDB/DataProvider/MySql/MySqlTools.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLHints.cs
- Source/LinqToDB/ProviderName.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.Merge.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Base/Remote/ServerContainer/GrpcServerContainer.cs
- Tests/Base/Remote/ServerContainer/TestLinqService.cs
- Tests/Base/Remote/ServerContainer/WcfServerContainer.cs
- Tests/Base/Remote/TestGrpcLinqService.cs
- Tests/Base/TestBase.cs
- Tests/Base/TestProvName.cs
- Tests/Linq/Extensions/MySqlTests.cs
- Tests/Linq/Extensions/MySqlTests.generated.cs
- Tests/Linq/Extensions/MySqlTests.tt
- Tests/Linq/Extensions/PostgreSQLTests.generated.cs
- linq2db.sln.DotSettings
> MySql lock hints

- Source/LinqToDB/Compatibility/System/Data/Linq/Binary.cs
> Improve System.Data.Linq.Binary ctor performance

- Build/Azure/README.md
- Directory.Packages.props
- NuGet/linq2db.AspNet.nuspec
- NuGet/linq2db.MySql.nuspec
- Tests/Linq/Common/ConnectionBuilderTests.cs
- Tests/Linq/UserTests/Issue3840Tests.cs
> Downgrade abstractions packages

- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Tests/Linq/UserTests/Issue3959Tests.cs
> preserve member ordering for derived types

- Source/LinqToDB/Metadata/IMetadataReader.cs
https://github.com/linq2db/linq2db/discussions/3978#discussioncomment-5011481
> Add comment for IMetadataReader's GetObjectID method

- Source/LinqToDB/LinqExtensions.Insert.cs
> Fix copy-paste errors in InputWithOutput* APIs

- README.md
- Source/LinqToDB.Tools/DataProvider/SqlServer/Schemas/Schemas.generated.cs
- Source/LinqToDB.Tools/DataProvider/SqlServer/Schemas/Schemas.xml
- Source/LinqToDB.Tools/Mapper/Map.cs
- Source/LinqToDB.Tools/Mapper/Mapper.cs
- Source/LinqToDB/Mapping/DynamicColumnInfo.cs
- Source/LinqToDB/Mapping/QueryFilterAttribute.cs
Fixes xmldoc/md issues, discovered by docfx.
5 warnings remain, caused by https://github.com/dotnet/docfx/issues/8449
> Fix docfx build warnings

- Source/LinqToDB/DataProvider/DB2/DB2BulkCopy.cs
- Source/LinqToDB/DataProvider/DB2/DB2BulkCopyShared.cs
- Source/LinqToDB/DataProvider/Informix/InformixBulkCopy.cs
https://github.com/LinqToDB4iSeries/Linq2DB4iSeries/issues/69#issuecomment-1444553980
@nsarris FYI
> Expose DB2BulkCopy.ProviderSpecificCopyImpl

- .editorconfig
- Build/Azure/pipelines/templates/build-job.yml
- Build/Azure/pipelines/templates/test-workflow-linux.yml
- Build/Azure/pipelines/templates/test-workflow-macos.yml
- Build/Azure/pipelines/templates/test-workflow-windows.yml
- Directory.Build.props
- Directory.Packages.props
Will be merged after Azure updated to 17.5
> Visual Studio 17.5 build fixes

- Source/LinqToDB/DataProvider/Access/AccessSpecific.cs
- Source/LinqToDB/DataProvider/DatabaseSpecificTable.cs
- Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSpecific.cs
- Source/LinqToDB/DataProvider/Oracle/OracleHints.cs
- Source/LinqToDB/DataProvider/Oracle/OracleSpecific.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteHints.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteSpecific.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeHints.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeSpecific.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSpecific.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/IExpressionQueryT.cs
- Source/LinqToDB/Linq/PersistentTableT.cs
- Source/LinqToDB/LinqExtensions.LoadWith.cs
- Source/LinqToDB/LinqExtensions.cs
- Source/LinqToDB/TempTable.cs
- Tests/Linq/Update/MergeTests.ApiParametersValidation.cs
Found during EF Core extension update.
> Avoid hints execution. Corrected tables immutability.

- Source/LinqToDB/Linq/Builder/AssociationContext.cs
- Source/LinqToDB/Linq/Builder/DefaultIfEmptyBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectManyBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Mapping/AssociationAttribute.cs
- Tests/Linq/Linq/AssociationTests.cs
Fixes issue when nullability re-enabled in deep-nested associations
> Move association DefaultOfEmpty disable flag to builder-only

- Source/LinqToDB/Data/DataConnection.Configuration.cs
> Revert "Fix for #4027."

- Source/LinqToDB/Data/DataConnection.Configuration.cs
- Tests/Base/TestBase.cs
> 4027 dataconnection defaultsettings is read before it could be set 2

- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSqlBuilder.cs
cherry-picked from another branch to fix test failures
(cherry picked from commit c86a40362a17892297c7a392ccebf14a3bbb9e06)
More details: march release 23.3 of ClickHouse added support for table engines for temp tables and now SQL we generate for temporary tables with primary key is not compatible with it
> Fixed latest ClickHouse temp table update.

- NuGet/TestToolLocal.cmd
- Source/LinqToDB.Tools/Scaffold/NameGenerationServices.cs
- Tests/Linq/Scaffold/NameGenerationTests.cs
> [Scaffold] fix generation of association names

- Source/LinqToDB.Templates/LinqToDB.Oracle.ttinclude
- Source/LinqToDB/DataProvider/Oracle/OracleTools.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLTools.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerFactory.cs
- Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
> Pass connection string to PostgreSQLTools/OracleTools.GetDataProvider when available

- Source/LinqToDB/Mapping/DynamicColumnInfo.cs
- Tests/Linq/Reflection/AttributesTests.cs
> Fix DynamicColumnInfo.GetCustomAttributes

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
Fix https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/213
Fix https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/316
Fix https://github.com/linq2db/linq2db/issues/3895
Fix https://github.com/linq2db/linq2db/issues/3776
> Fix tstz DateTime normalization

- Source/LinqToDB/Data/RecordReaderBuilder.cs
- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Linq/Builder/EnumerableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Reflection/MemberAccessor.cs
- Tests/Linq/Linq/InterfaceTests.cs
Fix #4082
Cherrypick from #4036
> Support readonly interface properties with writeable implmentation in query materialization

- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Tests/Linq/Linq/InterfaceTests.cs
Fix  #3034
Cherrypick from #4036
> Fix interfaces inheritance support

- Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
Migrates the `MySqlBuilder` changes from #4075 for cleaner history.
> Cherry Pick changes from #4075

- Source/LinqToDB/Linq/Builder/AllJoinsLinqBuilder.cs
- Source/LinqToDB/Linq/Builder/JoinBuilder.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/GroupByTests.cs
https://github.com/linq2db/linq2db/issues/4098
> Fix aggregates tracking in joined subqueries

- Source/LinqToDB/Mapping/EntityMappingBuilder.cs
- Tests/Linq/Mapping/DynamicStoreTests.cs
Discovered during #4026 testing
> Add missing xmldoc and fix NRT annotations for DynamicPropertyAccessors API

- Data/Create Scripts/SqlServer.sql
- Source/LinqToDB.Tools/DataModel/Context/NestedSchemaGenerationContext.cs
- Source/LinqToDB.Tools/DataModel/DataModelGenerator.Functions.Table.cs
- Tests/Tests.T4/Cli/All/SqlServer/TestSchemaSchema.cs
- Tests/Tests.T4/Cli/Fluent/SqlServer/TestDataDB.cs
- Tests/Tests.T4/Cli/Fluent/SqlServer/TestSchemaSchema.cs
- Tests/Tests.T4/Cli/NoMetadata/SqlServer/TestSchemaSchema.cs
- Tests/Tests.T4/Cli/T4/SqlServer/TestDataDb.cs
> Fix table function scaffold in separate schema class

- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/GroupByTests.cs
> Fix subquery order-by hoisting issues for aggregate-only queries

- .editorconfig
- Directory.Packages.props
- Source/LinqToDB/Common/DbDataType.cs
- Source/LinqToDB/DataProvider/ReaderInfo.cs
- Source/LinqToDB/Expressions/MemberHelper.cs
- Source/Shared/HashCode.cs
- Source/Shared/ValueTuple.cs
If it will cause issues with CI, we will merge it after Azure update to 17.6
> Fix builds with VS 17.6

- Source/LinqToDB/Data/CommandInfo.cs
- Tests/Linq/Linq/ConvertTests.cs
> Support column converters for Execute[Async](sql)

- Source/LinqToDB.AspNet/ServiceConfigurationExtensions.cs
> Fix code examples

- Tests/Linq/Linq/CteTests.cs
Regression test for #4167
Issue caused by invalid parameter name generation from `GetValueOrDefault` call: `_default`, which is not correct for Oracle as starts from `_`
> Add regression test

- Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs
- Tests/Linq/DataProvider/OracleTests.cs
Update Oracle11SqlOptimizer to add null check based on operator
Fix #4172
> #4172: Fixes issue with empty string check in Oracle

- Build/Azure/pipelines/templates/test-matrix.yml
- Tests/Linq/Linq/GroupByTests.cs
> Disable netcoreap31 tests

- Directory.Packages.props
- Tests/Linq/Data/MiniProfilerTests.cs
- Tests/Linq/DataProvider/MySqlTests.cs
> Stop testing old mysqlconnector packages

- Source/LinqToDB.Tools/CodeModel/Types/Parser/TypeParser.cs
- Tests/Linq/Scaffold/TypeParserTests.cs
> [scaffold] Fix multiple issues in type parser

- NuGet/README.T4.md
- NuGet/linq2db.Access.nuspec
- NuGet/linq2db.DB2.Core.nuspec
- NuGet/linq2db.DB2.nuspec
- NuGet/linq2db.Firebird.nuspec
- NuGet/linq2db.Informix.Core.nuspec
- NuGet/linq2db.Informix.nuspec
- NuGet/linq2db.MySql.nuspec
- NuGet/linq2db.MySqlConnector.nuspec
- NuGet/linq2db.Oracle.Managed.nuspec
- NuGet/linq2db.Oracle.Unmanaged.nuspec
- NuGet/linq2db.PostgreSQL.nuspec
- NuGet/linq2db.SQLite.MS.nuspec
- NuGet/linq2db.SQLite.nuspec
- NuGet/linq2db.SapHana.nuspec
- NuGet/linq2db.SqlCe.nuspec
- NuGet/linq2db.SqlServer.MS.nuspec
- NuGet/linq2db.SqlServer.nuspec
- NuGet/linq2db.Sybase.DataAction.nuspec
- NuGet/linq2db.Sybase.nuspec
- NuGet/linq2db.t4models.nuspec
- linq2db.sln
Due to strong internal and external opposition let's remove obsoletion notes...
> Unobsolete t4 nugets

- Source/LinqToDB/Linq/QueryRunner.Update.cs
- Tests/Linq/Linq/InheritanceTests.cs
Fix #4280
Related to #1070 - it was missing required change for update query
> Fix update for inheritance mapping

- Tests/Linq/Linq/CachingTests.cs
Tests for #4266
Looks like we need mechanism to (partially)evaluate extension to fix it properly
> Add tests for #4266

- Source/LinqToDB/Linq/Builder/EnumerableBuilder.cs
- Tests/Linq/Linq/AllAnyTests.cs
> Fix long enumerable sequences handling

- Source/LinqToDB/Expressions/ExpressionEvaluator.cs
- Source/LinqToDB/Extensions/ReflectionExtensions.cs
Thanks to https://www.meziantou.net/get-the-default-value-of-a-type-at-runtime.htm for remainder
> Fix default type value getter

- Source/LinqToDB/DataProvider/BasicBulkCopy.cs
- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseBulkCopy.cs
- Source/LinqToDB/DataProvider/DB2/DB2BulkCopyShared.cs
- Source/LinqToDB/DataProvider/Informix/InformixBulkCopy.cs
- Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
- Source/LinqToDB/DataProvider/MySql/MySqlBulkCopy.cs
- Source/LinqToDB/DataProvider/Oracle/OracleBulkCopy.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLBulkCopy.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaBulkCopy.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeBulkCopy.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerBulkCopy.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseBulkCopy.cs
- Tests/Linq/Update/BulkCopyTests.cs
> Respect CloseAfterUse in BulkCopy

- Source/LinqToDB/DataProvider/Access/AccessSqlBuilderBase.cs
- Source/LinqToDB/SqlQuery/SqlValue.cs
- Tests/Linq/Linq/GroupByTests.cs
> Fix SqlValue type nullability

- Source/LinqToDB/Common/Internal/TypeExtensions.cs
another change for efcore integration
> Open TypeExtensions.IsInteger api

- Build/Azure/pipelines/templates/build-vars.yml
- Directory.Packages.props
- Source/LinqToDB/DataProvider/PostgreSQL/NpgsqlProviderAdapter.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
- Tests/Linq/SchemaProvider/PostgreSQLSchemaProviderTests.cs
> Fix regression with Npgsql 7- support

- .editorconfig
- Directory.Build.props
- Tests/FSharp/Tests.FSharp.fsproj
Fix CI build with new VS/C# release
> Suppress new C# 12 analyzer warnings

- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Options.cs
> fix regex in scaffold help

- Directory.Packages.props
- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseBulkCopy.cs
- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseProviderAdapter.cs
- Tests/Linq/UserTests/Issue4389Tests.cs
> Upgrade ClickHouse.Client package

- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Tests/Linq/UserTests/Issue4383Tests.cs
> Issue with generic class association member

- Source/LinqToDB/Data/BulkCopyOptions.cs
- Source/LinqToDB/Data/ConnectionOptions.cs
- Source/LinqToDB/Data/QueryTraceOptions.cs
- Source/LinqToDB/Data/RetryPolicy/RetryPolicyOptions.cs
- Source/LinqToDB/DataContextOptions.cs
- Source/LinqToDB/DataProvider/Access/AccessOptions.cs
- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseOptions.cs
- Source/LinqToDB/DataProvider/DB2/DB2Options.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdOptions.cs
- Source/LinqToDB/DataProvider/Informix/InformixOptions.cs
- Source/LinqToDB/DataProvider/MySql/MySqlOptions.cs
- Source/LinqToDB/DataProvider/Oracle/OracleOptions.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLOptions.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteOptions.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaOptions.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeOptions.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerOptions.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseOptions.cs
- Source/LinqToDB/LinqOptions.cs
Couple of fixes and comments to remind adding new option properties wherever needed.
> Options small fixes and comments.

- Source/LinqToDB/Common/OptionsContainer.cs
> Concurrency issue in DataConnection options

- Build/Azure/README.md
- Build/Azure/net472/sqlserver.2022.metrics.json
- Build/Azure/net60/sqlserver.2022.metrics.json
- Build/Azure/net70/sqlserver.2022.metrics.json
- Build/Azure/pipelines/default.yml
- Build/Azure/pipelines/templates/test-matrix.yml
- Build/Azure/pipelines/testing.yml
- Tests/Base/BaselinesWriter.cs
- linq2db.sln
- run metrics only on release test-run or manually using `test-metrics` pipeline
- add line spacing to generated metrics file to improve review experience from GH UI
> Refactor metrics automation

- Source/LinqToDB/DataProvider/Oracle/OracleBulkCopy.cs
- Tests/Linq/Update/BulkCopyTests.cs
> Fix Oracle BulkCopy parameters

- Build/Azure/scripts/clickhouse.sh
- Data/Setup Scripts/clickhouse.cmd
- Tests/Linq/Linq/ParameterTests.cs
> Support primary constructor parameters as query parameters

- Source/LinqToDB.AspNet/ServiceConfigurationExtensions.cs
- Tests/Linq/Data/DataConnectionTests.cs
> Fix registration by `AddLinqToDBContext<TContext, TContextImplementation>`

- Directory.Packages.props
- NuGet/linq2db.AspNet.nuspec
- Source/LinqToDB.AspNet/LinqToDB.AspNet.csproj
- Source/LinqToDB.AspNet/ServiceConfigurationExtensions.cs
- Source/LinqToDB.Remote.Grpc/LinqToDB.Remote.Grpc.csproj
- Source/LinqToDB/DataProvider/Oracle/OracleXmlTable.cs
> More NativeAOT annotations

- Tests/Base/BaselinesWriter.cs
Try to remove TFM from baselines as different TFMs should produce same baselines. Should reduce amount of duplicate baselines by 60%
> Use version-less baselines folders

- Source/LinqToDB/DataContextTransaction.cs
- Tests/Linq/Data/InterceptorsTests.cs
> Release connection of DataContext transaction disposal

- Source/Directory.Build.props
- Source/LinqToDB/Expressions/ConstantPlaceholderExpression.cs
- Source/LinqToDB/Expressions/ExpressionVisitorBase.cs
- Source/LinqToDB/Expressions/ExpressionVisitors/EqualsToVisitor.cs
- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Source/LinqToDB/Linq/Builder/ParametersContext.cs
- Source/LinqToDB/Linq/ExpressionCacheHelpers.cs
- Source/LinqToDB/Linq/Query.cs
> Revised closure caching. Simplified algorithm.

- Directory.Packages.props
- Source/Directory.Build.props
- Source/LinqToDB/Expressions/SqlQueryRootExpression.cs
- Tests/Linq/ThirdParty/LinqKitTests.cs
- Tests/linq2db.TestProjects.props
> Fixed integration with third party extensions.

- Source/Directory.Build.props
- Source/LinqToDB/Linq/Builder/AggregationBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/SqlProvider/SqlExpressionConvertVisitor.cs
- Source/LinqToDB/SqlProvider/SqlExpressionOptimizerVisitor.cs
- Source/LinqToDB/SqlQuery/QueryHelper.Evaluate.cs
- Tests/Linq/Linq/GroupByTests.cs
- Tests/Linq/Linq/MappingTests.cs
> Multiple regressions in v6

- Tests/Linq/Update/MultiInsertTests.cs
> Test case for bug #2988

- Tests/Linq/UserTests/Issue2900Tests.cs
> New expr translation

- Build/Azure/pipelines/templates/build-vars.yml
- README.md
- Tests/Linq/Tools/EntityServices/IdentityMapTests.cs
- Tests/Model/TestDataCustomConnection.cs
Two new unit test to test the problem in #4365.
CompiledQueryCustomTest() works but CompiledQueryCustomTestAsync() fails.
> Unit tests for custom IDataContext class

- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/LinqExtensions.cs
> Add misssing cancellation token parameter

- Source/LinqToDB/Linq/Builder/OrderByBuilder.cs
- Tests/Linq/Linq/OrderByTests.cs
Probably closes #4557.
Added support for this option.
> Added support for DoNotClearOrderBys.

- Directory.Packages.props
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.Expressions.cs
> Do not convert simple constant to the SQL for projection.

- Source/BannedSymbols.txt
- Source/LinqToDB/AsyncExtensions.cs
- Source/LinqToDB/AsyncExtensions.generated.cs
- Source/LinqToDB/AsyncExtensions.tt
- Source/LinqToDB/Remote/RemoteDataContextBase.QueryRunner.cs
> Improve Task.Run()/CancellationToken code

- Source/LinqToDB/Async/IQueryProviderAsync.cs
- Source/LinqToDB/DataProvider/Access/AccessHints.cs
- Source/LinqToDB/DataProvider/Access/AccessSpecific.cs
- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseHints.cs
- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSpecific.cs
- Source/LinqToDB/DataProvider/DatabaseSpecificQueryable.cs
- Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSpecific.cs
- Source/LinqToDB/DataProvider/Oracle/OracleHints.cs
- Source/LinqToDB/DataProvider/Oracle/OracleSpecific.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLExtensions.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLHints.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSpecific.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeHints.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeSpecific.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSpecific.cs
- Source/LinqToDB/LinqExtensions.Delete.cs
- Source/LinqToDB/LinqExtensions.Insert.cs
- Source/LinqToDB/LinqExtensions.LoadWith.cs
- Source/LinqToDB/LinqExtensions.Merge.cs
- Source/LinqToDB/LinqExtensions.MultiInsert.cs
- Source/LinqToDB/LinqExtensions.Update.cs
- Source/LinqToDB/LinqExtensions.cs
- Source/LinqToDB/Sql/Sql.Analytic.cs
- Source/LinqToDB/TempTable.cs
- Tests/Linq/Update/MergeTests.ApiParametersValidation.cs
> Validate `IQueryable<>` is valid

- Build/Azure/scripts/sqlserver.2022.sh
- Data/Setup Scripts/sqlserver2022.cmd
- Source/LinqToDB/LinqExtensions.cs
> Don't assert intermediate APIs

- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizerVisitor.cs
- Tests/Linq/Linq/GroupByTests.cs
- Tests/Linq/Linq/TypesTests.cs
- re-enable tests for ClickHouse after it is fixed on CH side
- fix query conditions merge
- more fixes to come
> Fix additional discovered regressions

- Tests/Base/TestUtils.cs
by not adding test table setup/teardown to baselines
> Reduce baselines size/noise

- Source/LinqToDB/Linq/Builder/ExpressionBuildVisitor.cs
- Tests/Linq/UserTests/Issue4813Tests.cs
> Fix for issue #4813

- NuGet/t4models/linq2db.t4models.nuspec
> Update linq2db.t4models dependency.

- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/ExpressionCacheHelpers.cs
- Source/LinqToDB/Linq/ExpressionCacheManager.cs
- Source/LinqToDB/Linq/TableT.cs
- Source/LinqToDB/SharedTypeExtensions.cs
- Tests/Linq/Linq/CachingTests.cs
- add tests for #4266 non-builder implementation
- fix handling of scalar values for reference types
> Fix scallar reference types support

- Build/Azure/pipelines/templates/build-job.yml
- Build/Azure/pipelines/templates/build-vars.yml
- Build/Azure/pipelines/templates/nuget-job.yml
- NuGet/Pack.cmd
- NuGet/linq2db.Compat.nuspec
- Source/LinqToDB.Compat/LinqToDB.Compat.csproj
Forgotten part of https://github.com/linq2db/linq2db/pull/4821
> Add linq2db.Compat nuget build

- Source/LinqToDB/Sql/Sql.Collate.cs
- Tests/Base/TestUtils.cs
> Fix collation with "-" character validation in Sql.Collate API

- Source/LinqToDB/Linq/Builder/ExpressionBuildVisitor.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.Associations.cs
- Tests/Linq/Linq/JoinOptimizeTests.cs
> Fix build of association, defined on interface

- Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs
- Tests/Linq/Linq/AnalyticTests.cs
> Fix ArgIndices mapping by Sql.ExpressionAttribute

- Tests/EntityFrameworkCore/ContextTestBase.cs
- Tests/EntityFrameworkCore/Models/IssueModel/IssueContextBase.cs
- Tests/EntityFrameworkCore/Models/IssueModel/IssueEntities.cs
- Tests/EntityFrameworkCore/Tests/CustomContextIssueTests.cs
- Tests/EntityFrameworkCore/Tests/IssueTests.cs
adds tests for https://github.com/linq2db/linq2db/issues/4783
> More issue tests

- Source/LinqToDB/Linq/Builder/ExpressionBuildVisitor.cs
- Source/LinqToDB/Linq/ExpressionCacheManager.cs
- Tests/Linq/Linq/ContainsTests.cs
Fix #4317
I would say that this change will not protect from all possible cases where user could create fragile condition mixing client and server sub-conditions, but at least it will help to reduce number of parameters in some cases.
> Сompact client-side logical conditions

- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
- Tests/Linq/DataProvider/MySqlTests.cs
> Fix temporary table drop statement for MySQL

- Source/LinqToDB/DataProvider/SQLite/SQLiteSchemaProvider.cs
> Remove sqlserver copy-paste logic, not applicable to sqlite

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/UserTests/Issue4891Tests.cs
> Fix for #4891 - Corrected member comparison.

- Source/LinqToDB/DataProvider/SqlServer/SqlServer2012SqlOptimizer.cs
- Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs
- Source/LinqToDB/Linq/Builder/OrderByBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Linq/OrderByTests.cs
> Removed optimized out OrderBy items from SQL.

- Source/LinqToDB/Linq/Builder/MergeBuilder.InsertWhenNotMatched.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.UpdateWhenMatched.cs
- Source/LinqToDB/Linq/Builder/TableLikeQueryContext.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.Merge.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizerVisitor.cs
- Source/LinqToDB/SqlQuery/SqlQueryColumnNestingCorrector.cs
- Source/LinqToDB/SqlQuery/SqlQueryColumnUsageCollector.cs
- Source/LinqToDB/SqlQuery/SqlTableLikeSource.cs
- Tests/Linq/UserTests/Issue4923Tests.cs
> Added handling Enumerable source with lookup to other tables.

- Source/LinqToDB/SqlProvider/SqlExpressionOptimizerVisitor.cs
- Tests/Linq/Linq/WhereTests.cs
Faced `ArgumentOutOfRangeException` in very complex condition (tried to simplify it as much as possible in test).
> Fix predicate optimization exception

- Source/LinqToDB/Linq/Builder/TableLikeQueryContext.cs
- Tests/Linq/Update/MergeTests.Issues.cs
> Fix column aliases generation for enumerable Merge source

- Source/LinqToDB/Internal/Linq/Builder/LoadWithBuilder.cs
- Source/LinqToDB/Internal/SqlQuery/SelectQueryOptimizerVisitor.cs
- Tests/Linq/Linq/AnalyticTests.cs
- Tests/Linq/UserTests/Issue5049Tests.cs
- Tests/Linq/UserTests/Issue5052Tests.cs
> Fix LoadWith regression. Relaxed APPLY JON optimization.

- Source/LinqToDB/Mapping/ColumnDescriptor.cs
- Tests/EntityFrameworkCore/Tests/IssueTests.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
- Tests/Linq/Linq/ValueConversionTests.cs
> Fix converter use for nullable types

- Source/LinqToDB/Internal/DataProvider/Informix/InformixSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/Oracle/OracleSqlBuilderBase.cs
- Source/LinqToDB/Internal/Remote/LinqServiceSerializer.cs
- Source/LinqToDB/Internal/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/Internal/SqlProvider/SqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/SqlQuery/SelectQuery.cs
- Source/LinqToDB/Internal/SqlQuery/SqlPredicate.cs
- Source/LinqToDB/Internal/SqlQuery/Visitors/QueryElementVisitor.cs
- Tests/Linq/DataProvider/OracleTests.cs
- Tests/Linq/Linq/BooleanTests.cs
> Fix boolean coalesce support

- Source/LinqToDB/Internal/Linq/Builder/EnumerableContext.cs
- Tests/Linq/Linq/MappingTests.cs
> Fix custom type collection mapping

- Build/Azure/pipelines/templates/build-job.yml
- Source/LinqToDB/Internal/DataProvider/Access/AccessSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/DB2/DB2SqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/SqlCe/SqlCeSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/Sybase/SybaseSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/Translation/ProviderMemberTranslatorDefault.cs
- Source/LinqToDB/Internal/DataProvider/Translation/SqlExpressionFactoryExtensions.cs
- Source/LinqToDB/Internal/DataProvider/Translation/SqlFunctionsMemberTranslatorBase.cs
- Source/LinqToDB/Internal/DataProvider/Translation/TranslationContextExtensions.cs
- Source/LinqToDB/Internal/SqlProvider/SqlExpressionConvertVisitor.cs
- Source/LinqToDB/Sql/Sql.cs
- Tests/Linq/Linq/NullIfTests.cs
> Refactored NULLIF translation.

- Source/LinqToDB/Internal/DataProvider/Informix/InformixSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/Oracle/OracleSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/SqlQuery/QueryHelper.cs
- Source/LinqToDB/Internal/SqlQuery/Visitors/SelectQueryOptimizerVisitor.cs
- Tests/Linq/Linq/CteTests.cs
Wrong query generated in v6
v5.4.1 is OK :)
PS running tests on my project, some new issues would be in next few days, sorry but my kung-fu would be not enough now to fix em :( so only tests would be
> v6 regression: CTE

- Source/LinqToDB/Internal/DataProvider/SqlServer/SqlServerDataProvider.cs
- Tests/Linq/DataProvider/Types/TypeTestsBase.cs
- Tests/Linq/Linq/DataTypesTests.cs
- Tests/Linq/UserTests/Issue1373Tests.cs
Remaining test changes from #4954 task that will affect corresponding baselins
- add parameter type to help YDB to type it
- update tested date to fit into YDB-supported range
- fix missing uses of parameter vs literal switch in type tests
> Various test updates

- Source/LinqToDB/Internal/DataProvider/DataProviderBase.cs
- Source/LinqToDB/Internal/DataProvider/DynamicDataProviderBase.cs
- Source/LinqToDB/Internal/DataProvider/SqlServer/SqlServerDataProvider.cs
Part of #4954
Add new registration helpers to support YDB mappings
> Add additional reader registration helpers

- Source/LinqToDB/Internal/DataProvider/MultipleRowsHelper.cs
> Fix column type use for multiple-rows bulk copy mode

- Source/LinqToDB/Internal/DataProvider/DataProviderBase.cs
- Source/LinqToDB/Internal/DataProvider/SQLite/SQLiteDataProvider.cs
> Fix binary parameter type
