linq2db/linq2db

- Source/Data/CommandInfo.cs
- Source/Data/DataConnection.Async.cs
- Source/Data/DataConnection.Linq.cs
- Source/Data/DataConnection.cs
- Source/DataProvider/DataProviderBase.cs
- Source/DataProvider/IDataProvider.cs
- Source/DataProvider/SapHana/SapHanaMappingSchema.cs
- Source/DataProvider/SapHana/SapHanaOdbcDataProvider.cs
- Source/DataProvider/SapHana/SapHanaSqlBuilder.cs
- Tests/Linq/DataProvider/ExpressionTest.cs
- Tests/Linq/Linq/SelectScalar.cs
- Tests/Linq/Linq/TableFunctionTest.cs
- Tests/Linq/Update/MergeTest.cs
Hi,
I use SapHanaOdbcDataProvider, because at current state ADO.NET drivers have poor performance.
I need ability to call stored procedures, and ODBC drivers use [different approach] (http://support.microsoft.com/kb/310130) than ADO.NET drivers.
Before CommandInfo class was added, i was able to write my own DataConnection extension method and change this behavior outside of linq2db library, but this approach was ugly, so now i fixed it :)
I added PrepareCommandInfo method for IDataProvider, so that DataProvider could change command state, if it needs, before execution.
> Prepare db command before executing

- Source/Data/DataConnection.cs
We don't have connection string in web.config file.
This is for selecting provider into linq2db.
> Create data connection by provider name and connection string

- Source/DataProvider/MultipleRowsHelper.cs
This change need to properly insert bulk of items like this:
```
[Table("CableCurve")]
public partial class CableCurve
{
[Column(                  DataType=DataType.Int32,  Precision=10), PrimaryKey, Identity] public int          CableCurveID { get; set; } // Long
[Column(                  DataType=DataType.Int32,  Precision=10), NotNull             ] public int          CableID      { get; set; } // Long
[Column(                  DataType=DataType.Double, Precision=15), NotNull             ] public double       Load         { get; set; } // Double
[Column("T_UTemperature", DataType=DataType.Double, Precision=15), NotNull             ] public UTemperature T            { get; set; } // Double
}
```
ConvertExpression also set:
```
MappingSchema.Default.SetConvertExpression<Double, …
```
> Fix BulkCopy for objects with custom type properties

- Source/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
This solves my problem with storing timetstamptz  - when using datetimediff as parameter it is converted using 6 decimal places to parameter (length attribute is ignored) and checking for equality is not possible. Now using timestamptz(6) we can check for equality cause last 3 places are not rounded/cut off. Haven't noticed any side effects.
> Use Ticks instead of time fields for greater precision

- Source/SqlQuery/SelectQuery.cs
fix #223 
The same SqlValue (with value 1) shoul be considered as different if they belong different contexts.
> Added parent property comparison to Column.Equals

- Source/DataProvider/SqlServer/SqlServerSchemaProvider.cs
In sys.extended_properties minor_id is columnId and in INFORMATION_SCHEMA.COLUMNS ORDINAL_POSITION is not columnId.
See remarks in https://msdn.microsoft.com/en-us/library/ms188348(v=sql.110).aspx.
> Fix wrong descriptions for columns.

- Source/DataProvider/Oracle/OracleSqlBuilder.cs
Weird bug on OracleCommand. If a line break occurs right after a "RETURNING" statement, the command would hang forever.
> Fix OracleCommand that hang when using "RETURNING" statement

- Source/Linq/Builder/SelectContext.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/GenericsFilterTest.cs
Hi! We have a problem with some complex queries. I think that the cause in line 
```
if (me.Member == binding.Member)
```
When compared "me.Member" and "binding.Member" the first one can be interface preperty that is implemented by type with the second one. In this case comparision gives us "false" and then exception raised, but I think that it is possible to proceed.
Simplest solution is to replace "me.Member == binding.Member" with "me.Member.Name == binding.Member.Name", but it is not good idea, so I used InterfaceMapping to determine if property is interface implementation.
Without this fix test "WhenPredicateFactoryIsNotGeneric" passes, but "WhenPredicateFactoryIsGeneric" fails. With it both tests pass.
> Fixed problem with generic filter predicates

- Source/DataProvider/SqlServer/SqlServer2000SqlBuilder.cs
- Source/DataProvider/SqlServer/SqlServerSqlBuilder.cs
Replace SCOPE_IDENTITY() with OUTPUT for all types, not only for GUIDs,
SCOPE_IDENTITY also does not working with SEQUENCEs (MS SQL 2012).
http://www.sqlbadpractices.com/how-not-to-retrieve-identity-value/
> Retrieving identity value by using the OUTPUT clause. MSSQL Server since 2005 version. #268

- Source/DataProvider/MySql/MySqlSqlBuilder.cs
http://dev.mysql.com/doc/refman/5.7/en/cast-functions.html#function_cast
Previous behaviour: DataType.Int64 were built to default BIGINT which leads to error on sql side:
'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BIGINT) ='
Fixed: DataType.Int32, Int64, Int32 -> 'Signed', UInt16, UInt32, UInt64 -> 'Unsigned'
> Fixed MySql CAST operation

- Source/Data/DataParameter.cs
- Source/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
- Source/DataProvider/PostgreSQL/PostgreSQLSchemaProvider.cs
- Source/DataProvider/PostgreSQL/PostgreSQLTools.cs
- Source/DataType.cs
Added support to npsql 3.x datetime and new datatype Dictionary for hstore key-value pairs that are now supported by npgsql driver.
> Npgsql 3.0 datetime and hstore support

- Source/SqlQuery/SqlTable.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/CreateDecimalTableColumn.cs
Hi!
I've noticed that 'Precision' and 'Scale' of SqlDataType are ignored when creating table. 
Here is posible fix and test.
> Fixed column's Precision and Scale when creating table

- Source/DataProvider/Oracle/OracleSchemaProvider.cs
Slow downs the method OracleSchemaProvider.GetForeignKeys(DataConnection dataConnection).
#453
> T4 Template for Oracle is very slow. Can generate the model about 5 minutes.

- Source/DataProvider/Oracle/OracleSchemaProvider.cs
I have comments on columns in DB. But Oracle T4 Template does not fill Description properties on ColumnInfo's. Therefore there no XML comments on the generated code.
#452
> T4 Oracle Template does not generate XML code comments for columns.

- Source/Common/Configuration.cs
- Source/Linq/Builder/OrderByBuilder.cs
- Tests/Linq/Linq/OrderByTests.cs
If you hav nested Queryables, your object may become a Iqueryable again so you cannot use ThenBy. So don't clear orderbys
> Disable Clear of oderbys

- Source/DataProvider/PostgreSQL/PostgreSQLTools.cs
http://rsdn.org/forum/prj.rfd/6628354.1
Сама ошибка описана в передыдущей _версии_ указанного выше сообщения (тут http://rsdn.org/f/message/version/84495). Я хотел ответить, а нажал редактировать его.
Получается ошибка внесена была уже после 1.0.7.4 потому и сложно воспроизводилась: 
тут https://github.com/linq2db/linq2db/commit/3af76ec864ade38413501749dffe2b53bf672c6a
> Fix bug with autodetect version of PostgreSQL provider.

- Source/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
```cs
public partial class Customer
{
[PrimaryKey, Identity   ] public int    Id      { get; set; } // int
[Association(ThisKey="Id", OtherKey="AltCustomerId", CanBeNull=true, IsBackReference=true)]
public IEnumerable<Order> AltOrders { get; set; }
}
public partial class Order
{
[Column,        Nullable] public int?            AltCustomerId { get; set; } // int
[PrimaryKey, Identity   ] public int             Id            { get; set; } // int
}
```
Execute query
```cs
var query = linq2db.Customers.Select(c => new { c.AltOrders });
```
throw exeption InvalidOperationException
> The binary operator Equal is not defined for the types 'System.Nullable`1[System.Int32]' and 'System.Int32'.
> fix join nullable types Expression.Equal(T, T?)

- Source/Data/DataConnectionExtensions.cs
`CommandInfo` provides the method `ExecuteProc<T>` to execute scalar
commands. This pull request adds the missing extension method to call it
directly via a `DataConnection` object.
> Add missing extension method ExecuteProc<T>

- Source/DataProvider/Oracle/OracleSqlBuilder.cs
Added DateTimeOffset to oracle create test, and verified I could write a date in and read it back out the same. Ultimately didn't leave it in the test project.
> Add appropriate oracle type for datetimeoffset to SQL builder

- Source/Mapping/EntityMappingBuilder.cs
- Source/Mapping/PropertyMappingBuilder.cs
- Tests/Linq/Mapping/FluentMappingTests.cs
Hi.
I like to keep my models free of mapping attributes, and my mapping free of stringy property names, which is easily done by using the fluent mapping api. Except for associations, which doesn't seem to enjoy any fluent support. To fix that I've been using the below extension method. It works great, but I thought I'd try and submit it as a proper addition to the fluent mapping, so here you go.
```cs
using System;
using System.Linq.Expressions;
using LinqToDB.Mapping;
namespace Actimizer.LRM.Linq2DB.Mappers
{
public static class MapperExtensions
{
//private static GetMemberName( Expression expr )
//{
//    ExpressionVisitor
//}
public static PropertyMappingBuilder<T> Association<T,S,ID1,ID2>( 
this PropertyMappingBuilder<T> pmb, 
Expression<Func<T, S>> prop, 
Expression<Func<T, ID1>> …
```
> Proposal for adding fluent mapping api for associations

- Source/Linq/Builder/TableBuilder.cs
- Tests/FSharp/Models.fs
- Tests/FSharp/WhereTest.fs
- Tests/Linq/Linq/FSharpTests.cs
Hi.
To make Entity Framework work with F# records, you have to mark the records with the CLIMutableAttribute. This makes the porperties settable from other CLR languages, but still read-only from F#. It works pretty well.
I have a bunch of EF models that I'm trying to migrate to linq2db, but ironically linq2dbs support for records made this problematic for two reasons:
1. Linq2db exprect that records have only 1 constructor, but the CLIMutable attribute causes the record class to also have a default constructor.
2. Linq2db doesn't support relational properties for true records.
This pull request deals with 1.
I didn't plan on keeping the CLIMutable attribute, but reason number 2 made it the easier option to begin with. I have one more PR coming which implements relational properties for …
> Adding support for fsharp climutable attribute

- Source/Linq/Builder/TableBuilder.cs
- Tests/FSharp/Models.fs
- Tests/FSharp/WhereTest.fs
- Tests/Linq/Linq/FSharpTests.cs
Hi again
So this is my first attempt at proper support for relational properties in F# records.
Initially I played with copying the LoadWith logic from BuildDefaultConstructor and setting the association property mutable. That worked, but was obviously undesireable.
What was really needed was a way to pass the associated instance object to the record constructor. This PR is the result of that change. 
I decided to put the association check before the complex check, since I see that as the more likely scenario.
I haven't tested relational nesting deeper that one level yet, but I'll get to that.
Initially I had hoped to add support for option type relations, to make it truly F# ideomatic. Unfortunately that turned out to be complicated, so I'll start a separate issue about that.
Things to …
> Adding F# sharp record support for relational properties

- Source/Data/DataConnection.Linq.cs
- Tests/Linq/Samples/ConcurrencyCheckTests.cs
- Tests/Linq/Tests.csproj
Sample for #553
Also found that after cloning selectQuery, parameters are not handled correctly.
@igor-tkachev, take a look at this small change.
> Concurrency sample

- Source/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/Linq/IssueTests.cs
- linq2db.sln.DotSettings
Fix for #115 
Problem that columns for MemberExpression correctly expanded in TableBuilder in ConvertToSql method bu not in SelectContext. I hope that i found appropriate place and correctly fixed this issue.
@igor-tkachev, please review it's not obvious for me.
> Possible fix for #115

- Source/Linq/Builder/AggregationBuilder.cs
- Source/Linq/Builder/AllAnyBuilder.cs
- Source/Linq/Builder/CountBuilder.cs
- Source/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Tests/Linq/Linq/IssueTests.cs
Fix for issue #75
I've found that for sub-queries is not called function ConvertToParentIndex which registers such kind of columns in parent query.
@igor-tkachev, please review this pull request.
> Possible fix for #75

- Source/Linq/Builder/GroupByBuilder.cs
- Tests/Linq/Linq/IssueTests.cs
@igor-tkachev, another fix that needs your support.
I have not found any source history, even in BLToolkit, why this part of code was introduced,
In #498 introduced Association with CanBeNull = false. After grouping join become not weak and duplicate is not removed later.
> Possible fix for #498

- Source/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/SqlProvider/BasicSqlBuilder.cs
- Source/SqlQuery/SqlDataType.cs
- Source/SqlQuery/SqlValue.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue271Tests.cs
In general this implementation is hack.
It would be better to make `DataType`  required parameter for `SqlValue` but it would break tons of code. And only for char\nchar in predicate. I think is does not worth.
If we would face with same situation in another query part or with other type we'll make total refactoring.
> Fix for #271

- Source/DataProvider/Oracle/OracleDataProvider.cs
- Tests/Linq/DataProvider/OracleTests.cs
Bugfix for DateTimeOffset in Orace: nanoseconds was
improperly initialized from milliseconds; added full DateTimeOffset
precision (100 ns) instead of millisecond, like native DateTime.
> Bugfix for issue #612

- Source/Mapping/ColumnDescriptor.cs
- Tests/Linq/Mapping/MappingSchemaTests.cs
We should not use PrimartKey & Identity attributes from complex members (foreign keys for example)
> Do not use mapping attributes from "parent" object

- Source/DataProvider/DB2/DB2SqlBuilderBase.cs
- Source/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Source/DataProvider/Informix/InformixSqlBuilder.cs
- Source/DataProvider/MySql/MySqlSqlBuilder.cs
- Source/DataProvider/Oracle/OracleSqlBuilder.cs
- Source/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Source/DataProvider/SapHana/SapHanaSqlBuilder.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/UserTests/Issue681Tests.cs
Fixes fully-qualified table name generation for:
- Firebird
- Oracle
- MySql
- Informix (without server name support, create feature request if you need it)
- SAP HANA
- DB2
> Fix #681, #682, #683

- Source/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/UserTests/Issue513Tests.cs
Post-mortem for review.
Looks like CanCombineParameters flag was never supported for merge-based InsertOrUpdate query and we didn't spotted it before due to:
- only Sybase use this flag in default distribution
- Sybase doesn't use merge-based query for InsertOrUpdate
- for iSeries it wasn't spotted before due to a bug with duplicate parameters, which I fixed here https://github.com/linq2db/linq2db/pull/686#pullrequestreview-40652778
> Add CanCombineParameters support in merge-based InsertOrUpdate

- Source/Linq/Builder/SelectManyBuilder.cs
- Tests/Linq/Linq/DistinctTests.cs
- Tests/Linq/Linq/TakeSkipTests.cs
In queries like:
```cs
from a in db.Some.Skip(0).Take(10).Distinct()
from b in db.Other.Where(...).DefaultIfEmpty()
select {}
```
take, skip & distinct used to be applied to result query, now `db.Some.Skip(0).Take(10).Distinct()` closure is moved to subquery
> move take\skip\distinct to subquery in join

- Source/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/Linq/Builder/TableBuilder.cs
- Tests/Linq/Linq/AssociationTests.cs
Fixed
```cs
public void ExtensionTest3(string context) 
{ 
using (var db = GetDataContext(context)) 
{ 
AreEqual( 
Child.Select(_ => new { p = _.Parent   }).Select(_ => _.p.ParentID), 
db.Child.Select(_ => new { p = _.Parent() }).Select(_ => _.p.ParentID)); 
} 
} 
``
> fixed extension associations

- Source/Linq/Query.cs
- Source/LinqToDB.csproj
This small change adds support for a custom expression postprocessor. (Postprocessor is not configured statically but by particular DataContext.)
> Support for custom expression postprocessing

- Source/DataProvider/SqlServer/SqlServerSqlBuilder.cs
- Source/Sql/Sql.ExtensionAttribute.cs
- Source/Sql/Sql.cs
- Tests/Linq/Linq/ConvertTests.cs
Added Sql.NoConvert function. Sample usage:
```cs
from od in db.OrderDetail
select Sql.NoConvert(od.UnitPrice * od.Quantity * (decimal)(1 - od.Discount))
```
Before:
```sql
SELECT
([t1].[UnitPrice] * Convert(Decimal(29,10), [t1].[Quantity])) * Convert(Decimal(29,10), 1 - [t1].[Discount]) as [c1]
FROM
[Order Details] [t1]
```
After:
```sql
SELECT
([t1].[UnitPrice] * [t1].[Quantity]) * (1 - [t1].[Discount]) as [c1]
FROM
[Order Details] [t1]
```
> Added Sql.NoConvert function.

- Source/DataProvider/Firebird/FirebirdConfiguration.cs
- Source/DataProvider/Firebird/FirebirdMappingSchema.cs
* Trying to do not encode string for Firebird if not needed. 
* Added FirebirdConfiguration.SupportsLiteralEncoding for older versions of Firebird.
> Fix for #851

- Source/LinqToDB/DataProvider/SqlServer/SqlServerDataProvider.cs
- Tests/Linq/Linq/ParameterTests.cs
Setting string parameters to max size for SQL Server. 
It minimizes number of cached plans.
Fixes #989
> Setting string parameters to max size for SQL Server.

- Tests/Linq/DataProvider/OracleTests.cs
- Tests/Linq/Tests.csproj
Ran tests, all but bfile test pass (this failed for me in 4.5.2 as well). Later we should pull the redist oracle core dll, and opt for using the nuget feed when oracle gets that all situated.
> Slight refactoring to allow oracle core beta driver support.

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLTools.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLVersion.cs
- Source/LinqToDB/ProviderName.cs
- Source/LinqToDB/SqlQuery/ReservedWords.cs
- Tests/Linq/Update/MergeTests.cs
INSERT ... ON CONFLICT clause (UPSERT) support for InsertOrUpdate, see https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT
It contains questionable code which overrides and restores table alias. But there is no existing facility to create an alias in INSERT clause and I wanted to make as little changes to the core as possible.
> PostgreSQL 9.5 UPSERT support

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLBulkCopy.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
References:
PostgreSQL COPY documentation - https://www.postgresql.org/docs/current/static/sql-copy.html
COPY support in Npgsql - http://www.npgsql.org/doc/copy.html
It would be better to explicitly specify field type (second parameter in writer method), but I didn't figure out how to get NpgsqlDbType from field description.
> Provider-specific BulkCopy for PostgreSQL

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/UserTests/Issue1099Tests.cs
Choosing more reliable type for instantiating query result.
Fixes issue #1099
> Added possibility to instantiate objects in queries that work with interfaces.

- NuGet/Readme.txt
- Source/LinqToDB/DataProvider/Firebird/FirebirdIdentifierQuoteMode.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Source/LinqToDB/Linq/QueryRunner.Delete.cs
- Tests/Base/ScopedSettings.cs
- Tests/Base/TestBase.cs
- Tests/Base/TestUtils.cs
- Tests/Linq/DataProvider/FirebirdTests.cs
- Tests/Linq/Linq/ComplexTests2.cs
- Tests/Linq/Linq/DateTimeFunctionsTests.cs
- Tests/Linq/Linq/DynamicColumnsTests.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/Update/UpdateTests.cs
- Tests/Linq/UserTests/Issue1057Tests.cs
- Tests/Linq/UserTests/Issue1110Tests.cs
We have some tests added recently, that fail for one or another provider.
This PR will try to fix it.
Fixes #1095 remaining failures
> Working on failing tests

- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlQuery/SqlCteTable.cs
- Source/LinqToDB/SqlQuery/SqlTable.cs
If following method is called:
```
return this.GetCte<CmsDictionary>(employeeHierarchy =>
{
return
(
from f in query
select f
).Concat( 
from f in query
join x in employeeHierarchy on f.Id equals x.Id
select f
);
});
```
there is exception because 
SqlCteTable(mapping, Cte) calls base constructor of SqlTable, inside of base constructor body is referenced property "Name" which is overriden inside upper class (SqlCteTable)
Name property returns Name of CTE which is initializes after base init is finished.
> Proposal for Fix GetCteTable

- Source/LinqToDB/DataContext.cs
Needed for proper tracing of linq2db queries.
> Added OnTraceConnection property for tracing DataContext's connection.

- Source/LinqToDB/DataProvider/BasicMergeBuilder.cs
- Tests/Linq/Update/MergeTests.EmptySource.cs
- Tests/Linq/Update/MergeTests.Operations.Insert.cs
Fixes case, when merge performed over empty local source with source type != target type
> Fix merge with empty source

- Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs
- Tests/Linq/DataProvider/MySqlTests.cs
Current implementation uses Sql Server version to detect an appropriate data provider. Compatibility level should be used instead.
> Use compatibility level to detect Sql Server provider

- Source/LinqToDB/Linq/Builder/SelectManyBuilder.cs
- Tests/Linq/Linq/JoinTests.cs
Outer context in many cases should be enveloped in SubQueryContext.
For now it is enveloped in cases when it is not simple select from the table.
> Fix for issue #1210. Bad outer context initialization.

- Tests/Linq/Create/CreateData.cs
- Tests/Linq/Tests.csproj
Updated package reference to oracles nuget package, which should be easier to maintain, updated filter on the CreateTests for running tests in netcoreapp2.0 against oracle. 
I was seeing test failures in netcoreapp2.0 before and after this change that seemed to be related to running NUNIT tests as netcore2.0. Otherwise all oracle tests are passing and didn't see new failures as a result to changing this reference.
> Updating netcore assembly reference to nuget reference

- Source/LinqToDB/DataProvider/BasicMergeBuilder.cs
- Source/LinqToDB/DataProvider/Informix/InformixMergeBuilder.cs
- Source/LinqToDB/DataProvider/Oracle/OracleMergeBuilder.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerMergeBuilder.cs
- Source/LinqToDB/Merge.cs
- Source/LinqToDB/MergeDefinition.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Update/MergeTests.ApiParametersValidation.cs
- Tests/Linq/Update/MergeTests.CommandValidation.cs
- Tests/Linq/Update/MergeTests.Hints.cs
Fix #1272
SQL Server supports hints on target table, this PR adds support for hints generation.
~Because merge uses different ordering of hint and table alias, you cannot use `With` method, which will put hint after alias and need to use `WithTableExpression` method to specify proper ordering:~
```cs
// {0} is a table
// {1} is an alias
// for merge target alias must go after hint
table.WithTableExpression("{0} WITH (HOLDLOCK) {1}")
```
TODO:
- ~[ ] `UsingTarget` method produce bad sql. We should remove hint from target table, when it used as source~
Edit:
code above shouldn't be used for merge-specific hints, see below
> MERGE target hints support

- NuGet/Pack.bat
- NuGet/PackAV.bat
- NuGet/linq2db.SQLite.MS.nuspec
- NuGet/linq2db.SQLite.nuspec
- linq2db.sln
Fix #1175 
I'm a bit tired how contentFiles work in different types of projects:
- for old projects they added as files
- for new projects like .net core they added as links
- for xamarin projects they don't added at all, but work
Remaining issues:
> Add linq2db.sqlite.ms nuget for Microsoft.Data.Sqlite provider

- NuGet/linq2db.SQLite.MS.nuspec
- Source/LinqToDB/DataProvider/Informix/InformixBulkCopy.cs
- Source/LinqToDB/DataProvider/Informix/InformixDataProvider.cs
- Source/LinqToDB/DataProvider/InvariantCultureRegion.cs
- Source/LinqToDB/ServiceModel/LinqService.cs
- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/ServiceModel/RemoteDataContextBase.cs
- Source/LinqToDB/ServiceModel/ServiceModelDataReader.cs
- Tests/Linq/DataProvider/SQLiteTests.cs
- Tests/Linq/Tests.csproj
just copied fixes from #1286 
- fix serialization to use invariant culture for nullable types
- use provider execution scope for WCF (this fix Informix over WCF queries on systems with non-invariant decimal format)
> Fix serialization issues in WCF

- Data/Create Scripts/SapHana.sql
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/SqlProvider/ValueToSqlConverter.cs
- Tests/Linq/UserTests/Issue1287Tests.cs
Fix #1287
Actually it is overoptimization from compiler that we reverted for char but missed same logic for char?
> Fix char constants support in compare operations with char? operands in expressions

- Source/LinqToDB/DataProvider/SQLite/SQLiteDataProvider.cs
- Tests/Linq/UserTests/Issue1279Tests.cs
Fix #1279
Confirm that only microsoft's sqlite provider returns wrong value (both 1.x and 2.x)
> Fix char parameters for microsoft.data.sqlite

- Data/Create Scripts/Sybase.sql
- Source/LinqToDB/DataProvider/Sybase/SybaseMappingSchema.cs
- Tests/Linq/DataProvider/SybaseTests.cs
- Tests/Linq/Linq/CharTypesTests.cs
- Tests/Linq/Update/MergeTests.Types.cs
Nothing fancy, just more tests, fix for unicode normalization in tests and removal N prefix from string literals as it is not supported by Sybase and just ignored
> Add unicode test for sybase

- Source/LinqToDB/Linq/Builder/TableBuilder.CteTableContext.cs
- Source/LinqToDB/SqlQuery/SqlDeleteStatement.cs
- Source/LinqToDB/SqlQuery/SqlInsertOrUpdateStatement.cs
- Source/LinqToDB/SqlQuery/SqlInsertStatement.cs
- Source/LinqToDB/SqlQuery/SqlUpdateStatement.cs
- Tests/Linq/Linq/CteTests.cs
Fixed invalid SQL generation for recursive CTE when using Count() function. 
Fixed missed Walk calls which cause invalid AST generation.
> Fixed invalid SQL generation for recursive CTE when using Count()

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Tests/Base/TestBase.cs
- Tests/Linq/Linq/ExpandTests.cs
- Tests/Tests.Playground/ExpandTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
- linq2db.playground.sln.DotSettings
For now developer can use expression tree variable inside LINQ Query.
Idea was borrowed from LinqKit library.
For example if you have variable
```cs
Expression<Func<SampleClass, bool>> predicate = c => c.Value > 1;
```
It is difficult to use it in linq. For now you can use it in the following way (using `Compile()`):
```cs
var query = from t in table
from t2 in table.Where(predicate.Compile())
select t;
```
Or compile with invokation:
```cs
var query = from t in table
where predicate.Compile()(t)
select t;
```
-----------
Also this PR contains fix with bad evaluation of functions that have Lambda as parameter. For now the following query should work:
```cs
var ids = new[] { 1, 2, 3, 4, 5, 6 };
var query = from t in table
where ids.Where(i => i < 3).GroupBy(i => i).Select(i => …
```
> Introduced expanding expression. Fixed problem with local function evaluation.

- Source/LinqToDB/Data/DataConnection.cs
Fix for #1354. 
Added code for synchronizing already created Command object with DataConnection's CommandTimeout property.
> Fix for #1354. Synchronizing CommandTimeout properties.

- Data/Create Scripts/SqlServer.sql
- Source/LinqToDB.Templates/LinqToDB.SqlServer.ttinclude
- Source/LinqToDB.Templates/T4Model.ttinclude
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSchemaProvider.cs
- Tests/Linq/DataProvider/SqlServerTests.cs
Fixes #1144
- moved generic arguments list in T4 model from Name to separate GenericArguments field for Method and Class
- fixed double column selection when column used in index with desctiption on both column and index
> Issue 1144 fixes

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSchemaProvider.cs
npgsql 4.0 changed type of schema column ProviderType to enum: https://github.com/npgsql/npgsql/commit/0d1af7ef87be4962bd5889cf9037ae3c7fee77d2#diff-922404367f708ad04718b3837fa6168dR1192
switching to DataType schema column, which still contains same value as npgsql 3.x
> [postgresql] Fix schema provider for postgresql when used with npgsql 4.x

- NuGet/linq2db.Sybase.DataAction.nuspec
- Tests/Linq/Tests.csproj
Updated Sybase DataAction provider dependency to recently released v0.13
It contains remaining fixes for issues we reported and makes all our sybase.managed tests green.
> Bump DataAction provider dependency

- NuGet/DB2/LinqToDB.DB2.Tools.ttinclude
- NuGet/Informix/LinqToDB.Informix.Tools.ttinclude
- NuGet/SapHana/LinqToDB.SapHana.Tools.ttinclude
- NuGet/SqlCe/LinqToDB.SqlCe.Tools.ttinclude
- NuGet/Sybase/LinqToDB.Sybase.Tools.ttinclude
- NuGet/linq2db.DB2.nuspec
- NuGet/linq2db.Informix.nuspec
- NuGet/linq2db.SqlCe.nuspec
- NuGet/linq2db.Sybase.nuspec
- Source/LinqToDB.Templates/LinqToDB.DB2.ttinclude
- Source/LinqToDB.Templates/LinqToDB.Informix.ttinclude
- Source/LinqToDB.Templates/LinqToDB.SapHana.ttinclude
- Source/LinqToDB.Templates/LinqToDB.SqlCe.ttinclude
- Source/LinqToDB/DataProvider/DB2/DB2DataProvider.cs
- Source/LinqToDB/DataProvider/DynamicDataProviderBase.cs
- Source/LinqToDB/DataProvider/Informix/InformixDataProvider.cs
- Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaDataProvider.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeDataProvider.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseDataProvider.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/TestsInitialization.cs
- Tests/Tests.Playground/Tests.Playground.csproj
Fixes #1385
Note that it is supported only for desktop framework for now, because we don't build netcoreapp2.1/netstandard2.1 targets yet.
> Better DbProviderFactories support

- Build/AppVeyor.FixVersionNugets.ps1
- NuGet/PackLocal.cmd
- NuGet/linq2db.Access.nuspec
- NuGet/linq2db.DB2.nuspec
- NuGet/linq2db.Firebird.nuspec
- NuGet/linq2db.Informix.nuspec
- NuGet/linq2db.MySql.nuspec
- NuGet/linq2db.Oracle.Managed.nuspec
- NuGet/linq2db.Oracle.Unmanaged.nuspec
- NuGet/linq2db.PostgreSQL.nuspec
- NuGet/linq2db.SQLite.MS.nuspec
- NuGet/linq2db.SQLite.nuspec
- NuGet/linq2db.SapHana.nuspec
- NuGet/linq2db.SqlCe.nuspec
- NuGet/linq2db.SqlServer.nuspec
- NuGet/linq2db.Sybase.DataAction.nuspec
- NuGet/linq2db.Sybase.nuspec
- NuGet/linq2db.nuspec
- NuGet/linq2db.t4models.nuspec
Fix #1414 
- add release notes link to all packages
- add repository link to all packages
- add copyright to all packages
- generate various copy-pasted fields during publish
- update nuget.exe client to recent version
- add PackLocal.cmd to build nugets locally with nuspec update (no more nuspec manual version patching for each release)
> Nuget metadata update

- Source/LinqToDB/DataProvider/Access/AccessMappingSchema.cs
- Source/LinqToDB/DataProvider/DB2/DB2SqlBuilderBase.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Source/LinqToDB/DataProvider/Informix/InformixSqlBuilder.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
- Source/LinqToDB/DataProvider/Oracle/OracleMappingSchema.cs
- Source/LinqToDB/DataProvider/Oracle/OracleSqlBuilder.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLMappingSchema.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaSqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeMappingSchema.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeSqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerMappingSchema.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseSqlBuilder.cs
- Source/LinqToDB/Linq/QueryRunner.Delete.cs
- Source/LinqToDB/Linq/QueryRunner.Insert.cs
- Source/LinqToDB/Linq/QueryRunner.InsertOrReplace.cs
- Source/LinqToDB/Linq/QueryRunner.InsertWithIdentity.cs
- Source/LinqToDB/Linq/QueryRunner.Update.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlQuery/SqlTable.cs
- Tests/Base/Tools/ComparerBuilder.cs
- Tests/Base/Tools/EnumerableEqualityComparer.cs
- Tests/Linq/Tests.csproj
- Tests/Linq/Update/CreateTableTypesTests.cs
Summary of changes:
- Access: added missing mapping configuration for DateTime? type
- Firebird: added default boolean type support as CHAR for CreateTable
- Oracle: added missing mapping configuration for Guid? type
- Postgresql: changed mapping of string type from DataType.Unknown to DataType.NVarChar (fixes #1394)
- SQLCE/SQLServer: added missing mapping configuration for System.Data.SqlTypes.Sql* nullable struct types
- Query.CleanCaches() will also clean caches for IDataContext non-linq extension methods: Insert, Delete, InsertOrReplace, InsertWithIdentity, Update and their variations
- SAP HANA/SQL Server: properly generate (MAX) type specifier for varbinary/varchar/nvarchar types when length is not specified or outside of allowed range
- added IEnumerable-based properties …
> CreateTable improvements

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
`_npgsqlTypeMap` don't contains `varchar varying` type. 
So I've replace it by `character varying`, that exists [there](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs#L155) (and [in PostgreSQL docs](https://www.postgresql.org/docs/11/datatype-character.html)). Also I've added some additional check (for `character varying` with specified length).
> Fix postgresql provider "character varying" type bug

- Source/LinqToDB/LinqExtensions.cs
Added missing IQueryable<T> conversion points.
It is needed for `EF Core Integration` because Remotion Linq is trying to analyse expressions even before final parsing.
Related to https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/13
> Added missing conversion points for IQueryable<T> extensions.

- Data/Create Scripts/SqlServer.sql
- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Tests/T4.Linq/SqlServer.tt
- Fix #1479 - generate non-extension methods for procedures in nested schema classes
- fix association extension methods generation
- fix duplicate member names generated in TableExtensions
> Fix some T4 issues

- Source/LinqToDB/Mapping/MappingSchema.cs
- Source/LinqToDB/Mapping/MappingSchemaInfo.cs
Nothing fancy, just fixes two or three typos.
> [DO NOT MERGE BEFORE 3.0] Fix typo in MappingSchema and MappingSchemaInfo

- Source/LinqToDB.Templates/LinqToDB.ttinclude
Fix #1490
Because right now we don't have enough information in our code-generation model, we just need to ignore those methods during duplicates rename stage.
> [T4] Don't rename Find method

- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/Data/DataConnection.cs
- Tests/Base/TestBase.cs
- Tests/Linq/UserTests/Issue1486Tests.cs
Fix #1486
Improves support for AllowMultipleQuery in conjunction with external connection creation:
- added copy connection string from connection during DataConnection clonning. Fixes AllowMultipleQuery support for SqlCe and Sqlite.ms when parent DataConnection initialized with explicit connection
- added DataConnection constructors that take `Func<IDbConnection>` connection factory method. Fixes AllowMultipleQuery support for MySqlConnector, SAP, Oracle (native and managed) when parent DataConnection initialized with connection factory
> Connection factory support by DataConnection and better DataConnection cloning

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.AssociatedTableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/LinqExtensions.cs
- Source/LinqToDB/Mapping/EntityMappingBuilder.cs
- Source/LinqToDB/Mapping/PropertyMappingBuilder.cs
- Tests/Linq/UserTests/Issue1498Tests.cs
Fix #1498, fix #1499
- add missing fluent mapping Association method override for IEnumerable<T> property with key selectors
- add missing Association overrides to PropertyMappingBuilder
- add canbeNull parameter to existing Association method of PropertyMappingBuilder
> [WIP] Expression-based associations support for multiple queries

- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Tests/Linq/Linq/AssociationTests.cs
Adds missing primary key request build to SelectContext
Fixes following exception:
```
The method or operation is not implemented:
at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags) in c:\GitHub\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 593
at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in c:\GitHub\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 433
at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\GitHub\linq2db\Source\LinqToDB\Linq\Builder\SubQueryContext.cs:line 39
at LinqToDB.Linq.Builder.SelectManyBuilder.SelectManyContext.ConvertToSql(Expression expression, …
```
> test and fix for SelectContext

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
#1576
#1579
Provider: Postgres
Replace **currval -> returning id**
```sql
BeforeExecute
-- testdbDB PostgreSQL.9.5 PostgreSQL
DECLARE @Q Bigint -- Int64
SET     @Q = 10
INSERT INTO "public".test
(
q
)
VALUES
(
:Q
)
RETURNING
id
```
```csharp
var key = await db.InsertWithInt64IdentityAsync(new DataModels.Test { Q = 10});
```
> currval -> returning id

- Source/LinqToDB/Common/DbDataType.cs
- Source/LinqToDB/Data/CommandInfo.cs
- Source/LinqToDB/Data/DataConnection.QueryRunner.cs
- Source/LinqToDB/DataProvider/BasicMerge.cs
- Source/LinqToDB/DataProvider/BasicMergeBuilder.cs
- Source/LinqToDB/DataProvider/BulkCopyReader.cs
- Source/LinqToDB/DataProvider/Informix/InformixMergeBuilder.cs
- Source/LinqToDB/DataProvider/MultipleRowsHelper.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerDataProvider.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerMergeBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/TakeSkipBuilder.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/Linq/QueryRunner.InsertOrReplace.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Source/LinqToDB/Mapping/ColumnDescriptor.cs
- Source/LinqToDB/Mapping/MappingSchema.cs
- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/SqlParameter.cs
- Source/LinqToDB/SqlQuery/SqlTable.cs
- Tests/Base/SqlServerDataSourcesAttribute.cs
- Tests/Linq/Linq/ParameterTests.SqlServer.cs
- Tests/Linq/Linq/ParameterTests.cs
Fixes #1578 
This pr:
- adds length information to DbDataType object and pass it around
- [MSSQL] fixes varbinary parameter size for query to better hit sql query plan cache on subsequential calls with variable-sized parameters
[MSSQL] varbinary, varchar, nvarchar parameter sizing logic is following with this PR:
- if parameter used against column with length set in mapping and both column length and value length do not exceed max supported length (4000/8000 based on type) - use length from mapping
- otherwise if parameter value length does not exceed max supported length (4000/8000 based on type) - use max supported length
- otherwise use unsized parameter
Some details on how parameter size is important for sql server:
https://blogs.msdn.microsoft.com/psssql/2010/10/05/query-performance-a …
> Parameter size support improvements

- Data/Create Scripts/SapHana.sql
- Source/LinqToDB/DataProvider/SapHana/SapHanaDataProvider.cs
- Tests/Linq/DataProvider/SapHanaTests.cs
- Tests/Linq/Linq/CalculatedColumnTests.cs
- Tests/Linq/Linq/CountTests.cs
- Tests/Linq/Linq/DynamicColumnsTests.cs
- Tests/Linq/Linq/EnumMappingTests.cs
- Tests/Linq/Linq/ExpressionsTests.cs
- Tests/Linq/Linq/IssueTests.cs
- Tests/Linq/Linq/SelectTests.cs
- Tests/Linq/Linq/StringFunctionTests.cs
- Tests/Linq/Update/TruncateTableTests.cs
- Tests/Linq/UserTests/Issue569Tests.cs
SAP HANA fails to report proper value for column AllowDBNull property for some queries and linq2db fails with `HanaException : Data is Null. This method or property cannot be called on Null values.`
Also removed couple of fixed ActiveIssue attributes
> fix issue with mapperexpression nullable columns in SAP HANA

- Source/LinqToDB/Sql/Sql.DateTime.cs
- Tests/Linq/Linq/DateTimeFunctionsTests.cs
fix #1688
for SQLite:
DateTime(...)  equivalent  strftime('%Y-%m-%d %H:%M:%S', ...) but we need use %f format to get milliseconds.
> Add DateDiff implementation and fix AddDate for SQLite

- Source/LinqToDB/DataProvider/DB2/DB2DataProvider.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdDataProvider.cs
- Source/LinqToDB/DataProvider/Informix/InformixDataProvider.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteDataProvider.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaDataProvider.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeDataProvider.cs
- Tests/Linq/TestProviders/Npgsql4PostgreSQLDataProvider.cs
We store custom parameter setters in static variable,
Having them as static doesn't give us anything, because each new instance of provider instance always overrides them.
From other side having them static leads to issues when different providers used for same database. E.g. we already removed statics for this reason from sybase provider. Now it gives issues when we run tests with both npgsql3/npgsql4 providers.
> Get rid of static provider parameter setters

- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/Data/DataConnection.cs
- Source/LinqToDB/Data/DbCommandProcessor/DbCommandDefaultProcessor.cs
- Source/LinqToDB/Data/DbCommandProcessor/DbCommandProcessorExtensions.cs
- Source/LinqToDB/Data/DbCommandProcessor/IDbCommandProcessor.cs
- Source/LinqToDB/Data/RetryPolicy/RetryingDbCommand.cs
Extension point adds possibility to change implementation of `DbCommand` methods `ExecuteScalar`, `ExecuteNonQuery`, `ExecureReader` and their Async equivalents.
One of possible use cases: put commands into queue and initiate them in special separate thread, to overcome lock contention in `TimerQueue.Timer`
See: https://github.com/avtc/timer.noLock
> Extension point adds possibility to change implementation of DbCommand methods ExecuteScalar, ExecuteNonQuery, ExecureReader

- Source/LinqToDB/DataProvider/SqlServer/SqlServer2008SqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
- Tests/Linq/UserTests/Issue1721Tests.cs
DateTime2 type first available in MS SQL 2008.  Added override to `SqlServer2008SqlBuilder` to correctly generate type string for DateTime2 with Precision.
Test add but not tested, fix confirmed in external program.  Please check this test.
> Fix #1721 - CreateTable generation for DateTime2 with Precision.

- Build/linq2db.Source.props
- NuGet/linq2db.Tools.nuspec
- NuGet/linq2db.nuspec
- Source/LinqToDB/LinqToDB.csproj
Fix #1704
- move nuget dependencies back to linq2db project (linq2db.tools will get them as transient dependencies from linq2db)
- remove `System.Data.Common` dependency
- update multiple outdated nuspec dependencies (including system.data.sqlclient)
Incident summary: we shouldn't forget to update nuspec files when we bump dependencies for released products
> Fix nuget dependencies

- Source/LinqToDB/Data/DataConnectionExtensions.cs
Update xml documentation on `ExecuteProc*` methods to clarify that sql parameter must be properly escaped by user. See #1740 for details
> update ExecuteProc* extensions documentation on sql parameter

- Source/LinqToDB/Expressions/Extensions.cs
- Source/LinqToDB/Expressions/MappingExpressionsExtensions.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Mapping/AssociationDescriptor.cs
- Source/LinqToDB/Mapping/DynamicColumnAccessorAttribute.cs
- Source/LinqToDB/Mapping/DynamicColumnsStoreAttribute.cs
- Source/LinqToDB/Mapping/EntityDescriptor.cs
- Source/LinqToDB/Mapping/EntityMappingBuilder.cs
- Source/LinqToDB/Mapping/IConfigurationProvider.cs
- Source/LinqToDB/Mapping/MappingSchema.cs
- Source/LinqToDB/Reflection/MemberAccessor.cs
- Source/LinqToDB/Reflection/TypeAccessor.cs
- Source/LinqToDB/Reflection/TypeAccessorT.cs
- Tests/Linq/Mapping/DynamicStoreTests.cs
- Tests/Linq/Mapping/FluentDynamicMappingTests.cs
- Tests/Linq/Tests.csproj
Fix #1521, fix #1477
- respect `DynamicColumnsStoreAttribute.Configuration` property (before it was using first dictionary with such attribute)
- allow custom storage setter/getter methods using `DynamicColumnAccessorAttribute` mapping entity attribute instead of dictionary
- fluent mapper: new method `DynamicColumnsStore` to configure store dictionary
- fluent mapper: new method `DynamicPropertyAccessors` to configure store getters/setters
- fix type accessor to use current mapping schema instead of default for default values
> Dynamic store configuration improvements

- Source/LinqToDB/Data/CommandInfo.cs
- Source/LinqToDB/Data/DataConnection.QueryRunner.cs
- Source/LinqToDB/Data/DataConnection.cs
- Source/LinqToDB/DataProvider/DB2/DB2DataProvider.cs
- Source/LinqToDB/DataProvider/DataProviderBase.cs
- Source/LinqToDB/DataProvider/IDataProvider.cs
- Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaOdbcDataProvider.cs
- Tests/Linq/DataProvider/ExpressionTests.cs
- Tests/Linq/DataProvider/OracleTests.cs
- Tests/Linq/Linq/DynamicColumnsTests.cs
- Tests/Linq/Update/CreateTableTests.cs
- Tests/Linq/Update/DeleteTests.cs
- Tests/Linq/Update/DropTableTests.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/Update/MergeTests.CommandValidation.cs
- Tests/Linq/Update/TruncateTableTests.cs
- Tests/Linq/Update/UpdateTests.cs
- Tests/Linq/UserTests/Issue1222Tests.cs
- Tests/Linq/UserTests/Issue1279Tests.cs
- Tests/Linq/UserTests/Issue1438Tests.cs
- Tests/Linq/UserTests/Issue564Tests.cs
Set BindByName property only for commands with parameters for native provider to workaround issue when :NEW token treated by provider as parameter
> Fix creation of table with identity trigger for oracle native provider

- Source/LinqToDB/DataProvider/Sybase/SybaseDataProvider.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseMappingSchema.cs
- Tests/Linq/DataProvider/SybaseTests.cs
Fix #1707
- apply date part adjustment on data read only to DateTime values of db type 'time'
- update 'time' literal generation for negative TimeSpan to match behavior for parameters. From now negative interval literal will generate value, corresponding to `1 day - interval time part`. E.g. `-1 hour` interval with result in 23:00 time value (same for `-x days 1 hour`, as day part is ignored)
> Fix Sybase time datetime and type handling issues

- Source/LinqToDB/Linq/Builder/AllJoinsBuilder.cs
- Source/LinqToDB/Linq/Builder/AllJoinsLinqBuilder.cs
- Source/LinqToDB/Linq/Builder/DefaultIfEmptyBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectManyBuilder.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/JoinTests.cs
- Tests/Linq/Linq/SelectTests.cs
- Tests/Linq/UserTests/Issue820Tests.cs
Fix #1773
Fixes:
- selection of null record as null for left/right/full join nullable side for all Join*() API
- full join left side subquery optimization
> Fix left/right/full outer join() null record mapping

- Source/LinqToDB.Templates/DataModel.ttinclude
- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Source/LinqToDB.Templates/README.md
- Source/LinqToDB/DataProvider/Firebird/FirebirdSchemaProvider.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaSchemaProvider.cs
- Tests/T4.Linq/Firebird.generated.cs
- Tests/T4.Linq/Firebird.tt
- Tests/T4.Linq/Firebird3.generated.cs
- Tests/T4.Linq/Firebird3.tt
- Tests/T4.Linq/SapHana.generated.cs
Fix #1656
- adds new T4 option `bool PrefixTableMappingForDefaultSchema = false` to enable table mapping class prefixing with schema name for default schema too. Works only if following options also set to specified values:  `IncludeDefaultSchema = true && GenerateSchemaAsType = false && PrefixTableMappingWithSchema = true`
- fixed SchemaName field population for Firebird. Set `IncludeDefaultSchema = false`, if you don't want it to start generate `Schema` mapping properties.
> Add PrefixTableMappingForDefaultSchema T4 option

- Source/LinqToDB/Sql/Sql.Analytic.cs
- Tests/Base/TestProvName.cs
- Tests/Linq/Linq/AnalyticTests.cs
> improve RESPECT NULLS window function token support across databases

- Source/LinqToDB/DataExtensions.cs
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/Linq/Builder/SelectQueryBuilder.cs
- Tests/Linq/Linq/SelectQueryTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
It is possible now to inject into LINQ query single custom recordset via
```cs
db.SelectQuery(() => new { value1 = 1, Value2 = 2 })
```
> Implemented support of Single custom record in query - SelectQuery

- Source/LinqToDB/Sql/Sql.DateTime.cs
- Source/LinqToDB/SqlQuery/Precedence.cs
- Tests/Linq/Linq/DateTimeFunctionsTests.cs
Fixed incorrect precedence applied to dateadd expressions if interval is also expression.
Fixes DB2, Oracle, SQLite and PostgreSQL
> Fix dateadd SQL precedence issues for some providers

- Source/LinqToDB.Templates/README.md
- Source/LinqToDB/DataProvider/Access/AccessSchemaProvider.cs
- Source/LinqToDB/SchemaProvider/GetSchemaOptions.cs
- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
This change required to implement workaround for https://github.com/linq2db/linq2db.LINQPad/issues/23 where JET engine crashes with AV when we try to load foreign key information
> [schema] add option to disable FK schema information load

- Source/LinqToDB/DataContext.cs
Found during EF Core integration update.
> Added missed MappingSchema initialization for DataContext's DataConnection.

- Data/Create Scripts/Oracle.sql
- Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs
- Source/LinqToDB/DataType.cs
- Tests/Linq/DataProvider/OracleTests.cs
> Fix for #1927. Implemented support of LONG and LONG RAW datatypes in Oracle.

- Source/LinqToDB/DataExtensions.cs
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Expressions/SqlQueryDependentAttribute.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/SetOperationBuilder.cs
- Source/LinqToDB/Linq/Query.cs
- Tests/Linq/Linq/TestQueryCache.cs
> The more you know, the more you can fix :)
Fixed wrong algorithm with handling `SqlQueryDependentAttrinute`. For now in cache we store original values which were used in building query. It gives possibility to correctly handle query cache problems.
Fixes #1928
> Fix for #1928. Fixed wrong algorithm for handling SqlQueryDependentAttribute.

- Source/LinqToDB/Linq/Builder/TableBuilder.AssociatedTableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/UserTests/Issue1965Tests.cs
Fixes #1965
Looks like we have to find time to review this functionality in 3.X
> Fix for #1965. Redirecting to specific association context methods.

- Source/LinqToDB/Sql/Sql.Strings.cs
- Tests/Linq/UserTests/Issue1977Tests.cs
Fix #1977
Quite interesting issue - function was working correctly with existing tests due to two bugs negate each other:
- incorrect position passed to substring
- use of separator, for which mssql LEN produce incorrect (I insist!) result
> Fix Sql.ConcatString for MSSQL 2016-

- Source/LinqToDB/DataProvider/SqlServer/SqlServer2012SqlOptimizer.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Tests/Linq/Linq/ParameterTests.cs
- add tests with fix
- also fixed sql server remote context regression, introduced by  #1985
Also tests found another parameter evaluation issue. Created test without fix
> Fix support for pre-evaluated IQueryable sources with nested lambdas in queries

- Source/LinqToDB/DataContext.cs
- Tests/Linq/Linq/DataContextTests.cs
> Fix for #2047. Added CommandTimeout property for DataContext class.

- Source/LinqToDB/DataProvider/MySql/MySqlDataProvider.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
- Tests/Linq/DataProvider/MySqlTests.cs
Fix #1206, fix #2020 
This PR address issues with CreateTable API for MySQL by adding support for most of MySQL types.
Also fixes TIMESPAN values read into DateTimeOffset for MySqlConnector provider (MySql.Data provider is broken heavily here, will look into it on request)
Changes:
- DataType.VarChar/DataType.NVarChar generate VARCHAR type. Was: Char
- Guid generates CHAR(36) type. Was: Guid (invalid type name).
- DataType.Binary/VarBinary default length set to 255. Was: Binary, VarBinary (invalid type name)
- DataType.Blob/Text/NText generate corresponding subtypes based on length: TINY-/MEDIUM-/LONG- BLOB/TEXT.
- DataType.DateTime/DateTime2/SmallDateTime generates fractional seconds if precision specified. Was: no fractional size (=0)
- DataType.DateTimeOffset generates TIMESPAN type. …
> MySql CreateTable and DateTimeOffset improvements

- Source/LinqToDB/DataProvider/DB2/DB2Tools.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/Linq/QueryRunner.cs
Removed uses of `ConcurrentBag<T>`, which (due to use of `ThreadLocal<T>`) doesn't work well with some debugger configurations (see #2064, #1795)
This alone will fix debugger issue, but I plan to see if we can improve related caching functionality.
> Fix debugger failures on some configurations

- Source/LinqToDB.Templates/LinqToDB.PostgreSQL.ttinclude
- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Tests/T4.Linq/PostgreSQL.generated.cs
- Tests/T4.Linq/PostgreSQL.tt
- Tests/T4.Linq/SqlServer.generated.cs
- Tests/T4.Linq/SqlServer.tt
Fix #2049
Also marks `InitMappingSchema` implementation as protected for PostgreSQL instead of partial if constructors disabled (we don't generate this method implementation for other providers).
> [T4] Don't generate partial Init* methods if constructors generation disabled

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/Linq/ConvertTests.cs
- Tests/Linq/Linq/EnumMappingTests.cs
Fix #2039
Another case of #2041. Compiler adds unnecessary converts for byte, sbyte and ushort values comparisons.
> Remove redundant converts, inserted by compiler

- Build/Azure/README.md
- Build/linq2db.Tests.Providers.props
- NuGet/linq2db.Firebird.nuspec
- NuGet/linq2db.MySql.nuspec
- NuGet/linq2db.MySqlConnector.nuspec
- NuGet/linq2db.PostgreSQL.nuspec
- NuGet/linq2db.SQLite.MS.nuspec
- NuGet/linq2db.SqlServer.MS.nuspec
- NuGet/linq2db.Sybase.DataAction.nuspec
- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
- Tests/Base/Tests.Base.csproj
- Tests/FSharp/Tests.FSharp.fsproj
- Tests/Tests.Android/Tests.Android.csproj
- Tests/Tests.Android/packages.config
- Tests/Tests.T4/Tests.T4.csproj
Infra:
- [NUnit3TestAdapter](https://www.nuget.org/packages/NUnit3TestAdapter) 3.15.1 -> 3.16.1
- [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk) 16.4.0 -> 16.5.0
- [Humanizer.Core](https://www.nuget.org/packages/Humanizer.Core) 2.7.2 -> 2.7.9
Providers:
- [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient) 4.8.0 -> 4.8.1
- [AdoNetCore.AseClient](https://www.nuget.org/packages/AdoNetCore.AseClient) 0.16.0 -> 0.17.0
- [FirebirdSql.Data.FirebirdClient](https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient) 7.1.1 -> 7.5.0
- [MySql.Data](https://www.nuget.org/packages/MySql.Data) 8.0.18 -> 8.0.19
- [Npgsql](https://www.nuget.org/packages/Npgsql) 4.1.2 -> 4.1.3.1
- [MySqlConnector](https://www.nuget.org/packages/MySqlConnector) …
> Update nuget dependencies

- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
Cherry-picked change from 3.0 as [this](https://github.com/dotnet/runtime/issues/509) API change could became an issue for T4/Schema API users
> Add handling of empty schema tables for procedures

- Source/LinqToDB.Tools/EntityServices/EntityMap.cs
- Source/LinqToDB/Common/ConvertBuilder.cs
- Source/LinqToDB/Data/CommandInfo.cs
- Source/LinqToDB/DataProvider/DB2/DB2ProviderAdapter.cs
- Source/LinqToDB/DataProvider/Informix/InformixProviderAdapter.cs
- Source/LinqToDB/DataProvider/Oracle/OracleProviderAdapter.cs
- Source/LinqToDB/DataProvider/PostgreSQL/NpgsqlProviderAdapter.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerTypes.cs
- Source/LinqToDB/Expressions/ExpressionHelper.cs
- Source/LinqToDB/Expressions/Extensions.cs
- Source/LinqToDB/Expressions/TypeMapper.cs
- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Source/LinqToDB/Linq/Builder/SetOperationBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.AssociatedTableContext.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Source/LinqToDB/Mapping/ColumnDescriptor.cs
- Source/LinqToDB/Mapping/MappingSchema.cs
- Source/LinqToDB/Reflection/MemberAccessor.cs
- Source/LinqToDB/ServiceModel/DataService.cs
- Source/LinqToDB/TempTable.cs
- Tests/Linq/Mapping/MappingAmbiguityTests.cs
Enforce case-sensitivity for member mapping to avoid exceptions, when case-insensitive member search creates ambiguety.
Fixes issue with Merge failing, when mapped type has fields or properties with names differ only by case.
> Make by-name member mapping case-sensitive

- Source/LinqToDB/Data/DataConnection.Linq.cs
- Source/LinqToDB/Data/DataConnection.cs
- Tests/Linq/Data/DataConnectionTests.cs
- Copy `OnEntityCreated` delegate on `DataConnection` clone. Fixes #2169
- added tests, related to #962 and `DataConnection._disposeConnection` flag
List of candidates for cloning support:
> Improve DataConnection cloning

- Source/LinqToDB/DataContext.cs
- Tests/Linq/Linq/DataContextTests.cs
Fixes #2146 
Add `protected virtual` methods to `DataContext`:
```cs
protected virtual DataConnection CreateDataConnection();
protected virtual DataConnection CloneDataConnection(
DataConnection      currentConnection,
IAsyncDbTransaction dbTransaction,
IAsyncDbConnection  dbConnection);
```
> Make it possible to override DataConnection creation in DataContext

- Build/linq2db.Default.props
- CODE_OF_CONDUCT.md
- Data/Create Scripts/Oracle.sql
- README.md
- Source/LinqToDB/Common/ConvertUtils.cs
- Source/LinqToDB/Data/DataConnection.Linq.cs
- Source/LinqToDB/Data/DataConnection.cs
- Source/LinqToDB/DataContext.cs
- Source/LinqToDB/DataProvider/Oracle/OracleSchemaProvider.cs
- Source/LinqToDB/Linq/Builder/AsSubQueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/LinqExtensions.cs
- Tests/Linq/Data/DataConnectionTests.cs
- Tests/Linq/Linq/ConvertExpressionTests.cs
- Tests/Linq/Linq/DataContextTests.cs
- Tests/Linq/Linq/OptimizerTests.cs
- Tests/Tests.Playground/Tests.Playground.csproj
- appveyor.yml
- run tests
We plan this release as last one in v2 branch with 3.0.0 as next non-preview release.
After this release we will replace `master` branch content with v3 code and archive v2 to separate branch.
@linq2db/testers we plan to release on thursday (16/04)
[release notes](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#release-298)
> Release 2.9.8

- Build/Azure/README.md
- Build/Azure/pipelines/default.yml
- Build/linq2db.Tests.Providers.props
- NuGet/linq2db.MySql.nuspec
- NuGet/linq2db.MySqlConnector.nuspec
- NuGet/linq2db.Oracle.Managed.nuspec
- Tests/Tests.T4/Tests.T4.csproj
- set next release version to 3.0.0-rc.0
- updated: [Oracle.ManagedDataAccess.Core](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core) 2.19.60 -> 2.19.70
- updated: [Humanizer.Core](https://www.nuget.org/packages/Humanizer.Core) 2.8.2 -> 2.8.11
- updated: [MySql.Data](https://www.nuget.org/packages/MySql.Data) 8.0.19 -> 8.0.20
- updated: [MySqlConnector](https://www.nuget.org/packages/MySqlConnector) 0.64.1 -> 0.66.0
> fix next release version name, update dependencies

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.CteTableContext.cs
- Tests/Linq/Linq/CursorPagination.cs
Fixed found unexpected CTE duplication, possible fix for #2201
Introduced dynamic query generation sample based on ANY IQueryable.
**Pagination sample:**				
```cs
// sample query with filter
var dataQuery = table
.Where(t => t.ServiceDate > Sql.CurrentTimestamp.AddDays(-2));
// ordered query
var query = dataQuery
.OrderByDescending(t => t.ServiceDate)
.ThenByDescending(tt => tt.BookingID);
// getting first page result with total count
var pageResult = Paginator.GetPageViaCursor(query, b => b.BookingID, (int?)null, take, true);
```
First query result retrieves all needed data for continuous pagination:
```sql
DECLARE @take BigInt -- Int64
SET     @take = 12
SELECT
[q].[c1],
[q].[RowNumber],
[q].[BookingID],
[q].[ServiceDate],
[q].[Value_1]
FROM
(
SELECT
ROW_NUMBER() OVER(ORDER BY …
```
> Fixed found unexpected CTE duplication. Added sample for cursor based pagination.

- Source/LinqToDB.Templates/LinqToDB.SqlServer.ttinclude
I have noticed a typo, where parameters were passed to `string.Format` instead of `GetSqlServerConnection` method. I do not think there is an active issue for that.
> Fix SQL Server connection initialization for T4 template

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Base/TestBase.cs
- Tests/Linq/Linq/SelectTests.cs
> Fix for #2283. Added additional Expression types support for OuterApply queries.

- Data/Create Scripts/SqlServer2000.sql
- Source/LinqToDB/DataProvider/SqlServer/SqlServer2000SchemaProvider.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSchemaProvider.cs
- Source/LinqToDB/Sql/Sql.Strings.cs
- Tests/Base/TestUtils.cs
- Tests/Linq/Data/MiniProfilerTests.cs
- Tests/Linq/DataProvider/SqlServerTests.cs
- Tests/Linq/Linq/SetOperatorTests.cs
- Tests/Linq/Linq/SetTests.cs
- Tests/Linq/UserTests/Issue1303Tests.cs
- Tests/Linq/UserTests/Issue133Tests.cs
- Tests/Linq/UserTests/Issue2008Tests.cs
This fixes the following issues with testing for SQL Server 2000:
* `sys.sp_addextendedproperty` is named differently in SQL Server 2000 with different parameters.
* `sys.databases` should be accessed via `master.dbo.sysdatabases` and has different columns
* No `SCHEMA_NAME()` function
* `hierarchyid` user-defined type not supported in SQL Server 2000/2005
* User-defined types not supported in SQL Server 2000
* Cannot query `sys.databases` for collation setting (could perhaps query the `sysobjects` table)
* No `xml` data type
* `EXCEPT` not supported
* `INTERSECT` with WHERE clause not supported (it seems)
* Cannot search a binary field
* `OUTER APPLY` not supported
The only behavior change was to the `SqlServer2000SchemaProvider`, which now issues the proper query for the current …
> Updates for SQL Server 2000 testing

- Build/Azure/pipelines/default.yml
- Build/Azure/pipelines/experimental.yml
- Build/Azure/pipelines/test-all.yml
- Tests/Linq/Linq/ConvertTests.cs
- Tests/Linq/Linq/DateTimeFunctionsTests.cs
- Tests/Linq/TestsInitialization.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/Update/MergeTests.Types.cs
- Tests/Tests.T4/Databases/SapHana.generated.cs
- Tests/Tests.T4/Databases/SapHana.tt
Nothing interesting:
- removed hack needed for provider to load (SAP fixed it)
- disabled failing test as they break binary parameters
Looks like SAP guys still stick to their strategy as both issues are too trivial:
1. Unit-testing is not for "enterprise" development
2. If we don't have bugs, how can we sell support?
> Update SAP HANA tests to use latest provider

- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Tests/Linq/Linq/WhereTests.cs
With new IsTrue predicate we were skipping optimizations for ExprExpr simple cases.
> Fix RC2 regression with EXISTS function being wrapped in CASE/IIF

- Source/LinqToDB/Linq/ExpressionQuery.cs
- Tests/Linq/Linq/ExpandTests.cs
Problem that if you call `GetQuery(ref expression, true)` - better to remember corrected expression, otherwise parameters accessors will be broken.
> Fixes found problem with query caching.

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Mapping/ColumnAttribute.cs
- Source/LinqToDB/Mapping/ColumnDescriptor.cs
- Source/LinqToDB/Mapping/PropertyMappingBuilder.cs
- Source/LinqToDB/SqlQuery/SqlField.cs
- Tests/Linq/UserTests/SkipOnEntityFetchTests.cs
Implemented the `ColumnAttribute.SkipOnSelectAll` property.
This mapping property can be applied to columns that should not be fetched by default.
Main use case are tables with a long set of columns and in which some of them may impact performance if retrieved by default (e.g.: Blob / Clob / XMLs / etc). In these cases, such columns must be arbitrarily selected in Linq queries to be fetched if the SkipOnSelectAll = true.
> Skip on Select All

- Source/LinqToDB/TempTable.cs
- Tests/Linq/UserTests/Issue1721Tests.cs
See #1934 
This PR prevents a call of `CreateTempTable<int>(...)`.  Note that a generic constraint on `TempTable<T>` was not added due to conflicts elsewhere in the codebase.
> Add generic constraint of class type to CreateTempTable

- Source/LinqToDB/DataProvider/BasicBulkCopy.cs
- Source/LinqToDB/TempTable.cs
- Tests/Linq/Update/CreateTempTableTests.cs
This PR adds `CreateTempTableAsync<T>` overloads to `LinqToDB.DataExtensions`.
Notes:
* `TempTable<T>` now implements `IAsyncDisposable` for compatible frameworks
* Since constructors cannot be asynchronous, I have added `CreateAsync` static methods to `TempTable` to facilitate this.  Those static methods call a protected constructor to create the class after `CreateTableAsync` has been called.
* Some of the overloads include an _optional_ `action` that will run before the table is populated via a bulk copy operation.  This optional `action` parameter is now expected to be an asynchronous delegate.  If I were to add another overload for a synchronous action, the compiler would not be able to select which overload was intended to be used.  So I only included the asynchronous `action` …
> Add asynchronous overloads for CreateTempTable

- Data/Create Scripts/Oracle.sql
- Source/LinqToDB/DataProvider/Oracle/OracleSchemaProvider.cs
- Tests/Linq/DataProvider/OracleTests.cs
- Tests/Tests.T4/Databases/Oracle.generated.cs
Fix #2404
OracleSchemaProvider.GetTables
gives back Tables and Views AND Materialized Views NOW!
see also: https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_1105.htm#REFRN20139
why it differs between 
ALL_MVIEWS and  USER_MVIEWS?
it seems that materialized view comments are not in USER_TAB_COMMENTS, so the join kicks out the  USER_MVIEWS
but
materialized view seem to bee in ALL_TAB_COMMENTS, so this statement is simpler.
> Include Materialized Views in OracleSchemaProvider.GetTables

- Source/LinqToDB/TempTable.cs
- Tests/Linq/Update/CreateTempTableTests.cs
This PR does the following:
1. Adds cancellation tokens to all existing asynchronous CreateTempTable overloads, passing it both to the CreateTable function, and also to the optional `Copy` (bulk import) or `Insert` (from another table) operation.
2. If an exception occurs during the `Copy` / `Insert` phase, the temporary table is dropped from the database.  If an error occurs during the drop, it is ignored; the original exception is still thrown back onto the stack.  Applies to both synchronous and asynchronous operations.
> CreateTempTable cancellation token support and failure cleanup

- Data/Create Scripts/SqlServer.sql
- Source/LinqToDB/Data/CommandInfo.cs
- Source/LinqToDB/Data/DataConnectionExtensions.cs
- Source/LinqToDB/Data/DataReader.cs
- Source/LinqToDB/Data/DataReaderAsync.cs
- Tests/Linq/Data/ProcedureTests.cs
- add missing async overloads for stored procedure APIs. Fix #1501
- removed duplicate overloads in CommandInfo
- add parameter tests for all proc execution APIs and implement parameter rebind for `ExecuteProc<T>` and `QueryProcMultiple`. Fix #2361
> Stored Procedures: async API and parameters rebind fixes

- Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Tests/Linq/DataProvider/FirebirdTests.cs
Adds missing escaping of table aliases (column aliases already escaped) for firebird. Fix #2445
> [Firebird] Add escaping of table aliases

- Source/LinqToDB/Async/AsyncEnumeratorAsyncWrapper.cs
- Source/LinqToDB/Async/IAsyncEnumerable.cs
- Source/LinqToDB/Async/IQueryProviderAsync.cs
- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/ExpressionQuery.cs
- Source/LinqToDB/Linq/PersistentTableT.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/TempTable.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
- Tests/Linq/Update/MergeTests.ApiParametersValidation.cs
- fix support for eager load queries with IAsyncEnumerable. Fix #2442
- fix `IAsyncEnumerable<T>.GetAsyncEnumerator` signature for netfx targets
- fix async path for eager load to use async operations
> Fix IAsyncEnumerable support for Eager Load

- Source/LinqToDB/Extensions/ReflectionExtensions.cs
While working on another Library I noticed that calls `ReflectionExtensions.GetItemType` added up in certain cases (Mostly around `Insert<T>` and bulk copies.) With the benchmarks I'm running off a local branch I'm seeing some performance boosts for large series of individual writes.
> Add a ConcurrentDictionary cache to back ReflectionExtensions.GetItemType

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/UserTests/Issue2474Tests.cs
> Fix for #2474. Corrected Parent restoring when using ExpressionContext.

- Tests/Linq/DataProvider/SqlServerTests.cs
Just adds test for issue  #1468 and checks that new metadata load method doesn't fix it...
Looks like there is no way to make metadatga for  such procedures work. There are some manual workarounds, but they are not applicable for our case https://stackoverflow.com/questions/18346484
> Add test for #1468

- Source/LinqToDB/SqlQuery/ConvertVisitor.cs
All the predicate type conversion cases in ConvertVisitor allow a different type to be returned from the conversion implemented by the provider. FuncLike predicate does not follow this and attempts to cast the converted inner function expression to an SqlFunction. This of course will throw a cast exception when trying to replace the function expression with another valid expression.
This came up because the i Series has limitations on EXISTS predicates, so the EXISTS pseudo function needs to be replaced with a condition expression. This used to work in 2.x, but got broken in 3.x.
This patch attempts to identify the convert expression, and if it is a function expression uses it to rebuild the FuncLike predicate, otherwise if it is another predicate it simpy returns it. I added an …
> Allow different type of predicate when converting FuncLike in optimizer

- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/Data/DataConnection.QueryRunner.cs
- Source/LinqToDB/Data/DataConnection.cs
- Source/LinqToDB/Data/DataReader.cs
- Source/LinqToDB/Data/DataReaderAsync.cs
as if it fails it could hide exception from command execution (see #2507) and is not a good idea in general to do it for logging, as it interested only in command, associated with query, not in new one.
> Don't create new command instance for logging

- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/DataProvider/OracleTests.cs
Fix #2504 
Actually this is another reason to do #2502 - `SequenceNameAttribute` shouldn't exists in AST in first place and sequence should be attached to `SqlField`. But for now let's just fix issue.
> Remove not needed sequence configuration name check in sqltable

- Source/LinqToDB.Tools/Mapper/ExpressionBuilder.cs
- Source/LinqToDB/DataProvider/Access/AccessSqlBuilderBase.cs
- Source/LinqToDB/DataProvider/DB2/DB2LUWSchemaProvider.cs
- Source/LinqToDB/DataProvider/DB2/DB2SqlBuilderBase.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Source/LinqToDB/DataProvider/Informix/InformixSqlBuilder.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSqlBuilder.cs
- Source/LinqToDB/DataProvider/Oracle/Oracle11SqlBuilder.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteSqlBuilder.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaOdbcSqlBuilder.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaSqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeSqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServer2012SqlBuilder.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSchemaProvider.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSqlBuilder.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseSqlBuilder.cs
- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionTestGenerator.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.Merge.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/DataProvider/MySqlTests.cs
- Tests/Linq/Linq/ParameterTests.cs
Adds following sql builder properties.
```cs
protected virtual string InlineComma => ", ";
protected virtual string Comma => ",";
protected virtual string OpenParens => "(";
```
db2 implementation should override it like that:
```cs
protected override string Comma => ", ";
protected override string OpenParens => "( ";
```
There is no fix for `BuildSelectClause` change from #2536 as I don't see any pattern here. I recommend to override whole method as it very small one.
> Alternative fix for #2536

- Source/LinqToDB.Templates/LinqToDB.ttinclude
Fix #1586
This is my first open source PR, so please let me know if I did anything wrong.
To resolve issue 1586, which details how tables named "Relationship" would result in generated files with an ambiguous references to the `LinqToDB.Mapping.Relationship` enum, I have updated the generated parameter (which appears as an attribute in files generated from t4 templates) so that it is fully qualified, thus avoiding the ambiguity.
There is potential for a more sophisticated solution (such as a parameter in t4 templates that would fully qualify references), but:
1) I lack the familiarity with T4 templates
2) The solution is well beyond the scope of the reported issue
3) I don't know what other items might need to be fully qualified.
For that reason, I stuck with a simple solution with a low …
> ISSUE 1586 - WIP - Fully qualify Relationship mapping references to prevent table name conflict

- Source/LinqToDB.Templates/LinqToDB.ttinclude
Fixes #2168 
The issue is that `DataType` references in attributes would sometimes create ambiguous reference errors if there is a table named `DataType`. This ambiguous reference is already detected and prevented for field names; this fix expands that detection to include table names as well. When the condition is detected, `DataType` is fully qualified to `LinqToDB.DataType`.
> Issue 2168 - Modify T4 name conflict detection for data types to include table names instead of only column names

- Source/LinqToDB/DataProvider/Informix/InformixDataProvider.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Source/LinqToDB/Linq/Builder/OrderByBuilder.cs
- Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Tests/Linq/Linq/GroupByTests.cs
- Tests/Linq/UserTests/Issue2564Tests.cs
Added test to reproduce issue
```
Exception: Microsoft.Data.SqlClient.SqlException
Message  : Column 't1.c1' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
```
```sql
SELECT
Count(*)
FROM
(
SELECT
[t1].[c1] as [Key_1],
Count(*) as [Count_1]
FROM
(
SELECT
1 as [c1]
FROM
[Person] [_]
UNION ALL
SELECT
2 as [c1]
FROM
[Person] [_1]
) [t1]
-- GROUP BY WAS HERE
) [_2]
WHERE
[_2].[Count_1] > 1 AND [_2].[Key_1] = 1
```
> Non-table column excluded from sub-query group by (3.1.3 regression)

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLMappingSchema.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
Fix #2624
adds support for `ushort`, `uint` and `ulong` data in parameters in bulk copy
> [pgsql] fix unsigned integers mapping

- Tests/Base/Tools/SettingsReader.cs
Allows for a connecionstring enclosed in brackets to be translated as a reference to another connectionstring name. Due to the architecture of providers, a schema or non database related option has to spawn a different provider, so you might be able to reuse the same connection string to test different providers.
This is PR No.1 of a series related to help porting tests to 3rd party providers (like IBM i).
> [Tests] Support connection string pointers.

- Tests/Linq/SchemaProvider/SchemaProviderTests.cs
Some providers (like the IBM i ) support loading multiple schemas (libraries in IBM i) so the schema providers can load tables with the same name. This patch handles schema testing so that it looks for tables in the default schema, and fallsback to schema ignorant search in case the providers doesn't support default schema information.
This is PR No.2 of a series related to help porting tests to 3rd party providers (like IBM i).
> [Tests] multischema fix

- Tests/Linq/Data/DataExtensionsTests.cs
- Tests/Linq/Linq/AsyncTests.cs
A couple of tests stripped comments Access related comments before executing the SQL produced by the tracing mechanism when calling ToString on a query expression. To support more providers that can't handle inline comments in SQL, all comments were removed in said tests before the raw SQL is dispatched for execution.
This is PR No.3 of a series related to help porting tests to 3rd party providers (like IBM i).
> [Tests] Stripped all SQL trace comments from tests before execution

- Tests/Linq/Linq/DateTimeFunctionsTests.cs
Added support for IBM i week numbering scheme (day of year divided by 7) in related test (DatePartWeekNumberingType). 
This is PR No.4 of a series related to help porting tests to 3rd party providers (like IBM i).
> [Tests] Support for DB2 iSeries week numbering in tests.

- Tests/Base/InsertOrUpdateDataSourcesAttribute.cs
- Tests/Linq/Exceptions/DmlTests.cs
- Tests/Linq/Linq/ComplexTests2.cs
- Tests/Linq/Update/InsertTests.cs
- Tests/Linq/Update/MergeTests.cs
- Tests/Linq/UserTests/Issue1238Tests.cs
- Tests/Linq/UserTests/SkipValuesTestCache.cs
The default behaviour from the base DataProvider for InsertOrUpdate is to throw an unsupported exception. All of the embedded linq2db providers support it so there is no ability to skip those tests. This patch adds an attribute to control this for tests tha invoke the InsertOrUpdate / InsertOrReplace functions, similarly to Merge. The list of unsupported providers is empty by default.
This is PR No.5 of a series related to help porting tests to 3rd party providers (like IBM i).
> [Tests] Added sttribute to control Upsert tests on unsupported providers.

- Tests/Base/CustomizationSupport/CustomizationSupport.cs
- Tests/Base/CustomizationSupportInterceptor.cs
- Tests/Base/DataSourcesBaseAttribute.cs
- Tests/Base/TestBase.cs
This patch helps control which tests will run without editing the source code. It is critical for porting and maintaining the test code base for 3rd party providers.
It basicly providers a class with 3 overridable methods that by default do nothing, and a static class that provides a singleton instance of that class. If someone wants to port the tests to their own project they only have to:
1. Create a new subclass of the interceptor class
2. Switch the singleton instance of the default implementation (this is the only change needed in the original source code)
In this way, the developer can copy the tests over to their project, inject their own list of providers globally, and control which tests should not run, or should run with different filters on a test base. 
This is PR No.6 (and …
> [Tests] Customization interceptor

- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Tests/Linq/Linq/ExpressionsTests.cs
Added tests that throw exception due to call of `Nullable<T>` methods on `null` literal
```
TargetException : Non-static method requires a target.
RuntimeMethodInfo.CheckConsistency(Object target)
RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
RuntimePropertyInfo.GetValue(Object obj, Object[] index)
InternalExtensions.EvaluateExpression(Expression expr) line 1299
ExpressionBuilder.BuildConstant(Expression expr, ColumnDescriptor columnDescriptor) line 1346 …
```
> Incorrect null literal handling against Nullable<T> members in expression

- Source/LinqToDB/Metadata/SystemDataLinqAttributeReader.cs
Fixes #2692 
#
Copied 
```cs
IsPrimaryKey = c.IsPrimaryKey,
IsIdentity   = c.IsDbGenerated,
```
from donor `System.Data.Linq.Mapping.ColumnAttribute` object
> Improve ColumnAttribute parsing in SystemDataLinqAttributeReader

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/Linq/ExpressionsTests.cs
(not 3.2.0 regression)
generated sql miss null check:
```sql
SELECT
IIF(EXISTS(
SELECT
*
FROM
[Person] [p]
WHERE
[p].[PersonID] = CAST(N'SHOULD NOT BE CALLED' AS INT)
), 1, 0)
```
> Null check in expression method transaltion to SQL

- Source/LinqToDB/DataProvider/SqlServer/SqlServer2012SqlOptimizer.cs
- Tests/Linq/Linq/WhereTests.cs
Fails at least for SQL Server (will add list of dbs a bit later)
> Bad `IS NULL` predicate generation

- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/ConvertVisitor.cs
- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/GroupByTests.cs
- Tests/Linq/Linq/IdlTests.cs
count moved inside subquery, which produce incorrect results
```sql
SELECT
1,
Count(*)
FROM
[Person] [_]
WHERE
1 = 0
```
> Incorrect GROUP BY optimization when applied to subquery

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/Linq/ExpressionsTests.cs
```sql
SELECT
IIF(EXISTS(
SELECT
*
FROM
[Parent] [p]
WHERE
[p].[ParentID] = CAST(N'SHOULD NOT BE CALLED' AS INT)
), 1, 0)
```
> Null check from expression missing in query

- Source/LinqToDB/DataProvider/SapHana/SapHanaSqlBuilder.cs
Issue. SapHana.
With a large number of parallel insertWithIdentity into the same table, sometimes returned wrong identity. 
SELECT MAX(id) FROM table is not best way to get last identity at SapHana. Using CURRENT_IDENTITY_VALUE() is right way.
https://help.sap.com/viewer/7c78579ce9b14a669c1f3295b0d8ca16/Cloud/en-US/01e1a30aa542448da56da76233fea779.html
> Fix. Returning wrong identity at SapHana

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/Linq/Builder/OrderByBuilder.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Linq/OrderByTests.cs
not all providers support IN as predicate (list below)
also minor issue - contains result not selected, but re-evaluated on server
```sql
SELECT
[_].[PersonID],
[_].[LastName]
FROM
[Person] [_]
ORDER BY
[_].[PersonID] IN (1, 3)
```
Fails for:
- Firebird 2.5 (works in 3.0). Note that I'm working on versioning support for firebird so it makes sense to preserve 3.0 behavior (maybe commented for now)
- oracle (at least v11), need to test v12 on CI
- SAP HANA
- SQL Server
- SQL CE
- Sybase ASE
> Incorrest SQL generated for order by contains column

- .editorconfig
This PR sets `indent_size` to 4 for the linq2db repository by updating the `.editorconfig` file. With recent changes made to the GitHub online code viewer, the `indent_size` for C# (the tab size) now defaults to 8, and this might hurt the readability of the code in certain cases. E.g. without `indent_size=4` the code looks as such:
With `indent_size=4` it would look like this by default:
Thanks for making and maintaining the best ORM for .NET btw.
> chore: Set indent_size to 4 on GitHub

- Source/LinqToDB/Common/Configuration.cs
- Source/LinqToDB/Common/StringBuilderExtensions.cs
- Source/LinqToDB/DataProvider/Access/AccessMappingSchema.cs
- Source/LinqToDB/DataProvider/Access/AccessODBCSchemaProvider.cs
- Source/LinqToDB/DataProvider/DB2/DB2MappingSchema.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdMappingSchema.cs
- Source/LinqToDB/DataProvider/Informix/InformixMappingSchema.cs
- Source/LinqToDB/DataProvider/MySql/MySqlMappingSchema.cs
- Source/LinqToDB/DataProvider/Oracle/OracleMappingSchema.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLMappingSchema.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteMappingSchema.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaMappingSchema.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeMappingSchema.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerMappingSchema.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseMappingSchema.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
When profiling some benchmarks I noticed that there was a lot of traffic around `.ConvertBinaryToSql` (especially in bulk insert scenarios). 
I did some research and adapted [this](https://stackoverflow.com/a/24343727/2937845) into something that worked with StringBuilder.
Doing 'before/after' tests with this change show a pretty big improvement on paths where `.ConvertBinaryToSql` is called (with payloads in the 512b-1kb range, as much as 30% in a library benchmark against fast local IO)
> Lower allocations to improve ConvertBinaryToSql performance

- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Reflection/TypeAccessorT.cs
Fix #2680 
Note that this issue applies only to CoreRT runtime, enabled by `Compile with .NET Native tool chain` build option.
Implementation for this method were added to corert by [this](https://github.com/dotnet/corert/pull/8144) PR but it looks like it was never released and whole CoreRT stuff [looks like dead horse](https://github.com/dotnet/corert/issues/7200).
@Daveismus, I'm replacing GetInterfaceMap implementation with noop method, which means you cannot use interfaces in your data model (linq2db will not see them). Another option to make it work is to disable AOT buid for your project...
> Stub Type.GetInterfaceMap on CoreRT

- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Update/UpdateTests.cs
`SqlException : The multi-part identifier "a_Patient.LastName" could not be bound.`
```sql
DECLARE @id Int -- Int32
SET     @id = -1
UPDATE
[Person]
SET
[a_Patient].[LastName] = N'test'
FROM
[Person] [_]
LEFT JOIN (
SELECT
[a_Person].[LastName],
[t1].[PersonID]
FROM
[Patient] [t1]
LEFT JOIN [Person] [a_Person] ON [t1].[PersonID] = [a_Person].[PersonID]
) [a_Patient] ON [_].[PersonID] = [a_Patient].[PersonID]
WHERE
[_].[PersonID] = @id
```
> Association update query generates wrong SQL

- Source/LinqToDB/Linq/Builder/MergeBuilder.UpdateWhenMatched.cs
- Tests/Linq/Update/MergeTests.Operations.Combined.cs
- Tests/Linq/UserTests/Issue2560Tests.cs
- Tests/Linq/UserTests/Issue2856Tests.cs
> Merge: skip update operation without explicit setter for non-updateable entity

- Source/LinqToDB/Sql/Sql.Collate.cs
Without `[SqlQueryDependent] string collation,` Linq2DB will cache the first generation of the query and all further queries will use the same collation. This ensures that the correct SQL will be generated every time for different values of `collation`.
> Annotate Collate argument with SqlQueryDependent

- Source/LinqToDB/DataProvider/SqlServer/SqlServer2017SqlBuilder.cs
Supported since SQL Server 2016+ and within Azure SQL Database.
Not supported in Azure Synapse Analytics and Parallel Data Warehouse
See: https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-table-transact-sql?view=sql-server-ver15
> Add DROP IF EXISTS support to SQL Server 2017

- Source/LinqToDB/Common/Configuration.cs
- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/DataProvider/Access/AccessTools.cs
- Source/LinqToDB/DataProvider/DB2/DB2Tools.cs
- Source/LinqToDB/DataProvider/DataTools.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdTools.cs
- Source/LinqToDB/DataProvider/Informix/InformixTools.cs
- Source/LinqToDB/DataProvider/MySql/MySqlTools.cs
- Source/LinqToDB/DataProvider/Oracle/OracleTools.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLTools.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteTools.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeTools.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerTools.cs
- Source/LinqToDB/DataProvider/Sybase/SybaseTools.cs
Remove code, marked with `[Obsolete]` attribute, except legacy merge API (guess why)
> Remove obsoleted members

- Source/LinqToDB/Common/ConvertBuilder.cs
- Source/LinqToDB/Data/TraceInfo.cs
- Source/LinqToDB/DataProvider/DB2/DB2LUWSchemaProvider.cs
- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/ExpressionTestGenerator.cs
- Source/LinqToDB/Linq/Builder/SelectContext.cs
- Source/LinqToDB/Metadata/MetadataReader.cs
- Source/LinqToDB/Metadata/SystemDataSqlServerAttributeReader.cs
- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/ConvertVisitor.cs
As I was reading parts of the codebase, I noticed some array copies that are not required and cut them down.
The codebase makes a heavy use of LINQ and array copies, this won't make a big change but it's a small improvement anyway.
> Cut down array copies

- Source/LinqToDB/DataProvider/Oracle/OracleMappingSchema.cs
- Tests/Linq/DataProvider/OracleTests.cs
Oracle supports ANSI SQL dates literal, as well as timestamp literals, which are shorter and more readable then calling parsing functions:
- `DATE '2020-01-01'`
- `TIMESTAMP '2020-01-01 10:30:00.1234567 +00:00'`
Sadly, there's no such literal for dates with times, so this has to stay as `TO_DATE('2020-01-01 10:00:00', 'YYYY-MON-DD HH24:MIN-SS')`
> Use Oracle date/timestamp literals instead of functions

- Source/LinqToDB/Linq/Builder/SelectBuilder.cs
- Source/LinqToDB/Reflection/TypeAccessor.cs
- Source/LinqToDB/Reflection/TypeAccessorT.cs
- Tests/Linq/Linq/SelectTests.cs
- Tests/Tests.Playground/TestTemplate.cs
> Fix for #2919. Corrected support for internal members in explicit projection.

- Source/LinqToDB/Data/DataConnection.cs
- Source/LinqToDB/Metadata/MetadataReader.cs
The "Publish a ref atomically" pattern is safe only with a memory half-fence that prevents writes to be reordered after the publishing write (aka _Release Write_).
Otherwise compiler and hardware are free to reorder writes as long as it isn't noticeable on a single thread, which can lead to other threads seeing the published reference pointing to a partially initialized object.
Fixes #2940
> Improve thread-safety

- Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs
- Tests/Linq/DataProvider/OracleTests.cs
Just a forgotten mapping that prevents `OracleBlob` from working smoothly.
> Add missing Blob datatype mapping

- Source/LinqToDB/Sql/Sql.cs
- Tests/Base/TestProvName.cs
- Tests/Linq/Update/InsertTests.cs
This PR adds an extension to use the SQL `DEFAULT` keyword.
This keyword can be used as an insert value, for example:
```csharp
db.T.Insert(() => new T 
{
Id = Sql.Default<int>(),
Name = "Joe",
});
```
Generates:
```sql
insert into T (id, name)
values (default, "Joe")
```
Default is useful when you need to explicitly insert a non-null value but the DB decides what the value actually is, e.g.:
- Identities, sequences;
- Default constraints;
- Triggers.
> Add Sql.Default<T>()

- Tests/Linq/Linq/JoinTests.cs
```sql
([q1].[Count_1] IS NULL OR [q1].[Count_1] IS NULL)
```
should be
```sql
([q1].[Count_1] IS NULL OR [q2].[Count_1] IS NULL)
```    	
```sql
SELECT
Count(*)
FROM
(
SELECT
[p].[PersonID] as [Key_1],
Count(*) as [Count_1]
FROM
[Person] [p]
GROUP BY
[p].[PersonID]
) [q1]
FULL JOIN (
SELECT
[p_1].[PersonID] as [Key_1],
Count(*) as [Count_1]
FROM
[Patient] [p_1]
GROUP BY
[p_1].[PersonID]
) [q2] ON [q1].[Key_1] = [q2].[Key_1] AND ([q1].[Count_1] = [q2].[Count_1] OR [q1].[Count_1] IS NULL AND [q2].[Count_1] IS NULL)
WHERE
([q1].[Count_1] IS NULL OR [q1].[Count_1] IS NULL)
```
> Incorrect column selected in query condition (v3.3 regression)

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLMappingSchema.cs
- Source/LinqToDB/SqlProvider/ValueToSqlConverter.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
Fix #2978
- add special value literal support for floating point values for postgresql
- bonus: use roundtrip format for float literals
> NaN/Infinity literals for PostgreSQL

- Source/LinqToDB/Sql/Sql.cs
- Source/LinqToDB/Tools/DataExtensions.cs
- Tests/Linq/DataProvider/SqlServerTests.cs
Fix #2983
feature hidden behind `useIdentity` parameter to preserve backward compatibility.
> Add sql server support to RetrieveIdentity

- .gitignore
- Source/LinqToDB/DataContext.cs
- Source/LinqToDB/Linq/Builder/GroupByBuilder.cs
- Tests/Linq/Data/DataExtensionsTests.cs
Fix #2937
Hi, this pull request has two unit tests that demonstrate the NullReferenceException
when a query with a grouping is executed by `DataContext`, see issue #2937.
I tried to work around the NRE, but now I'm getting an `ObjectDisposedException` instead:
```csharp
using (var dc = new DataContext(context))
{
// part1: this part works fine
var dictionary = dc.GetTable<Person>()
.GroupBy(p => p.FirstName)
.ToDictionary(p => p.Key);
// part2: this part throws an ObjectDisposedException 
var tables = dictionary.ToDictionary(p => p.Key, p => p.Value.ToList());
}
```
That's because the DataContext's query runner redirects all its calls to the
internal DataConnection's query runner, and the data connection is released 
when the first part is executed and DataContext.ReleaseQuery is called. …
> An attempt to work around the DataContext grouping issue #2937

- Source/LinqToDB/DataProvider/SapHana/SapHanaSqlBuilder.cs
- Source/LinqToDB/Linq/Builder/ExpressionContext.cs
- Source/LinqToDB/Linq/Builder/InsertOrUpdateBuilder.cs
- Source/LinqToDB/LinqExtensions.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Linq/Update/InsertTests.cs
Fix #3005
alongsize with `r => new Table() { }` empty init statement following values also now recognized:
- `null`
- `record => null`
- `record => new Table()`
> Recognize more values as empty update in InsertOrUpdate

- Source/LinqToDB.AspNet/ServiceConfigurationExtensions.cs
- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Tests/Tests.T4/Databases/Access.generated.cs
Fix #2998
- generate typed options constructor in T4
- register untyped options only for context without typed options constructor
> Fix issues around LinqToDbConnectionOptions

- Source/LinqToDB/Metadata/MetadataReader.cs
- Tests/Linq/UserTests/Issue3056Tests.cs
- Tests/Model/TestDataConnection.cs
Simple change, fix MetadataReader.GetDynamicColumns to not reset length variable until we have made array.
Fixes #3056
> Fix for #3056

- Source/LinqToDB.Templates/DataModel.ttinclude
- Source/LinqToDB.Templates/LinqToDB.ttinclude
- Tests/Tests.T4/Databases/SQLite.generated.cs
- Tests/Tests.T4/Databases/SQLite.tt
- Tests/Tests.T4/Databases/SqlCe.generated.cs
- Tests/Tests.T4/Databases/SqlCe.tt
fix #3138
- check that base class is not DataContext (will be removed after merge to v4 as there we support such constructors)
- add explicit option to disable options constructors (`GenerateLinqToDbConnectionOptionsConstructors = true`)
> Don't generate options constructors for context based on DataContext

- Source/LinqToDB/Data/DataConnection.QueryRunner.cs
- Source/LinqToDB/Data/DataConnection.cs
- Source/LinqToDB/DataContext.cs
- Source/LinqToDB/Extensions/DataContextExtensions.cs
- Source/LinqToDB/Linq/IQueryContext.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/Linq/QueryRunnerBase.cs
- Source/LinqToDB/ServiceModel/LinqService.cs
- Source/LinqToDB/ServiceModel/LinqServiceQuery.cs
- Source/LinqToDB/ServiceModel/LinqServiceSerializer.cs
- Source/LinqToDB/ServiceModel/RemoteDataContextBase.QueryRunner.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/ISqlBuilder.cs
- Tests/Linq/Linq/QueryHintsTests.cs
Fix #3137
Issue was caused by storing hints in query cache so it was shared between context which is not correct as our current hint API is per-connection (new hints API should be query-bound!).
So:
- hints from one connection appeared for same query on other connections
- hints cleanup in execution logic lead to concurrency exceptions as this shared hints collection were enumerated in another thread by sql builder
Fix:
- moves hints population to execution phase where there is no way for hints to escape to cache
- implemented safe optimization case where hints collection could be used without copying it
- switched to `IReadOnlyCollection<string>` to pass hints internally to avoid invalid use in future
- also found and fixed incorrect hints copy logic in `DataContext`
> Fix concurrency issues with hints

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLMappingSchema.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
- Tests/Linq/Mapping/FluentMappingTests.cs
- fix ulong handling in bulk copy when mapped to UInt64
- fix `DataType.Binary` mapping to `bytea`. Fix #3130
TODO:
> Various PostgreSQL type mapping issues

- Source/LinqToDB/Linq/Builder/LoadWithBuilder.cs
- Source/LinqToDB/Linq/Builder/SequenceHelper.cs
- Source/LinqToDB/Linq/Builder/TableAttributeBuilder.cs
- Source/LinqToDB/Linq/Builder/WithTableExpressionBuilder.cs
- Source/LinqToDB/LinqExtensions.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
> Make `TableAttributeBuilder` and `WithTableExpressionBuilder` working with `LoadWithContext`

- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Tests/Linq/Linq/ConstructorTests.cs
This PR adds an ability for linq2db to map data to classes with only private or protected constructors. Before this PR only public ones were supported. 
This case is useful when you want to map data to encapsulated rich models, which often have closed constructors.
We can also consider smartly selecting which constructor to use (most suitable based on field names). Right now it will only work for classes with single constructor.
> Allow to use private and protected parameterized constructor for mapping

- README.md
Extended readme with more details about mapping and transaction scope. Changed "Code First" with more appropriate "Fluent".
> Extended readme with more details about mapping and transaction scope

- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Source/LinqToDB/Linq/ExpressionQuery.cs
- Source/LinqToDB/Linq/Query.cs
- Tests/Base/QueryUtils.cs
- Tests/Linq/Linq/FromSqlTests.cs
- Tests/Linq/Linq/SelectTests.cs
`IQueryable` instances has it's own cache and we have to do not cache queries which are dependent on parameters.
> Fixed regression with query cache.

- Source/LinqToDB.Templates/LinqToDB.Tools.ttinclude
I've encountered a case when SingleOrDefault() (at line 38) throws `InvalidOperationException` due to finding more than one assembly item in the collection.
Changing the **tt** file this way eliminated the issue and otherwise didn't affect my project anyhow.
> Replace SingleOrDefault with Any

- Source/LinqToDB/Expressions/ExpressionVisitors/TransformVisitor.cs
- Source/LinqToDB/Mapping/MappingSchema.cs
- Tests/Linq/Mapping/MappingSchemaTests.cs
Fix #3312
TIL that `(x =?? new T())` code is not thread-safe and parallel thread could get uninitialized `x` instance.
> Fix race condition in mapping schema

- Data/Create Scripts/Sybase.sql
- Source/LinqToDB/Sql/Sql.cs
- Tests/Linq/Data/DataConnectionTests.cs
- Tests/Linq/Infrastructure/ActiveIssueConfigurationTests.cs
- Tests/Linq/Linq/AnalyticTests.cs
- Tests/Linq/Linq/CommonTests.cs
- Tests/Linq/Linq/ConcatUnionTests.cs
- Tests/Linq/Linq/CountTests.cs
- Tests/Linq/Linq/CteTests.cs
- Tests/Linq/Linq/DataContextTests.cs
- Tests/Linq/Linq/DateTimeFunctionsTests.cs
- Tests/Linq/Linq/DynamicColumnsTests.cs
- Tests/Linq/Linq/EnumerableSourceTests.cs
- Tests/Linq/Linq/GroupByTests.cs
- Tests/Linq/Linq/InheritanceTests.cs
- Tests/Linq/Linq/IssueTests.cs
- Tests/Linq/Linq/VisualBasicTests.cs
- Tests/Linq/OrmBattle/OrmBattleTests.cs
- Tests/Linq/Update/BulkCopyTests.cs
- Tests/Linq/UserTests/Issue1298Tests.cs
- Tests/Linq/UserTests/Issue1441Tests.cs
- Tests/Linq/UserTests/Issue2478Tests.cs
- Tests/Linq/UserTests/Issue2800Tests.cs
- Tests/Linq/UserTests/Issue3148Tests.cs
Another run over ActiveIssue tests:
- `InnerJoinArray6Postgres` now works probably due to recent enumerable context improvements
- [FIX][Informix] use `CHAR_LENGTH` function instead of `LENGTH` for text (`Sql.Length(str)`, `string.Length` mappings)
- fixed SQL script for Sybase
- issue #1078 seems fixed in current release or earlier (except Access/SQL CE)
- removed test for #1441 as it is not actionable
- issue #535 seems fixed in current release or earlier
- andother ORM Battle test works now (`AnyParameterizedTest`)
> ActiveIssue tests review

- Source/LinqToDB/Data/DataConnection.QueryRunner.cs
- Source/LinqToDB/Data/DataConnection.cs
- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Prevent connecting to database while calling `query.ToString()`
- Fixed lambda copy logic for  Eager Loading.
> Fixed found issues with current code.

- Source/LinqToDB/Sql/Sql.Analytic.cs
- Tests/Linq/Linq/AnalyticTests.cs
Fix #3423 
This PR fixes the type of `default` in `LEAD` and `LAG`.
It comes with a unit test that uses string as `default` in addition to existing tests that used `int`.
I've also added more `LEAD` and `LAG` convenience overloads because it's pretty uncommon to specify the null modifier.
Now all these are possible: `Lag(expr)`, `Lag(expr, 3)`, `Lag(expr, 3, "default")`, which mirrors the native SQL function specs.
> Fix #3423 LEAD and LAG default parameter type

- Build/Azure/pipelines/templates/test-workflow-windows.yml
- Tests/Linq/Linq/AnalyticTests.cs
Looks like after migration to win2022 test image, NETFX tests stopped to run.
> Fix tests execution on win2022 for netfx targets

- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Base/ScopedSettings.cs
- Tests/Linq/UserTests/Issue3432Tests.cs
Fixes #3432
Note that OUTER APPLY will be removed only if `Configuration.Linq.PreferApply = false`
> Fix for #3432. Localized bug with Outer Apply.

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Tests/Linq/Linq/FunctionTests.cs
Fix #3375
Translate `Contains` calls over `IReadOnlyCollection<T>` instances (e.g. `IReadOnlySet<T>.Contains`)
> `Contains` as IN support improvements

- Build/Azure/pipelines/templates/test-jobs.yml
- Build/Azure/pipelines/templates/test-matrix.yml
- Build/Azure/pipelines/templates/test-workflow-windows.yml
- Build/Azure/scripts/sqlserver.2005.cmd
- Build/Azure/scripts/sqlserver.2008.cmd
- Build/Azure/scripts/sqlserver.2012.cmd
- Build/Azure/scripts/sqlserver.2014.cmd
- Build/Azure/scripts/sqlserver.2016.cmd
- Build/Azure/scripts/sqlserver.2017.cmd
- Build/Azure/scripts/sqlserver.2019.cmd
It will be removed 15/03, so we better stop using it now
> Remove use of win2016 image on CI

- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/Linq/QueryableAccessor.cs
- Source/LinqToDB/Reflection/Methods.cs
- Tests/Linq/Linq/ParameterTests.cs
Partial fix #3450
Partial, because extra parameter evaluation still performed by query cache comparer.
> Reduce number of `IQueryable` parameter evaluations

- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Reflection/Methods.cs
- Source/LinqToDB/Sql/Sql.Expressions.cs
- Tests/Linq/Linq/CalculatedColumnTests.cs
Fix #3465
- mark `Sql.TableField` as public
- fix `Sql.Property` use in expressions
> Fix Sql.Property use in expression methods

- Source/LinqToDB/Common/Configuration.cs
Fix #3097
Update default value for `Configuration.ContinueOnCapturedContext` to `false`
> Change defaults for Configuration.ContinueOnCapturedContext

- Source/LinqToDB/SqlQuery/QueryHelper.cs
- Tests/Linq/Linq/ValueConversionTests.cs
Fixes https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/226
> Added column descriptor detection from Coalesce operator.

- Source/LinqToDB.CLI/CommandLine/Commands/HelpCommand.cs
> Workaround exception for CLI called with redirected output

- Directory.Packages.props
- Source/LinqToDB/DataProvider/BulkCopyReader.cs
- Source/LinqToDB/DataProvider/MySql/MySqlDataProvider.cs
- Source/LinqToDB/DataProvider/MySql/MySqlProviderAdapter.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLMappingSchema.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaDataProvider.cs
- Source/LinqToDB/DataProvider/SapHana/SapHanaOdbcDataProvider.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerMappingSchema.cs
- Source/LinqToDB/Expressions/ConvertFromDataReaderExpression.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.RawSqlContext.cs
- Source/LinqToDB/Mapping/MappingSchema.cs
- Source/LinqToDB/Sql/Sql.DateOnly.cs
- Source/LinqToDB/Sql/Sql.DateTime.cs
- Source/LinqToDB/Sql/Sql.DateTimeOffset.cs
- Source/LinqToDB/Sql/Sql.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Tests/Base/TestBase.cs
- Tests/Linq/Linq/TakeSkipTests.cs
- Tests/Linq/Update/BulkCopyTests.cs
- Tests/Linq/Update/DropTableTests.cs
Small generic changes from ClickHouse PR:
- update `MySqlConnector` nuget and add more data reader methods support for it
- pick remaining non-functional changes
- fix `NULL` literal generation from enumerable source to have space between `NULL` and column alias
- register nullable structs in `MappingSchema.AddScalarType()` by default
- unwrap enums in `ConvertFromDataReaderExpression`
> Small fixes from ClickHouse provider branch

- Source/LinqToDB/DataProvider/Informix/InformixSqlOptimizer.cs
- Source/LinqToDB/Linq/Expressions.cs
- Source/LinqToDB/Sql/Sql.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
Extracted from #3627
Fixes generation of datetime strings to have fixed length for parts with leading zeroes, e.g. generate `01:02` time part instead of `1:2`
> Fix datetime strings generation

- Source/LinqToDB/DataProvider/Access/AccessSqlOptimizer.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
Another part of #3627
Move access-specific logic to Access optimizer so it doesn't interfere with ClickHouse implementation
> Refactor LIKE handling in BasicSqlOptimizer

- Directory.Packages.props
- Tests/Linq/DataProvider/Types/ClickHouseTypeTests.cs
- [NodaTime](https://www.nuget.org/packages/NodaTime): 3.1.1 -> 3.1.2
- [ClickHouse] Extend tested `Date32`/`DateTime64` ranges to new limits from ClickHouse 22.8.1
> ClickHouse 22.8.1 updates

- Source/LinqToDB.CLI/CommandLine/Commands/HelpCommand.cs
- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Options.cs
- Source/LinqToDB.CLI/CommandLine/Options/NamingCliOption.cs
- Source/LinqToDB.CLI/CommandLine/Options/OptionType.cs
Fix #3676
- accept `transformation: none` option from command-line/`json` config
- update help to list `transformation: none` option
- update help to list `transformation: association` option instead of non-existing `transformation: t4`
> [CLI] Fix transformation option parsing and help

- Build/Azure/README.md
- Directory.Packages.props
- NuGet/linq2db.MySqlConnector.nuspec
- NuGet/linq2db.Remote.Grpc.nuspec
- [Grpc.Net.Client](https://www.nuget.org/packages/Grpc.Net.Client): 2.47.0 -> 2.48.0
- [ClickHouse.Client](https://www.nuget.org/packages/ClickHouse.Client): 5.0.3 -> 5.0.4 (tested manually)
- [MySqlConnector](https://www.nuget.org/packages/MySqlConnector): 2.1.12 -> 2.1.13
- [Microsoft.SqlServer.Types](https://www.nuget.org/packages/Microsoft.SqlServer.Types): 160.600.9-ctp2p0 -> 160.900.6-rc0
- [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk): 17.3.0 -> 17.3.1
- [BenchmarkDotNet](https://www.nuget.org/packages/BenchmarkDotNet): 0.13.1 -> 0.13.2
> Dependencies update

- Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
- Source/LinqToDB/SqlQuery/ConvertVisitor.cs
- Tests/Linq/DataProvider/SybaseTests.cs
- Tests/Linq/Linq/FullTextTests.SqlServer.cs
I found that Russian letters misused in Englush words in few places and fix it. (not sure about Sybase inclusion).
Please, feel free to close this PR as the unimportant one.
> [Minor] Fix misuse of Russian letters in English words.

- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
Helps to figure out which column is the issue when creating table with type that can not be determined.
Log was:
> Unhandled exception. LinqToDB.LinqToDBException: Database type cannot be determined automatically and must be specified explicitly
Now (diff in bold):
> Unhandled exception. LinqToDB.LinqToDBException: Database **column** type cannot be determined automatically and must be specified explicitly **for system type NodaTime.Instant**
> Improve log when db type can not be determined

- Source/Shared/IsExternalInit.cs
Critical issue discovered during https://github.com/linq2db/linq2db/pull/3530 testing.
Workaround to https://github.com/dotnet/runtime/issues/79082
> Fix C# init-only support for older TFMs

- Source/LinqToDB.Tools/Mapper/ExpressionBuilder.cs
- Source/LinqToDB/DataProvider/DataTools.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlFn.cs
- Source/LinqToDB/Expressions/ExpressionExtensions.cs
- Source/LinqToDB/Expressions/ExpressionVisitors/TransformInfoVisitor.cs
- Source/LinqToDB/Expressions/ExpressionVisitors/TransformVisitor.cs
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Expressions/TypeMapper/TypeMapper.cs
- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Linq/Builder/EagerLoading.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
- Source/LinqToDB/Sql/Sql.Collate.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlProvider/ISqlOptimizer.cs
- Source/LinqToDB/SqlQuery/CloneVisitor.cs
- Source/LinqToDB/SqlQuery/ConvertVisitor.cs
- Source/LinqToDB/SqlQuery/QueryVisitorExtensions.cs
- Tests/Linq/Linq/PaginationExtensions.cs
fix #3579
Also migrate `NotNullIfNotNull` attribute usages to use nameof (C# 11)
> Update Sql.Collate nullability

- Source/LinqToDB/DataContextTransaction.cs
- Tests/Linq/Data/TransactionTests.cs
This adds an `IAsyncDisposable` implementation for `DataContextTransaction`s.
Note: `DataConnectionTransaction` already implements `IAsyncDisposable`
> Implement IAsyncDisposable for DataContextTransaction

- Build/Azure/pipelines/templates/test-matrix.yml
Disable some test targets to avoid CI timeouts after net7 targets added
> [CI] Disable some test targets

- Source/LinqToDB/Remote/LinqService.cs
- Source/LinqToDB/Remote/LinqServiceSerializer.cs
- Tests/Linq/Linq/ValueConversionTests.cs
Fixed incorrect data read using remote context for columns with ValueConverter applied. Discovered when tried to reproduce #3830
> FIx ValueConverter support for RemoteContext

- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Interceptors.cs
Fixes #3896 
Occurs when .net 7 is picked up rather than .net 6.
Loading native only assemblies caused the T4 compilation to fail.
The generated type in the in memory assembly has a namespace so the gettype returns null in .net 7 too.
Error fixed:
```
dotnet linq2db scaffold -i Portal.json -c "Server=localhost;Database=Portal;TrustServerCertificate=true;Integrated Security=SSPI" --customize Generic.tt
AssemblyResolve: Microsoft.CodeAnalysis.resources, Version=4.4.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35
AssemblyResolve: Microsoft.CodeAnalysis.resources, Version=4.4.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to …
```
> T4: Do not reference native assemblies when scaffolding

- Source/LinqToDB/Linq/Builder/AssociationHelper.cs
- Source/LinqToDB/Linq/Builder/CountBuilder.cs
- Tests/Linq/Linq/AssociationTests.cs
Fix #3658
Replaces #3657
Fixes:
- respect `CanBeNull` for association with custom predicate
- respect associations in select for `Count` scalar queries
- don't remove "unused" **INNER** join for `Count` scalar query with association field access
> Association fixes

- Source/LinqToDB/DataProvider/DB2/DB2SqlBuilderBase.cs
- Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Source/LinqToDB/DataProvider/Oracle/OracleSqlBuilderBase.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/CteTests.cs
Fix #3945 
Summary:
- remove not needed SELECT * wrapper around SELECT with CTE for insert queries
- fix DB2 CTE generation location
- added basic heuristics to detect that CTE created by `GetCte` API is not recursive
- "fixed" unnecessary column generation hack (whole hack will be gone in v6)
> Failing test case for #3945

- Build/Azure/pipelines/templates/build-vars.yml
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Mapping/AssociationAttribute.cs
- Source/LinqToDB/Mapping/AssociationDescriptor.cs
- Source/LinqToDB/Mapping/EntityDescriptor.cs
- Tests/Linq/Linq/AssociationTests.cs
I'm not sure about the performance aspect, do you think I should cache the 
```
var setMethod = descriptor.GetSetterMethod(storageMember.Type, ex.Type)!;
```
or is it useless because the resulting expression is cached at a higher level?
Edit: fixes #3961
> Add support for custom setters for associations storage members

- Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
This is needed for better integration with https://github.com/linq2db/linq2db.EntityFrameworkCore - user don't wan't to specify connection string second type
I've noticed that it is not a good idea to set multiple options with single extension - it already fired back several times...
> Add provider configuration overloads without connection string

- Source/LinqToDB/Compatibility/System/Data/Linq/Binary.cs
- Source/LinqToDB/DataOptions.cs
Discovered during ef.core extension migration:
- `DataOptions` equality operators doesn't work with null values
- `UseDB` configuration methods should have overloads without connection string to allow provider configuration without specifying connection string
> DataOptions: fix equality operators nullability

- Source/LinqToDB/DataProvider/SqlServer/SystemDataSqlServerAttributeReader.cs
- Source/LinqToDB/Mapping/MappingSchema.cs
- Source/LinqToDB/Mapping/MappingSchemaInfo.cs
- Source/LinqToDB/Metadata/AttributeInfo.cs
- Source/LinqToDB/Metadata/AttributeReader.cs
- Source/LinqToDB/Metadata/FluentMetadataReader.cs
- Source/LinqToDB/Metadata/IMetadataReader.cs
- Source/LinqToDB/Metadata/MetaMemberInfo.cs
- Source/LinqToDB/Metadata/MetaTypeInfo.cs
- Source/LinqToDB/Metadata/MetadataReader.cs
- Source/LinqToDB/Metadata/SystemComponentModelDataAnnotationsSchemaAttributeReader.cs
- Source/LinqToDB/Metadata/SystemDataLinqAttributeReader.cs
- Source/LinqToDB/Metadata/XmlAttributeReader.cs
- Tests/Linq/Metadata/AttributeReaderTests.cs
- Tests/Linq/Metadata/SystemDataLinqAttributeReaderTests.cs
- Tests/Linq/Metadata/XmlReaderTests.cs
Fix #3981
After IMetadataReader refactoring [here](#3900) `GetAttributes` methods always called using `MappingAttribute` as type parameter, which makes it unnecessary and confusing.
> Simplify IMetadataReader.GetAttributes API

- Source/LinqToDB/DataProvider/ProviderDetectorBase.cs
Discovered during efcore testing with new `UseDB` overloads without connection string...
> Don't throw from provider detector when autodetect is not enabled

- Source/LinqToDB/DataProvider/PostgreSQL/NpgsqlProviderAdapter.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLMappingSchema.cs
- Tests/.editorconfig
- Tests/Linq/DataProvider/PostgreSQLTests.cs
Fix #4006
- add SQL literals generation for `BigInteger` parameters
- add `BigInteger` mapping on read
> [Npgsql] Add BigInteger support

- Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
When optional parameters not specified, compiler cannot decide which overload to call...
> Fix overloads conflict for UsePostgreSQL extensions

- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSqlBuilder.cs
cherry-picked from https://github.com/linq2db/linq2db/pull/4049 as it creates a lot of noise in baselines, making it hard to review
> Fix ClickHouse primary key SQL spacing

- Source/LinqToDB/Async/AsyncEnumeratorAsyncWrapper.cs
- Source/LinqToDB/Compatibility/System/IAsyncDisposableEmpty.cs
- Source/LinqToDB/DataContext.cs
- Source/LinqToDB/Linq/ExpressionQuery.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Tests/Linq/Linq/EagerLoadingTests.cs
- Tests/Model/Extensions.cs
Fix #4057
There were at least two bugs:
- for async enumeration we were disposing connection before data reader (in sync code disposal were done in different place with correct order) which raised exception in SqlClient when it tried to execute `Rollback Transaction` command on connection with already open data reader
- transaction rollback is actually another bug, affecting also sync code: because we open eager load transaction not on `DataContext` but on underlying `DataConnection` - `DataContext` with `KeepConnectionAlive = false` option set (default) doesn't know anything about it and close underlying connection after first eager load query for async code or don't close it at all for sync code (that's why there were no exception for sync code)
- also there were small issues with …
> Fix eager load auto-transaction

- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Reflection/TypeAccessorT.cs
- Tests/Linq/Linq/InterfaceTests.cs
- Tests/Linq/Update/MergeTests.Issues.cs
- Tests/Model/Interfaces.cs
Fix #4031
Original issue caused by C# compiler adding explicit getter/setter implementations without property implementation to class inheriting implementation from base class, located in another assembly.
I've added fix, but not happy with it so will appreciate better heuristics proposed.
Additional tests showed that we also doesn't handle inherited explicit interface implementations, so it makes sense to try and fix it too.
Additionally, added guard against static interface members
> Improve interfaces support

- Source/LinqToDB/Reflection/TypeAccessorT.cs
- Tests/Linq/Linq/InterfaceTests.cs
- Tests/Linq/Linq/MappingTests.cs
> Restore handling behavior of same-name properties/fields for entities with interfaces

- Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs
- Tests/Linq/UserTests/Issue4090Tests.cs
Fix #4090 
The queries here were mostly copied from the tests for #3462 and although are not quite the same as in #4090, effectively demonstrate the bug.  Note that only when the nested OUTER APPLY has no data does the bug manifest itself, and only depending on the order of the columns selected.
> Fix outer apply columns nullability tracking

- Source/LinqToDB/DataProvider/MySql/MySqlTools.cs
Fix #4124
Since MySQL.Data doesn't support modern versions of MariaDB, we can map it to MySqlConnector directly
> map mariadb provider name to mysqlconnector provider

- Source/LinqToDB/DataProvider/Oracle/Oracle11SqlOptimizer.cs
Fix #3273
Optimized ConvertExpressionImpl method to use nvl function for coalesce expressions with two parameters.
> Optimized ConvertExpressionImpl method

- Source/LinqToDB/LinqExtensions.Merge.cs
- Tests/Linq/Update/DeleteWithOutputTests.cs
- Tests/Linq/Update/InsertWithOutputTests.cs
- Tests/Linq/Update/MergeTests.WithOutput.cs
- Tests/Linq/Update/UpdateWithOutputTests.cs
Referring to the outputTable using Expression.Constant results in TableAttributeBuilder not being used. Unfortunately TableBuilder.BuildSequence just returns a TableBuilder+TableContext which only bases its SqlTable on the original type without taking modified attributes into account. So in order to make the modified attributes take effect the full expression from outputTable must be used rather than just embedding it in a ConstantExpression (alternatively should the logic in TableBuilder be changed so the SqlTable is generated with the changed attributes)
> Fix table attributes ignored for output table when using MergeWithOutputInto

- Source/LinqToDB/Linq/Builder/SingleExpressionContext.cs
- Tests/Linq/Update/MergeTests.WithOutput.cs
This makes the test included in the commit work instead of throwing a NotImplementedException.
I had a hard time figuring out what IsExpression is actually supposed to do. It asks whether an expression is an expression (?), and the comments are less than helpful. It's something about whether the (linq) expression can be turned into a valid SQL expression in the current context? - but then what does it mean when expression is null?
I figured the worst that can happen is that incorrect sql is produced now where it previously crashed with NotImplementedException. It at least makes this case work, and can't affect anything that didn't crash before.
> Fix MergeWithOutputInto with conditional in output expression

- Source/LinqToDB/Async/AsyncFactory.cs
- Source/LinqToDB/Common/Internal/MethodCache.cs
- Source/LinqToDB/Common/Internal/ValueComparer.cs
- Source/LinqToDB/DataProvider/Access/AccessHints.cs
- Source/LinqToDB/DataProvider/Access/AccessSpecific.cs
- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseHints.cs
- Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSpecific.cs
- Source/LinqToDB/DataProvider/MySql/MySqlHints.cs
- Source/LinqToDB/DataProvider/MySql/MySqlSpecific.cs
- Source/LinqToDB/DataProvider/Oracle/OracleHints.cs
- Source/LinqToDB/DataProvider/Oracle/OracleSpecific.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLHints.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSpecific.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteHints.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteSpecific.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeHints.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeSpecific.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerHints.cs
- Source/LinqToDB/DataProvider/SqlServer/SqlServerSpecific.cs
- Source/LinqToDB/Expressions/InternalExtensions.cs
- Source/LinqToDB/Expressions/IsQueryableAttribute.cs
- Source/LinqToDB/LinqExtensions.cs
- Tests/Linq/Extensions/SqlServerTests.cs
The following code
```c#
from c in db.Child
select new
{
cc =
(
from c1 in db.Child
.AsSqlServer().WithNoLock()
where c1.ParentID == c.ParentID select c1
).Count()
}
```
generates an exception
```
value(Tests.Model.TestDataConnection).GetTable().AsSqlServer().TableHint("NoLock").Where(c1 => (c1.ParentID == c.ParentID)).Count()'
cannot be converted to SQL.
```
> BUG: Using hint in subquery.

- Source/LinqToDB/SqlQuery/SelectQueryOptimizer.cs
- Tests/Linq/Linq/GroupByTests.cs
The following code 
```c#
from pmp in
(
from pmp  in db.Child
group pmp by pmp.ParentID into g
select g.Key
)
from pmp1 in db.Child
select new { pmp1.ChildID }
```
generates wrong SQL
```sql
SELECT
[pmp1].[ChildID]
FROM
[Child] [pmp],
[Child] [pmp1]
GROUP BY
[pmp].[ParentID]
```
should be 
```sql
SELECT
[pmp1].[ChildID]
FROM
(
SELECT
[t1].[ParentID]
FROM
[Child] [t1]
GROUP BY
[t1].[ParentID]
) [pmp],
[Child] [pmp1]
```
> BUG: GroupBy with subquery.

- Source/LinqToDB/Linq/Builder/EnumerableContext.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
- Source/LinqToDB/SqlQuery/SqlValuesTable.cs
- Tests/Linq/Linq/ValueConversionTests.cs
```c#
from p in db.Parent
from i in new[] { 0, 1 }
select new
{
ID    = i == 0 ? null : (int?)p.ParentID,
Value = p.Value1
} into p
where p.ID == p.Value // p.ID is considered as NOT nullable
select p
```
> BUG: Conditional with null

- Source/LinqToDB/DataProvider/Oracle/Oracle11ParametersNormalizer.cs
- Source/LinqToDB/DataProvider/Oracle/Oracle122ParametersNormalizer.cs
- Source/LinqToDB/DataProvider/Oracle/OracleDataProvider.cs
Fix #4219
We could reenable them when we will add more dialects to Oracle provider. Parameter names longer 30 characters doesn't sound right thing to require new dialect support.
> Disable long parameter names for oracle12 dialect

- Build/Azure/pipelines/templates/build-job.yml
Again, oracle test agents run out of space..
> Remove netcoreapp3.1 test builds (to gain space on CI agents)

- Source/LinqToDB.Tools/Comparers/ComparerBuilder.cs
- Source/LinqToDB.Tools/EntityServices/EntityMap.cs
- Source/LinqToDB.Tools/Mapper/ExpressionBuilder.cs
- Source/LinqToDB/Concurrency/ConcurrencyExtensions.cs
- Source/LinqToDB/Concurrency/OptimisticLockPropertyAttribute.cs
- Source/LinqToDB/Data/RecordReaderBuilder.cs
- Source/LinqToDB/Extensions/ReflectionExtensions.cs
- Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
- Source/LinqToDB/Mapping/ColumnDescriptor.cs
- Source/LinqToDB/Mapping/EntityDescriptor.cs
- Source/LinqToDB/Mapping/MappingSchema.cs
- Source/LinqToDB/Mapping/SkipValuesByListAttribute.cs
- Source/LinqToDB/Reflection/MemberAccessor.cs
- Source/LinqToDB/SqlQuery/SqlObjectExpression.cs
Fix #4275
This PR address performance issues in `EntityDescriptor` construction. It is not an issue for majority of use-cases, but in situations, when you want to prebuild big datamodel it results in quite big delays. See #4275 for details on specific use case.
I've used following model to test:
- entity with 1 PK field, 4 FK fields, 40 regular fields and 8 associations
Tested models: 150 entities and 1500 entities (to detect bottlenecks, not visible enough on smaller model)
1. model build: create single instance of `FluentMappingBuilder` and populate it with mappings in single thread
2. model pregeneration: create entity descriptor for each registered entity using `MappingSchema.GetEntityDescriptor` call in single thread
Version: 5.2.2 vs this PR
150 items: 0.5 + 4 seconds => 0.5 + 0.7 …
> EntityDescriptor optimizations

- Source/LinqToDB/Data/DataConnection.cs
Reasoning: the property is supposed to be overridable (why would a global static one be overridable then?) but for some reason it's not outside of the base class which is often inheritable.
> Change WriteTraceLineConnection accessibility level to protected

- Tests/Linq/Linq/SelectQueryTests.cs
Adds test for #4284
We don't plan to fix it for now:
- it is already fixed in new parser
- fix could be too complex with current parser
- issue could be workarounded
> Add test for #4284

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLIdentifierQuoteMode.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.cs
- Tests/Base/BaselinesWriter.cs
- Tests/Linq/DataProvider/PostgreSQLTests.cs
Fix #4285
- fix validation of allowed characters
- add `"` escaping
- remove legacy logic to skip quotation when identifier starts from `"`. User should fix their mappings or use `PostgreSQLIdentifierQuoteMode.None` mode
> Fix postgresql identifiers quotation

- Source/LinqToDB/Extensions/ReflectionExtensions.cs
Fix #4267 - adds workaround for runtime issue
We already have workaround code for CoreRT, but looks like NativeAOT have issue with `GetInterfaceMap` code erasure : https://github.com/dotnet/runtime/issues/89157
Problem with this workaround is tha it only suppress exception, not reintroduce required functionality, so it will not work properly for mappings with interfaces.
For v6 release I plan to add proper NativeAOT testing to ensure that we can work there.
> Workaround NativeAOT issue with GetInterfaceMap  method

- Source/LinqToDB/Expressions/ExpressionExtensions.cs
Fix #4263
`Expression.DebugView` is a private property accessed using reflection, which leads to it's trimming.
> Fix trimming issue with Expression.DebugView use

- Source/LinqToDB/DataProvider/Oracle/OracleBulkCopy.cs
Tiny perf improvement: while investigating the DateOnly BulkCopy issue, I noticed that the buffer containing one batch of rows is arbitrarily sized to 31 items (quite low) although we actually know the batch size.
> Size batch buffer appropriately

- Source/LinqToDB/Data/DataConnection.Async.cs
- Source/LinqToDB/Data/DataConnection.cs
more or less easily reproduced using following code:
```cs
for (var i = 0; i < 190000; i++)
{
DataConnection.TurnTraceSwitchOn(System.Diagnostics.TraceLevel.Info);
DataConnection.TurnTraceSwitchOn(System.Diagnostics.TraceLevel.Warning);
Task.Run(() =>
{
using var db = new DataConnection(SqlServerTools.GetDataProvider(provider: SqlServerProvider.MicrosoftDataSqlClient), "Server=.\\SQL2019;Initial Catalog=DesignerDB;User=sa;Password=p@zzw0rd;Encrypt=true;TrustServerCertificate=true");
using var _ = db.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
});
DataConnection.TurnTraceSwitchOn(System.Diagnostics.TraceLevel.Info);
DataConnection.TurnTraceSwitchOn(System.Diagnostics.TraceLevel.Warning);
}
```
> Fix rare NRE in tracing due to race-conditions

- Source/LinqToDB/DataProvider/SQLite/SQLiteExtensions.cs
- Source/LinqToDB/DataProvider/SQLite/SQLiteTools.cs
CreateDatabase helper method exists in AccessTools, SqlCeTools and SQLiteTools.
MS Access most common database file extension is ".mdb", SQL Server Compact - ".sdf". 
Unlike them SQLite has many commonly used extensions (".sqlite", ".sqlite3", ".db", etc.).
SQLite database file extension can now be passed to SQLiteTools.CreateDatabase (parameter has ".sqlite" default value for backward compatibility)
> SQLite database file extension can now be passed to SQLiteTools.CreateDatabase (parameter has ".sqlite" default value for backward compatibility)

- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLBulkCopy.cs
- Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs
Fix #4445
Good afternoon.
`NormalizeTimeStamp` now accepts the parameter `NpgsqlProviderAdapter.NpgsqlDbType?`, the responsibility for calculating it has been transferred to the following methods:
- `setParameter` - as before, GetNativeType(data type.DbType) is simply called without parameters.
- `ProviderSpecificCopySyncImpl<T>` - now gets `NpgsqlProviderAdapter.NpgsqlDbType?` from the `npgsqlTypes` array.
- `ProviderSpecificCopyImplAsync<T>` - now gets `NpgsqlProviderAdapter.NpgsqlDbType?` from the `npgsqlTypes` array.
- `ProviderSpecificCopyImplAsync<T> with NATIVE_ASYNC` - now gets `NpgsqlProviderAdapter.NpgsqlDbType?` from the `npgsqlTypes` array.
The `ProviderSpecificCopy*` methods already had a calculated `npgsqlTypes` array, so I just deleted the `GetNativeType` calls. The main …
> PostgreSQLBulkCopy - replaced GetNativeType by pre calculated npgsqlType

- README.md
Changes "plain old CLR object objects" to "plain old CLR objects" by changing "POCO objects" to "POCOs".
> Removed redundancy in README for POCOs.

- Source/LinqToDB/ProviderName.cs
Found a small copy/paste typo in the providerName comment for the SqlServer2022
> Fix typo in SqlServer2022 providerName comment

- Tests/Linq/Linq/SetOperatorTests.cs
Looks like using same subquery expression leads to huge AST of duplicated queries
#3132
> Fix SET query parsing with same subqueries

- Tests/Linq/UserTests/Issue4337Tests.cs
- Tests/Linq/UserTests/Issue4394Tests.cs
> Address Query Parsing Performance

- Tests/Linq/UserTests/Issue3847Tests.cs
> test for #3847

- Source/LinqToDB/Linq/Builder/ParametersContext.cs
- Source/LinqToDB/Linq/Builder/TakeSkipBuilder.cs
- Source/LinqToDB/Linq/Query.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Source/LinqToDB/Mapping/MappingSchema.cs
- Tests/Linq/Data/DataExtensionsTests.cs
- Tests/Linq/Linq/MappingTests.cs
Fix #4539
Summary:
- improve collection-based parameters handling (currently used by `In/Contains` predicates with client-side collection) to use same parameter conversion generation logic as other parameters (original issue)
- (semi-breaking change) fix long standing issue with `SetConvertExpression(addNullCheck=true)` creating invalid conversion expression to `DataParameter` : `dp != null ? dp : default` as it later used to extract value and type from it leading to bad extractors like `(dp != null ? dp : default).Value/DbType`. As it was generated bad expression, I wouldn't expect anyone being broken by this change.
> Improve InList values conversion logic

- Source/CodeGenerators/Directory.Build.props
or roslyn will not be able to locate them
> Remove tfm from generator binaries path

- Source/LinqToDB/SchemaProvider/SchemaProviderBase.cs
SchemaProvider parsed max length of varchar(max) procedure parameters as "-1".
This fixes the problem for me but unsure if this causes problems in other cases...
Fixes #4631
> Fix length -1 on varchar(max) parameters

- NuGet/TestToolLocal.cmd
- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Configuration.cs
- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.Options.cs
- Source/LinqToDB.CLI/CommandLine/Commands/ScaffoldCommand.cs
- Source/LinqToDB.Scaffold/Scaffold/DataModel/DataModelLoader.DataContext.cs
- Source/LinqToDB.Scaffold/Scaffold/Options/DataModelOptions.cs
- Source/LinqToDB.Scaffold/Scaffold/Options/ScaffoldOptions.cs
- Tests/Tests.T4/Cli/Interceptors.tt
- Tests/Tests.T4/Cli/Interceptors/SQLite/TestDataDB.cs
Hey
In my ongoing quest to get my scaffolding exactly like I want it, I now have the need for changing the access modifier of the generated Context class.
I've added a property to the scaffolding dataModel that enables this.
When not specified it does as before.
I'm not entirely sure where or if it would be appropriate to add this new option to tests.
> Add DataContextModifier option to ScaffoldCommand

- Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs
- Tests/EntityFrameworkCore/Models/ForMapping/ForMappingContextBase.cs
- Tests/EntityFrameworkCore/Models/ForMapping/Npgsql/ForMappingContext.cs
- Tests/EntityFrameworkCore/Models/ForMapping/Pomelo/ForMappingContext.cs
- Tests/EntityFrameworkCore/Models/ForMapping/SQLServer/ForMappingContext.cs
- Tests/EntityFrameworkCore/Models/ForMapping/SQLite/ForMappingContext.cs
- Tests/EntityFrameworkCore/Models/ForMapping/SkipModesTable.cs
- Tests/EntityFrameworkCore/Tests/ForMappingTests.cs
Migration of https://github.com/linq2db/linq2db.EntityFrameworkCore/pull/274 to this repo
> Fix EF.Core model `PropertySaveBehavior` attributes mapping

- Source/LinqToDB/Expressions/SqlDefaultIfEmptyExpression.cs
- Source/LinqToDB/Linq/Builder/ExpressionBuildVisitor.cs
- Tests/Linq/Linq/DistinctTests.cs
Issue exists at least since v5: distinct over record from association generate extra unused columns that could lead to de-duplication failure
```sql
SELECT
[t1].[Value_1]
FROM
(
SELECT DISTINCT
[a_Lvl3].[Id],
[a_Lvl3].[Value] as [Value_1],
-- shouldn't be here
[a_Lvl2].[Id] as [Id_1]
FROM
[Level1] [p]
LEFT JOIN [Level2] [a_Lvl2] ON [p].[Id] = [a_Lvl2].[FK2]
LEFT JOIN [Level3] [a_Lvl3] ON [a_Lvl2].[FK3] = [a_Lvl3].[Id]
WHERE
[a_Lvl3].[Id] = 21
) [t1]
LIMIT 2
```
> Fix record exists check for multiple left joins

- Source/LinqToDB.FSharp/DataOptionsExtensions.fs
- Tests/FSharp/Issue4851.fs
- Tests/FSharp/Tests.FSharp.fsproj
> Fix UseFSharp() extension method not found in F#.

- Source/LinqToDB/TempTable.cs
- Tests/Linq/Update/TempTableTests.cs
The following code stopped working:
```c#
class Table1
{
public int ID;
}
class Table2
{
public int       ID;
public DateTime? Date;
}
[Test]
public void InsertTest([DataSources(false, TestProvName.AllClickHouse)] string context)
{
using var db = GetDataContext(context);
using var t1 = db.CreateLocalTable<Table1>([new Table1 { ID = 10 }]);
using var t2 = db.CreateLocalTable<Table2>();
t2.Insert(from t in t1 select new Table2 { ID = t.ID });
var result = t2.ToList();
Assert.Multiple(() =>
{
Assert.That(result,         Has.Count.EqualTo(1));
Assert.That(result[0].ID,   Is.EqualTo(10));
Assert.That(result[0].Date, Is.Null);
});
}
```
Works in 5.4.1.
> TempTable.Insert method is broken.

- Source/LinqToDB/DataProvider/DataProviderBase.cs
- Source/LinqToDB/DataProvider/SqlCe/SqlCeDataProvider.cs
- Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
- Source/LinqToDB/SqlQuery/SelectQueryOptimizerVisitor.cs
- Tests/Linq/Linq/GroupByTests.cs
See test.
`group by` itself has `order by`.
```sql
DECLARE @take Int -- Int32
SET     @take = 2
/* GroupBy */
SELECT TOP (@take)
[t1].[Key_1],
[t1].[Max_1]
FROM
(
SELECT
MAX([g_1].[ChildID]) as [Max_1],
[g_1].[ParentID] as [Key_1]
FROM
[Child] [g_1]
GROUP BY
[g_1].[ParentID]
) [t1]
ORDER BY
[t1].[Max_1] DESC
```
If it is used as subquery `order by` is lost.
```sql
/* GroupBy
Query */
SELECT
[t].[ParentID],
[t].[ChildID]
FROM
[Child] [t]
WHERE
[t].[ParentID] IN (
SELECT
[t1].[ParentID]
FROM
(
SELECT TOP (2)
[x].[ParentID]
FROM
[Child] [x]
GROUP BY
[x].[ParentID]
) [t1]
)
```
> ORDER BY is removed from subquery even when TOP or LIMIT/OFFSET are used

- Source/LinqToDB/Concurrency/OptimisticLockPropertyAttribute.cs
- Source/LinqToDB/Concurrency/OptimisticLockPropertyBaseAttribute.cs
- Source/LinqToDB/Expressions/SkipIfConstantAttribute.cs
- Source/LinqToDB/Linq/Builder/Attributes.cs
- Source/LinqToDB/Linq/Internal/ColumnReaderAttribute.cs
- Source/LinqToDB/Mapping/AssociationAttribute.cs
- Source/LinqToDB/Mapping/DynamicColumnsStoreAttribute.cs
- Source/LinqToDB/Mapping/NotNullAttribute.cs
- Source/LinqToDB/Mapping/QueryFilterAttribute.cs
- Source/LinqToDB/Mapping/ResultSetIndexAttribute.cs
- Source/LinqToDB/Mapping/ValueConverterAttribute.cs
- Source/LinqToDB/Sql/Sql.EnumAttribute.cs
- Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
All attributes that inherit MappingAttribute must have `AllowMultiple=true` set as this is the only feature of this base class: allow configuration-based dispatch. Also remoted `AllowMultiple=false` from some non-maping attributes, as this is default value for this option.
Following mappin attributes fixed:
- `OptimisticLockPropertyBaseAttribute`-based attributes
- `AssociationAttribute`
- `DynamicColumnsStoreAttribute`
- `NotNullAttribute`
- `QueryFilterAttribute`
- `ValueConverterAttribute`
- `EnumAttribute`
> Add missing `AllowMultiple = true` to MappingAttribute-based attributed

- Source/LinqToDB/Linq/Builder/ExpressionBuildVisitor.cs
- Tests/Linq/Linq/ParameterTests.cs
The following code in not working:
```c#
var valueGetter = () => 1;
_ = db.Parent.Where(r => r.ParentID == valueGetter());
```
Worked in v5.4.1.
> Lambda as a parameter issue

- Source/LinqToDB/Linq/Builder/DeleteBuilder.cs
- Source/LinqToDB/Linq/Builder/InsertBuilder.cs
- Source/LinqToDB/Linq/Builder/InsertOrUpdateBuilder.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.InsertWhenNotMatched.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.MergeContext.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.UpdateWhenMatched.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.UpdateWhenMatchedThenDelete.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.UpdateWhenNotMatchedBySource.cs
- Source/LinqToDB/Linq/Builder/MergeBuilder.cs
- Source/LinqToDB/Linq/Builder/MultiInsertBuilder.cs
- Source/LinqToDB/Linq/Builder/UpdateBuilder.cs
- Tests/Linq/Linq/GroupByTests.cs
- Tests/Linq/Linq/LeftJoinTests.cs
The following code is not working
```c#
using var t1 = db.CreateLocalTable("temp_table_1", [new { ID = 1, Value = ""}]);
using var t2 = db.CreateTempTable("temp_table_2",
from c in t1
group c by c.ID into gr
select new
{
gr.First().Value,
});
```
Worked in v5.4.1.
> GroupBy issue

- Source/LinqToDB/Data/DataConnection.Configuration.cs
- Source/LinqToDB/DataContext.cs
- Tests/Linq/UserTests/Issue4883Tests.cs
Use EnsureConnection(connect: false) in ConfigurationID to obtain connection string. This way connection is not opened synchronously during query generation.
Fixes #4883
> Use EnsureConnection() in ConfigurationID property of DataConnection and DataContext

- Source/LinqToDB/TempTable.cs
Clarifying comment that says `TmpTable` uses real tables.
It actually depends on option `TableOptions.IsTemporary`, which is the default when using `db.CreateTempTable<T>`.
Side note (breaking change, for v6?): 
It would be nice if internally we had a flag on the table that indicates whether the table is normal or temporary.
We don't need to send DROP TABLE statements in `Dispose()` for real temporary table,
The only use case would be if someone wants to re-create the same temporary table in the same transaction, in which case it seems appropriate to have users call `DropTable()` themselves.
> Update TempTable comment

- Source/LinqToDB/DataProvider/DataProviderBase.cs
- Source/LinqToDB/Linq/QueryRunner.cs
- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
- Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
`IsTakeSupported` was probably a legacy provider flags that was used before.
Currently all providers have `IsTakeSupported = true`, even the few that don't support TOP/TAKE/FETCH such as Oracle 11.
I'm noting that we have 60 flags remaining, that's a lot of bool / bytes. It would fit into just 8 bytes (a `long`) if we stored them as a bitfield. That would also simplify serialization (numbering 60 `Datamember` is no fun) as well as `Equals` and `GetHashCode` implementations.
In fact `GetHashCode()` impl. is currently horrible: `bool.GetHashCode()` simply returns 1 or 0. So all those chained `^` xor just compute whether there's an odd or even number of true flags ☹️
> Remove IsTakeSupported from SqlProviderFlags

- Source/LinqToDB/Mapping/PropertyMappingBuilder.cs
The summary tag for the IsNotNull() method was previously duplicating the description
used by IsNullable(), which was misleading. This change updates the documentation
to clearly state that IsNotNull() marks the column as NOT NULL, disallowing any NULL values.
See the [issue](https://github.com/linq2db/linq2db/issues/4941) for details
> Fixed IsNotNull method misleading summary (Issue #4941)

- Source/LinqToDB/Data/TraceInfo.cs
Don't add space to trace when not necesary.
This space keeps reappearing in baselines making review a nightmare (e.g. here https://github.com/linq2db/linq2db.baselines/pull/1445 )
> Fix configuration string tracing

- Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
Fix #4973
Required for `OVERRIDING .. VALUE` clause generation (https://www.ibm.com/docs/en/i/7.6.0?topic=statements-insert) without copy-paste of base implementation.
> add INSERT query sql generation extension point before values clause (VALUES or SELECT)

- Build/Azure/scripts/pgsql18.sh
- Data/Setup Scripts/pgsql18.cmd
- Source/LinqToDB/Internal/DataProvider/Access/AccessSqlBuilderBase.cs
- Source/LinqToDB/Internal/DataProvider/DB2/DB2MappingSchema.cs
- Source/LinqToDB/Internal/DataProvider/DB2/DB2SqlBuilderBase.cs
- Source/LinqToDB/Internal/DataProvider/DB2/DB2SqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/Firebird/FirebirdMappingSchema.cs
- Source/LinqToDB/Internal/DataProvider/Firebird/FirebirdSqlBuilder.Merge.cs
- Source/LinqToDB/Internal/DataProvider/Firebird/FirebirdSqlBuilder.cs
- Source/LinqToDB/Internal/DataProvider/Firebird/FirebirdSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/MySql/MySqlSqlBuilder.cs
- Source/LinqToDB/Internal/DataProvider/MySql/MySqlSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/PostgreSQL/PostgreSQLSqlBuilder.Merge.cs
- Source/LinqToDB/Internal/DataProvider/PostgreSQL/PostgreSQLSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/SapHana/SapHanaDataProvider.cs
- Source/LinqToDB/Internal/DataProvider/SapHana/SapHanaSqlBuilder.cs
- Source/LinqToDB/Internal/DataProvider/SapHana/SapHanaSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/SqlServer/SqlServerSqlBuilder.cs
- Source/LinqToDB/Internal/DataProvider/SqlServer/SqlServerSqlExpressionConvertVisitor.cs
- Source/LinqToDB/Internal/DataProvider/Sybase/SybaseSqlBuilder.cs
- Source/LinqToDB/Internal/DataProvider/Sybase/SybaseSqlExpressionConvertVisitor.cs
- Tests/Linq/Linq/MappingTests.cs
Fix #4955
Problem: database/provider could infer wrong column type from literal or parameter for specific value resulting im mapping expression using wrong reader methods. When same query executed later with another value that is not compatible with generated reader - it fails during mapping.
Affects different databases in different way:
- for most of databases if for value we use literal of other type (e.g. for bigint generate int literal) - database infer not the type we expect
- for some databases/providers it also affects parameters, because they don't use type parameter information from parameter
- also it could affect NULL literal and/or null-valued parameters for some databases
Here we implement temporary fix (hopefully v7 will have new mapping subsystem that could handle it …
> Fix mapping typing by constant

- Source/LinqToDB/Internal/SqlProvider/SqlExpressionOptimizerVisitor.cs
- Tests/Linq/Linq/WhereTests.cs
**Critical**
Optmizer may wrong optimize
```sql
x.Prop = 3 AND (x.Value = "A" OR x.Value = "B") AND x.Value = "A"
```
to
```sql
x.Value = "A"
```
> Disabled wrong optimization code.

- Source/LinqToDB/Internal/Linq/Builder/ExpressionBuildVisitor.cs
- Source/LinqToDB/Internal/Linq/Builder/SelectContext.cs
- Tests/Linq/Linq/ConditionalTests.cs
- Tests/Linq/Linq/ConstantTests.cs
to bug or not to bug...
we can define nullable constant in two ways:
* `(int?)1` - this is converted to SQL
* `1 as int?` - this fails, and in geneal it is discussionable, those both are not the same, `as` is not `convert` it is [try_convert](https://learn.microsoft.com/ru-ru/sql/t-sql/functions/try-convert-transact-sql?view=sql-server-ver17) but in any way this is regression
> v6 regression: nullable constant definition with as keyword fails
